import React, { useState } from "react";
import { Layers, AlertTriangle, Eye, Heart, AlertCircle, Flag, Sparkles, FileText, X, Plus, ChevronRight } from "lucide-react";
import { SHOW_DETAILS } from "../constants.js";
import { SectionHeader, ModalCard, InfoBlock } from "./Shared.jsx";

const FLAG_ICONS = {
  Violence:          AlertTriangle,
  "Mature Themes":   Eye,
  "Brief Nudity":    Eye,
  "Medical Content": Heart,
  "Disturbing Content": AlertTriangle,
};

function ShowHero({ details, nextAiring, children }) {
  return (
    <div style={{ borderRadius: "8px", padding: "24px", position: "relative", overflow: "hidden", background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
      <div style={{ position: "absolute", top: 0, right: 0, width: "256px", height: "256px", opacity: 0.1, pointerEvents: "none", background: "radial-gradient(circle, #f5a623 0%, transparent 70%)" }} />
      <div style={{ position: "relative" }}>
        <div style={{ fontSize: "12px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "8px", color: "#f5a623" }}>{details.genre} · {details.season}</div>
        <h2 className="font-display" style={{ fontWeight: 900, fontSize: "30px", color: "white", lineHeight: "1.25", marginBottom: "8px", margin: "0 0 8px 0" }}>{details.title}</h2>
        <p style={{ fontSize: "14px", maxWidth: "672px", color: "#a8b4cc", margin: "0 0 16px 0" }}>{details.tagline}</p>
        <div style={{ display: "flex", gap: "24px", fontSize: "12px", color: "#a8b4cc" }}>
          <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Episodes</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{details.episodes}</div></div>
          <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Season</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{details.season}</div></div>
          {nextAiring && <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Next Airing</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{nextAiring.time}</div></div>}
        </div>
        {children}
      </div>
    </div>
  );
}

function FlagsCard({ flags }) {
  if (!flags.length) return null;
  return (
    <ModalCard title="Content Advisories" eyebrow="Auto-synced from data lake" icon={AlertTriangle} iconColor="#d97706">
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: "12px" }}>
        {flags.map((f) => {
          const Icon = FLAG_ICONS[f.kind] || AlertCircle;
          return (
            <div key={f.kind} style={{ borderRadius: "4px", padding: "12px", background: "#fef3c7", border: "1px solid #fde68a" }}>
              <Icon style={{ width: "16px", height: "16px", marginBottom: "8px", color: "#92400e" }} />
              <div style={{ fontSize: "12px", fontWeight: 700, color: "#92400e" }}>{f.kind}</div>
              <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.05em", marginTop: "2px", color: "#b45309" }}>{f.level}</div>
            </div>
          );
        })}
      </div>
      <p style={{ fontSize: "12px", marginTop: "12px", fontStyle: "italic", color: "#6b6a63", margin: "12px 0 0 0" }}>Advisories automatically generated by upstream scheduling + screening systems.</p>
    </ModalCard>
  );
}

function RightsCard({ rights }) {
  return (
    <ModalCard title="Rights & Clearances" eyebrow="Rights management system" icon={Flag} iconColor="#7c2d12">
      <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: "16px", fontSize: "14px" }}>
        <InfoBlock label="Window"     value={rights.window} />
        <InfoBlock label="Territory"  value={rights.territory} />
        <InfoBlock label="Clearances" value={rights.clearances} />
      </div>
    </ModalCard>
  );
}

function FundingCard({ funding }) {
  return (
    <ModalCard title="Funding Credits" eyebrow="Rights management system" icon={Sparkles} iconColor="#059669">
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        {funding.map((f) => (
          <span key={f} style={{ fontSize: "12px", padding: "6px 12px", borderRadius: "9999px", background: "#f5f3ee", color: "#1a2744", border: "1px solid #e5e2d8" }}>{f}</span>
        ))}
      </div>
    </ModalCard>
  );
}

function ContributorsCard({ contributors, role }) {
  return (
    <ModalCard title="Contributor Notes" eyebrow="Custom annotations" icon={FileText} iconColor="#1a2744">
      <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
        {contributors.map((c, i) => (
          <div key={i} style={{ borderRadius: "4px", padding: "12px", background: "#f5f3ee" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
              <div style={{ width: "28px", height: "28px", borderRadius: "9999px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "12px", fontWeight: 700, color: "white", background: "#1a2744", flexShrink: 0 }}>
                {c.name.split(" ").map((n) => n[0]).join("")}
              </div>
              <div>
                <div style={{ fontSize: "14px", fontWeight: 600, color: "#1a2744" }}>{c.name}</div>
                <div style={{ fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.05em", color: "#6b6a63" }}>{c.role}</div>
              </div>
            </div>
            <p style={{ fontSize: "14px", color: "#3a3833", margin: 0 }}>{c.note}</p>
          </div>
        ))}
        {role === "hq" && (
          <button style={{ fontSize: "12px", fontWeight: 600, display: "flex", alignItems: "center", gap: "4px", color: "#1a2744", background: "transparent", border: "none", cursor: "pointer", padding: 0 }}>
            <Plus style={{ width: "14px", height: "14px" }} /> Add contributor note
          </button>
        )}
      </div>
    </ModalCard>
  );
}

// ========== SHOW 360° TAB ==========
export function Show360Browser({ selected, setSelected, role, schedule }) {
  const details    = SHOW_DETAILS[selected];
  const nextAiring = schedule.find((s) => s.show === selected);
  if (!details) return null;

  return (
    <div className="fade-in-up" style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      <SectionHeader
        eyebrow="Consolidated View"
        title="Show 360°"
        subtitle="A single pane aggregating scheduling, rights, funding, and contributor notes across all upstream systems."
      />

      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        {Object.keys(SHOW_DETAILS).map((s) => (
          <button key={s} onClick={() => setSelected(s)} style={{ padding: "6px 12px", borderRadius: "4px", fontSize: "12px", fontWeight: 600, background: selected === s ? "#1a2744" : "white", color: selected === s ? "white" : "#1a2744", border: `1px solid ${selected === s ? "#1a2744" : "#e5e2d8"}`, cursor: "pointer" }}>
            {s}
          </button>
        ))}
      </div>

      <ShowHero details={details} nextAiring={nextAiring} />
      <FlagsCard flags={details.flags} />
      <RightsCard rights={details.rights} />
      <FundingCard funding={details.funding} />
      <ContributorsCard contributors={details.contributors} role={role} />
    </div>
  );
}

// ========== SHOW 360° MODAL (opened from schedule cards) ==========
export function Show360Content({ show, role, onClose, onReportIssue, schedule }) {
  const [pickingEpisode, setPickingEpisode] = useState(false);
  const details  = SHOW_DETAILS[show];
  const airings  = schedule.filter((s) => s.show === show);
  const nextAiring = airings[0];
  if (!details) return null;

  if (pickingEpisode) {
    return (
      <>
        <div style={{ position: "relative", padding: "20px 24px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexShrink: 0, background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
          <div style={{ position: "relative", flex: "1 1 0%", minWidth: 0 }}>
            <div style={{ fontSize: "10px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "4px", color: "#f5a623", display: "flex", alignItems: "center", gap: "4px" }}>
              <Flag style={{ width: "12px", height: "12px", display: "inline" }} /> Report Issue · Choose Episode
            </div>
            <h2 className="font-display" style={{ fontWeight: 900, fontSize: "24px", color: "white", lineHeight: "1.25", margin: 0 }}>{details.title}</h2>
            <p style={{ fontSize: "14px", marginTop: "4px", color: "#a8b4cc", margin: "4px 0 0 0" }}>Select the specific episode you're reporting an issue with.</p>
          </div>
          <button onClick={onClose} style={{ position: "relative", padding: "6px", borderRadius: "4px", marginLeft: "16px", background: "transparent", border: "none", cursor: "pointer" }}>
            <X style={{ width: "20px", height: "20px", color: "white" }} />
          </button>
        </div>
        <div className="scrollbar-thin" style={{ overflowY: "auto", flex: 1, padding: "16px 24px", display: "flex", flexDirection: "column", gap: "8px" }}>
          {airings.length === 0 && (
            <p style={{ fontSize: "14px", textAlign: "center", padding: "32px 0", color: "#6b6a63", margin: 0 }}>No upcoming airings found for this show.</p>
          )}
          {airings.map((ep) => (
            <button key={ep.id} onClick={() => onReportIssue(ep)} className="bow-full" style={{ width: "100%", textAlign: "left", borderRadius: "8px", padding: "16px", display: "flex", alignItems: "center", gap: "12px", background: "white", border: "1px solid #e5e2d8", cursor: "pointer" }}>
              <div style={{ flex: "1 1 0%", minWidth: 0 }}>
                <div style={{ fontWeight: 600, fontSize: "14px", color: "#1a2744" }}>{ep.episode}</div>
                <div style={{ fontSize: "12px", marginTop: "2px", color: "#6b6a63" }}>{ep.date} · {ep.time} · {ep.duration} min</div>
              </div>
              <ChevronRight style={{ width: "16px", height: "16px", flexShrink: 0, color: "#a8a59a" }} />
            </button>
          ))}
        </div>
        <div style={{ padding: "16px 24px", flexShrink: 0, background: "white", borderTop: "1px solid #e5e2d8" }}>
          <button onClick={() => setPickingEpisode(false)} style={{ fontSize: "14px", fontWeight: 600, color: "#6b6a63", background: "transparent", border: "none", cursor: "pointer", padding: 0 }}>← Back to show details</button>
        </div>
      </>
    );
  }

  return (
    <>
      <div style={{ position: "relative", padding: "24px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexShrink: 0, background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
        <div style={{ position: "absolute", top: 0, right: 0, width: "384px", height: "100%", opacity: 0.1, pointerEvents: "none", background: "radial-gradient(circle at top right, #f5a623 0%, transparent 60%)" }} />
        <div style={{ position: "relative", flex: "1 1 0%", minWidth: 0 }}>
          <div style={{ fontSize: "10px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: "8px", color: "#f5a623", display: "flex", alignItems: "center", gap: "4px" }}>
            <Layers style={{ width: "12px", height: "12px", display: "inline" }} /> Show 360° · {details.genre}
          </div>
          <h2 className="font-display" style={{ fontWeight: 900, fontSize: "30px", color: "white", lineHeight: "1.25", marginBottom: "4px", margin: "0 0 4px 0" }}>{details.title}</h2>
          <p style={{ fontSize: "14px", color: "#a8b4cc", margin: "0 0 16px 0" }}>{details.tagline}</p>
          <div style={{ display: "flex", gap: "24px", fontSize: "12px", color: "#a8b4cc" }}>
            <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Episodes</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{details.episodes}</div></div>
            <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Season</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{details.season}</div></div>
            {nextAiring && <div><div style={{ textTransform: "uppercase", letterSpacing: "0.05em", opacity: 0.7 }}>Next Airing</div><div className="font-display" style={{ fontWeight: 700, color: "white", fontSize: "18px" }}>{nextAiring.time}</div></div>}
          </div>
        </div>
        <button onClick={onClose} style={{ position: "relative", padding: "6px", borderRadius: "4px", marginLeft: "16px", background: "transparent", border: "none", cursor: "pointer" }}>
          <X style={{ width: "20px", height: "20px", color: "white" }} />
        </button>
      </div>

      <div className="scrollbar-thin" style={{ overflowY: "auto", flex: 1, padding: "20px 24px", display: "flex", flexDirection: "column", gap: "16px" }}>
        <FlagsCard flags={details.flags} />
        <RightsCard rights={details.rights} />
        <FundingCard funding={details.funding} />
        <ContributorsCard contributors={details.contributors} role={role} />
      </div>

      <div style={{ padding: "16px 24px", display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0, background: "white", borderTop: "1px solid #e5e2d8" }}>
        <div style={{ fontSize: "12px", color: "#6b6a63" }}>Data aggregated from Staffbase scheduling, rights, and CMS systems.</div>
        <div style={{ display: "flex", gap: "8px" }}>
          <button onClick={onClose} style={{ padding: "8px 16px", fontSize: "14px", fontWeight: 600, borderRadius: "8px", color: "#6b6a63", background: "transparent", border: "none", cursor: "pointer" }}>Close</button>
          {role === "station" && airings.length > 0 && (
            <button onClick={() => setPickingEpisode(true)} style={{ padding: "8px 16px", fontSize: "14px", fontWeight: 700, borderRadius: "8px", display: "flex", alignItems: "center", gap: "8px", background: "#f5a623", color: "#1a2744", border: "none", cursor: "pointer" }}>
              <Flag style={{ width: "14px", height: "14px" }} /> Report Issue
            </button>
          )}
        </div>
      </div>
    </>
  );
}
