import React, { useState } from "react";
import { Layers, AlertTriangle, Eye, Heart, AlertCircle, Flag, Sparkles, FileText, X, Plus, ChevronRight } from "lucide-react";
import { SHOW_DETAILS } from "../constants.js";
import { SectionHeader, ModalCard, InfoBlock } from "./Shared.jsx";

const FLAG_ICONS = {
  Violence:          AlertTriangle,
  "Mature Themes":   Eye,
  "Brief Nudity":    Eye,
  "Medical Content": Heart,
  "Disturbing Content": AlertTriangle,
};

function ShowHero({ details, nextAiring, children }) {
  return (
    <div className="rounded-lg p-6 relative overflow-hidden" style={{ background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
      <div className="absolute top-0 right-0 w-64 h-64 opacity-10 pointer-events-none" style={{ background: "radial-gradient(circle, #f5a623 0%, transparent 70%)" }} />
      <div className="relative">
        <div className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "#f5a623" }}>{details.genre} · {details.season}</div>
        <h2 className="font-display font-black text-3xl text-white leading-tight mb-2">{details.title}</h2>
        <p className="text-sm max-w-2xl" style={{ color: "#a8b4cc" }}>{details.tagline}</p>
        <div className="flex gap-6 mt-4 text-xs" style={{ color: "#a8b4cc" }}>
          <div><div className="uppercase tracking-wider opacity-70">Episodes</div><div className="font-display font-bold text-white text-lg">{details.episodes}</div></div>
          <div><div className="uppercase tracking-wider opacity-70">Season</div><div className="font-display font-bold text-white text-lg">{details.season}</div></div>
          {nextAiring && <div><div className="uppercase tracking-wider opacity-70">Next Airing</div><div className="font-display font-bold text-white text-lg">{nextAiring.time}</div></div>}
        </div>
        {children}
      </div>
    </div>
  );
}

function FlagsCard({ flags }) {
  if (!flags.length) return null;
  return (
    <ModalCard title="Content Advisories" eyebrow="Auto-synced from data lake" icon={AlertTriangle} iconColor="#d97706">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {flags.map((f) => {
          const Icon = FLAG_ICONS[f.kind] || AlertCircle;
          return (
            <div key={f.kind} className="rounded p-3" style={{ background: "#fef3c7", border: "1px solid #fde68a" }}>
              <Icon className="w-4 h-4 mb-2" style={{ color: "#92400e" }} />
              <div className="text-xs font-bold" style={{ color: "#92400e" }}>{f.kind}</div>
              <div className="text-[11px] uppercase tracking-wider mt-0.5" style={{ color: "#b45309" }}>{f.level}</div>
            </div>
          );
        })}
      </div>
      <p className="text-xs mt-3 italic" style={{ color: "#6b6a63" }}>Advisories automatically generated by upstream scheduling + screening systems.</p>
    </ModalCard>
  );
}

function RightsCard({ rights }) {
  return (
    <ModalCard title="Rights & Clearances" eyebrow="Rights management system" icon={Flag} iconColor="#7c2d12">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
        <InfoBlock label="Window"     value={rights.window} />
        <InfoBlock label="Territory"  value={rights.territory} />
        <InfoBlock label="Clearances" value={rights.clearances} />
      </div>
    </ModalCard>
  );
}

function FundingCard({ funding }) {
  return (
    <ModalCard title="Funding Credits" eyebrow="Rights management system" icon={Sparkles} iconColor="#059669">
      <div className="flex gap-2 flex-wrap">
        {funding.map((f) => (
          <span key={f} className="text-xs px-3 py-1.5 rounded-full" style={{ background: "#f5f3ee", color: "#1a2744", border: "1px solid #e5e2d8" }}>{f}</span>
        ))}
      </div>
    </ModalCard>
  );
}

function ContributorsCard({ contributors, role }) {
  return (
    <ModalCard title="Contributor Notes" eyebrow="Custom annotations" icon={FileText} iconColor="#1a2744">
      <div className="space-y-3">
        {contributors.map((c, i) => (
          <div key={i} className="rounded p-3" style={{ background: "#f5f3ee" }}>
            <div className="flex items-center gap-2 mb-1">
              <div className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold text-white" style={{ background: "#1a2744" }}>
                {c.name.split(" ").map((n) => n[0]).join("")}
              </div>
              <div>
                <div className="text-sm font-semibold" style={{ color: "#1a2744" }}>{c.name}</div>
                <div className="text-[11px] uppercase tracking-wider" style={{ color: "#6b6a63" }}>{c.role}</div>
              </div>
            </div>
            <p className="text-sm" style={{ color: "#3a3833" }}>{c.note}</p>
          </div>
        ))}
        {role === "hq" && (
          <button className="text-xs font-semibold flex items-center gap-1" style={{ color: "#1a2744" }}>
            <Plus className="w-3.5 h-3.5" /> Add contributor note
          </button>
        )}
      </div>
    </ModalCard>
  );
}

// ========== SHOW 360° TAB ==========
export function Show360Browser({ selected, setSelected, role, schedule }) {
  const details    = SHOW_DETAILS[selected];
  const nextAiring = schedule.find((s) => s.show === selected);
  if (!details) return null;

  return (
    <div className="space-y-6 fade-in-up">
      <SectionHeader
        eyebrow="Consolidated View"
        title="Show 360°"
        subtitle="A single pane aggregating scheduling, rights, funding, and contributor notes across all upstream systems."
      />

      <div className="flex gap-2 flex-wrap">
        {Object.keys(SHOW_DETAILS).map((s) => (
          <button key={s} onClick={() => setSelected(s)} className="px-3 py-1.5 rounded text-xs font-semibold" style={{ background: selected === s ? "#1a2744" : "white", color: selected === s ? "white" : "#1a2744", border: `1px solid ${selected === s ? "#1a2744" : "#e5e2d8"}` }}>
            {s}
          </button>
        ))}
      </div>

      <ShowHero details={details} nextAiring={nextAiring} />
      <FlagsCard flags={details.flags} />
      <RightsCard rights={details.rights} />
      <FundingCard funding={details.funding} />
      <ContributorsCard contributors={details.contributors} role={role} />
    </div>
  );
}

// ========== SHOW 360° MODAL (opened from schedule cards) ==========
export function Show360Content({ show, role, onClose, onReportIssue, schedule }) {
  const [pickingEpisode, setPickingEpisode] = useState(false);
  const details  = SHOW_DETAILS[show];
  const airings  = schedule.filter((s) => s.show === show);
  const nextAiring = airings[0];
  if (!details) return null;

  if (pickingEpisode) {
    return (
      <>
        <div className="relative px-6 py-5 flex items-start justify-between flex-shrink-0" style={{ background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
          <div className="relative flex-1 min-w-0">
            <div className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: "#f5a623" }}>
              <Flag className="w-3 h-3 inline mr-1" /> Report Issue · Choose Episode
            </div>
            <h2 className="font-display font-black text-2xl text-white leading-tight">{details.title}</h2>
            <p className="text-sm mt-1" style={{ color: "#a8b4cc" }}>Select the specific episode you're reporting an issue with.</p>
          </div>
          <button onClick={onClose} className="relative p-1.5 rounded hover:bg-white/10 transition-colors ml-4">
            <X className="w-5 h-5 text-white" />
          </button>
        </div>
        <div className="overflow-y-auto scrollbar-thin flex-1 px-6 py-4 space-y-2">
          {airings.length === 0 && (
            <p className="text-sm text-center py-8" style={{ color: "#6b6a63" }}>No upcoming airings found for this show.</p>
          )}
          {airings.map((ep) => (
            <button key={ep.id} onClick={() => onReportIssue(ep)} className="w-full text-left rounded-lg p-4 flex items-center gap-3 transition-all hover:shadow-md" style={{ background: "white", border: "1px solid #e5e2d8" }}>
              <div className="flex-1 min-w-0">
                <div className="font-semibold text-sm" style={{ color: "#1a2744" }}>{ep.episode}</div>
                <div className="text-xs mt-0.5" style={{ color: "#6b6a63" }}>{ep.date} · {ep.time} · {ep.duration} min</div>
              </div>
              <ChevronRight className="w-4 h-4 flex-shrink-0" style={{ color: "#a8a59a" }} />
            </button>
          ))}
        </div>
        <div className="px-6 py-4 flex-shrink-0" style={{ background: "white", borderTop: "1px solid #e5e2d8" }}>
          <button onClick={() => setPickingEpisode(false)} className="text-sm font-semibold" style={{ color: "#6b6a63" }}>← Back to show details</button>
        </div>
      </>
    );
  }

  return (
    <>
      <div className="relative px-6 py-6 flex items-start justify-between flex-shrink-0" style={{ background: "linear-gradient(135deg, #1a2744 0%, #2d3f6b 100%)" }}>
        <div className="absolute top-0 right-0 w-96 h-full opacity-10 pointer-events-none" style={{ background: "radial-gradient(circle at top right, #f5a623 0%, transparent 60%)" }} />
        <div className="relative flex-1 min-w-0">
          <div className="text-xs font-bold uppercase tracking-widest mb-2" style={{ color: "#f5a623" }}>
            <Layers className="w-3 h-3 inline mr-1" /> Show 360° · {details.genre}
          </div>
          <h2 className="font-display font-black text-3xl text-white leading-tight mb-1">{details.title}</h2>
          <p className="text-sm" style={{ color: "#a8b4cc" }}>{details.tagline}</p>
          <div className="flex gap-6 mt-4 text-xs" style={{ color: "#a8b4cc" }}>
            <div><div className="uppercase tracking-wider opacity-70">Episodes</div><div className="font-display font-bold text-white text-lg">{details.episodes}</div></div>
            <div><div className="uppercase tracking-wider opacity-70">Season</div><div className="font-display font-bold text-white text-lg">{details.season}</div></div>
            {nextAiring && <div><div className="uppercase tracking-wider opacity-70">Next Airing</div><div className="font-display font-bold text-white text-lg">{nextAiring.time}</div></div>}
          </div>
        </div>
        <button onClick={onClose} className="relative p-1.5 rounded hover:bg-white/10 transition-colors ml-4">
          <X className="w-5 h-5 text-white" />
        </button>
      </div>

      <div className="overflow-y-auto scrollbar-thin flex-1 px-6 py-5 space-y-4">
        <FlagsCard flags={details.flags} />
        <RightsCard rights={details.rights} />
        <FundingCard funding={details.funding} />
        <ContributorsCard contributors={details.contributors} role={role} />
      </div>

      <div className="px-6 py-4 flex items-center justify-between flex-shrink-0" style={{ background: "white", borderTop: "1px solid #e5e2d8" }}>
        <div className="text-xs" style={{ color: "#6b6a63" }}>Data aggregated from Staffbase scheduling, rights, and CMS systems.</div>
        <div className="flex gap-2">
          <button onClick={onClose} className="px-4 py-2 text-sm font-semibold rounded-lg transition-colors hover:bg-gray-100" style={{ color: "#6b6a63" }}>Close</button>
          {role === "station" && airings.length > 0 && (
            <button onClick={() => setPickingEpisode(true)} className="px-4 py-2 text-sm font-bold rounded-lg flex items-center gap-2 transition-all" style={{ background: "#f5a623", color: "#1a2744" }}>
              <Flag className="w-3.5 h-3.5" /> Report Issue
            </button>
          )}
        </div>
      </div>
    </>
  );
}
