// i18n bundles. `en_US` is the source of truth; the branch's
// `availableLocales` on verizon-demo are fr_CA, en_US, es_MX, es_ES, fr_FR,
// de_DE and nl_NL, so all seven ship here.

import { Bundles } from "../tasks/shared/i18n";

export const AVAILABLE_LOCALES = ["en_US", "de_DE", "fr_FR", "fr_CA", "es_ES", "es_MX", "nl_NL"];

export const BUNDLES: Bundles = {
  en_US: {
    "widget.title": "Engagement leaderboard",
    "state.loading": "Loading engagement data…",
    "state.error": "Could not load engagement data.",
    "state.empty": "No engagement activity yet.",
    "state.emptyTile": "No activity in this period.",
    "state.retry": "Try again",
    "state.refresh": "Refresh",
    "state.sample": "Sample data",
    "state.partial": "Partial data — some channels were not readable.",
    "state.configure": "Set the base URL and API token in the widget settings.",

    "window.all": "All time",
    "window.7d": "Last 7 days",
    "window.30d": "Last 30 days",
    "window.90d": "Last 90 days",
    "window.12m": "Last 12 months",
    "window.custom": "Custom range",
    "window.widened": "No activity in the selected period — showing all time.",
    "window.updated": "Updated",

    "metric.mostActive": "Most active",
    "metric.mostActive.sub": "Comments, reactions and posts combined",
    "metric.mostEngaged": "Most engaged",
    "metric.mostEngaged.sub": "Weighted for depth and breadth of participation",
    "metric.topCommenter": "Top commenter",
    "metric.topCommenter.sub": "Most comments written",
    "metric.topReactor": "Top reactor",
    "metric.topReactor.sub": "Most reactions given",
    "metric.mostAppreciated": "Most appreciated",
    "metric.mostAppreciated.sub": "Most reactions received on their posts",
    "metric.topContributor": "Top contributor",
    "metric.topContributor.sub": "Most posts published",
    "metric.risingStar": "Rising star",
    "metric.risingStar.sub": "Biggest increase over the previous period",
    "metric.advocacy": "Social advocacy",
    "metric.advocacy.sub": "Most shared posts, credited to their author",

    "part.comments": "Comments",
    "part.reactions": "Reactions",
    "part.posts": "Posts",
    "part.breadth": "Breadth",
    "part.shares": "Shares",
    "part.clicks": "Clicks",

    "unit.actions": "actions",
    "unit.points": "points",
    "unit.comments": "comments",
    "unit.reactions": "reactions",
    "reaction.LIKE": "Like",
    "reaction.CELEBRATE": "Celebrate",
    "reaction.SUPPORT": "Support",
    "reaction.THANKS": "Thanks",
    "reaction.INSIGHTFUL": "Insightful",
    "unit.received": "reactions received",
    "unit.posts": "posts",
    "unit.shares": "shares",

    "advocacy.unknownPost": "Unknown post",
    "chart.previous": "Previous",
    "chart.current": "Current",
    "chart.breakdown": "How the score breaks down",
    "chart.mix": "Reaction mix",
    "nav.previous": "Previous metric",
    "nav.next": "Next metric",
    "map.title": "The engagement map",
    "map.sub": "Breadth of participation against sheer volume",
    "map.label": "Engagement map: participation breadth against total actions",
    "map.axisX": "Breadth",
    "map.axisY": "Volume",
    "window.from": "From",
    "window.to": "To",
    "state.partialN": "Partial data — {n} of {total} posts could not be read.",
    "a11y.rank": "Rank",
  },

  de_DE: {
    "widget.title": "Engagement-Bestenliste",
    "state.loading": "Engagement-Daten werden geladen…",
    "state.error": "Engagement-Daten konnten nicht geladen werden.",
    "state.empty": "Noch keine Engagement-Aktivität.",
    "state.emptyTile": "Keine Aktivität in diesem Zeitraum.",
    "state.retry": "Erneut versuchen",
    "state.refresh": "Aktualisieren",
    "state.sample": "Beispieldaten",
    "state.partial": "Unvollständige Daten – einige Kanäle waren nicht lesbar.",
    "state.configure": "Basis-URL und API-Token in den Widget-Einstellungen festlegen.",

    "window.all": "Gesamter Zeitraum",
    "window.7d": "Letzte 7 Tage",
    "window.30d": "Letzte 30 Tage",
    "window.90d": "Letzte 90 Tage",
    "window.12m": "Letzte 12 Monate",
    "window.custom": "Eigener Zeitraum",
    "window.widened": "Keine Aktivität im gewählten Zeitraum – gesamter Zeitraum wird angezeigt.",
    "window.updated": "Aktualisiert",

    "metric.mostActive": "Aktivste Person",
    "metric.mostActive.sub": "Kommentare, Reaktionen und Beiträge zusammen",
    "metric.mostEngaged": "Höchstes Engagement",
    "metric.mostEngaged.sub": "Gewichtet nach Tiefe und Breite der Beteiligung",
    "metric.topCommenter": "Top-Kommentator",
    "metric.topCommenter.sub": "Die meisten Kommentare geschrieben",
    "metric.topReactor": "Top-Reaktionen",
    "metric.topReactor.sub": "Die meisten Reaktionen gegeben",
    "metric.mostAppreciated": "Größte Wertschätzung",
    "metric.mostAppreciated.sub": "Die meisten Reaktionen auf eigene Beiträge",
    "metric.topContributor": "Top-Autor",
    "metric.topContributor.sub": "Die meisten Beiträge veröffentlicht",
    "metric.risingStar": "Aufsteiger",
    "metric.risingStar.sub": "Größter Zuwachs gegenüber dem Vorzeitraum",
    "metric.advocacy": "Social Advocacy",
    "metric.advocacy.sub": "Meistgeteilte Beiträge, dem Autor zugeordnet",

    "part.comments": "Kommentare",
    "part.reactions": "Reaktionen",
    "part.posts": "Beiträge",
    "part.breadth": "Reichweite",
    "part.shares": "Geteilt",
    "part.clicks": "Klicks",

    "unit.actions": "Aktionen",
    "unit.points": "Punkte",
    "unit.comments": "Kommentare",
    "unit.reactions": "Reaktionen",
    "reaction.LIKE": "Gefällt mir",
    "reaction.CELEBRATE": "Glückwunsch",
    "reaction.SUPPORT": "Unterstützung",
    "reaction.THANKS": "Danke",
    "reaction.INSIGHTFUL": "Aufschlussreich",
    "unit.received": "Reaktionen erhalten",
    "unit.posts": "Beiträge",
    "unit.shares": "Mal geteilt",

    "advocacy.unknownPost": "Unbekannter Beitrag",
    "chart.previous": "Vorher",
    "chart.current": "Aktuell",
    "chart.breakdown": "Zusammensetzung der Punktzahl",
    "chart.mix": "Reaktionsmix",
    "nav.previous": "Vorherige Kennzahl",
    "nav.next": "Nächste Kennzahl",
    "map.title": "Die Engagement-Karte",
    "map.sub": "Breite der Beteiligung im Verhältnis zur Menge",
    "map.label": "Engagement-Karte: Beteiligungsbreite gegenüber Gesamtaktionen",
    "map.axisX": "Breite",
    "map.axisY": "Menge",
    "window.from": "Von",
    "window.to": "Bis",
    "state.partialN": "Unvollständige Daten – {n} von {total} Beiträgen konnten nicht gelesen werden.",
    "a11y.rank": "Rang",
  },

  fr_FR: {
    "widget.title": "Classement d'engagement",
    "state.loading": "Chargement des données d'engagement…",
    "state.error": "Impossible de charger les données d'engagement.",
    "state.empty": "Aucune activité d'engagement pour l'instant.",
    "state.emptyTile": "Aucune activité sur cette période.",
    "state.retry": "Réessayer",
    "state.refresh": "Actualiser",
    "state.sample": "Données d'exemple",
    "state.partial": "Données partielles — certains canaux n'ont pas pu être lus.",
    "state.configure": "Définissez l'URL de base et le jeton d'API dans les paramètres du widget.",

    "window.all": "Depuis le début",
    "window.7d": "7 derniers jours",
    "window.30d": "30 derniers jours",
    "window.90d": "90 derniers jours",
    "window.12m": "12 derniers mois",
    "window.custom": "Période personnalisée",
    "window.widened": "Aucune activité sur la période choisie — affichage depuis le début.",
    "window.updated": "Mis à jour",

    "metric.mostActive": "Le plus actif",
    "metric.mostActive.sub": "Commentaires, réactions et publications cumulés",
    "metric.mostEngaged": "Le plus engagé",
    "metric.mostEngaged.sub": "Pondéré selon l'intensité et la diversité de la participation",
    "metric.topCommenter": "Top commentateur",
    "metric.topCommenter.sub": "Le plus de commentaires rédigés",
    "metric.topReactor": "Top réactions",
    "metric.topReactor.sub": "Le plus de réactions données",
    "metric.mostAppreciated": "Le plus apprécié",
    "metric.mostAppreciated.sub": "Le plus de réactions reçues sur ses publications",
    "metric.topContributor": "Top contributeur",
    "metric.topContributor.sub": "Le plus de publications",
    "metric.risingStar": "Étoile montante",
    "metric.risingStar.sub": "Plus forte progression par rapport à la période précédente",
    "metric.advocacy": "Relais social",
    "metric.advocacy.sub": "Publications les plus partagées, attribuées à leur auteur",

    "part.comments": "Commentaires",
    "part.reactions": "Réactions",
    "part.posts": "Publications",
    "part.breadth": "Diversité",
    "part.shares": "Partages",
    "part.clicks": "Clics",

    "unit.actions": "actions",
    "unit.points": "points",
    "unit.comments": "commentaires",
    "unit.reactions": "réactions",
    "reaction.LIKE": "J’aime",
    "reaction.CELEBRATE": "Bravo",
    "reaction.SUPPORT": "Soutien",
    "reaction.THANKS": "Merci",
    "reaction.INSIGHTFUL": "Instructif",
    "unit.received": "réactions reçues",
    "unit.posts": "publications",
    "unit.shares": "partages",

    "advocacy.unknownPost": "Publication inconnue",
    "chart.previous": "Précédent",
    "chart.current": "Actuel",
    "chart.breakdown": "Composition du score",
    "chart.mix": "Répartition des réactions",
    "nav.previous": "Indicateur précédent",
    "nav.next": "Indicateur suivant",
    "map.title": "La carte d'engagement",
    "map.sub": "Diversité de la participation face au volume",
    "map.label": "Carte d'engagement : diversité de participation et actions totales",
    "map.axisX": "Diversité",
    "map.axisY": "Volume",
    "window.from": "Du",
    "window.to": "Au",
    "state.partialN": "Données partielles — {n} publications sur {total} n'ont pas pu être lues.",
    "a11y.rank": "Rang",
  },

  es_ES: {
    "widget.title": "Clasificación de participación",
    "state.loading": "Cargando datos de participación…",
    "state.error": "No se pudieron cargar los datos de participación.",
    "state.empty": "Todavía no hay actividad.",
    "state.emptyTile": "Sin actividad en este periodo.",
    "state.retry": "Reintentar",
    "state.refresh": "Actualizar",
    "state.sample": "Datos de ejemplo",
    "state.partial": "Datos parciales: algunos canales no se pudieron leer.",
    "state.configure": "Configura la URL base y el token de API en los ajustes del widget.",

    "window.all": "Desde siempre",
    "window.7d": "Últimos 7 días",
    "window.30d": "Últimos 30 días",
    "window.90d": "Últimos 90 días",
    "window.12m": "Últimos 12 meses",
    "window.custom": "Periodo personalizado",
    "window.widened": "Sin actividad en el periodo seleccionado: se muestra desde siempre.",
    "window.updated": "Actualizado",

    "metric.mostActive": "Más activo",
    "metric.mostActive.sub": "Comentarios, reacciones y publicaciones combinados",
    "metric.mostEngaged": "Mayor participación",
    "metric.mostEngaged.sub": "Ponderado por profundidad y amplitud de la participación",
    "metric.topCommenter": "Top comentarista",
    "metric.topCommenter.sub": "Más comentarios escritos",
    "metric.topReactor": "Top reacciones",
    "metric.topReactor.sub": "Más reacciones dadas",
    "metric.mostAppreciated": "Más valorado",
    "metric.mostAppreciated.sub": "Más reacciones recibidas en sus publicaciones",
    "metric.topContributor": "Top colaborador",
    "metric.topContributor.sub": "Más publicaciones publicadas",
    "metric.risingStar": "Promesa emergente",
    "metric.risingStar.sub": "Mayor aumento respecto al periodo anterior",
    "metric.advocacy": "Difusión social",
    "metric.advocacy.sub": "Publicaciones más compartidas, atribuidas a su autor",

    "part.comments": "Comentarios",
    "part.reactions": "Reacciones",
    "part.posts": "Publicaciones",
    "part.breadth": "Amplitud",
    "part.shares": "Compartidos",
    "part.clicks": "Clics",

    "unit.actions": "acciones",
    "unit.points": "puntos",
    "unit.comments": "comentarios",
    "unit.reactions": "reacciones",
    "reaction.LIKE": "Me gusta",
    "reaction.CELEBRATE": "Enhorabuena",
    "reaction.SUPPORT": "Apoyo",
    "reaction.THANKS": "Gracias",
    "reaction.INSIGHTFUL": "Revelador",
    "unit.received": "reacciones recibidas",
    "unit.posts": "publicaciones",
    "unit.shares": "veces compartido",

    "advocacy.unknownPost": "Publicación desconocida",
    "chart.previous": "Anterior",
    "chart.current": "Actual",
    "chart.breakdown": "Desglose de la puntuación",
    "chart.mix": "Mezcla de reacciones",
    "nav.previous": "Métrica anterior",
    "nav.next": "Métrica siguiente",
    "map.title": "El mapa de participación",
    "map.sub": "Amplitud de la participación frente al volumen",
    "map.label": "Mapa de participación: amplitud frente a acciones totales",
    "map.axisX": "Amplitud",
    "map.axisY": "Volumen",
    "window.from": "Desde",
    "window.to": "Hasta",
    "state.partialN": "Datos parciales: no se pudieron leer {n} de {total} publicaciones.",
    "a11y.rank": "Puesto",
  },

  nl_NL: {
    "widget.title": "Betrokkenheidsklassement",
    "state.loading": "Betrokkenheidsgegevens laden…",
    "state.error": "Betrokkenheidsgegevens konden niet worden geladen.",
    "state.empty": "Nog geen activiteit.",
    "state.emptyTile": "Geen activiteit in deze periode.",
    "state.retry": "Opnieuw proberen",
    "state.refresh": "Vernieuwen",
    "state.sample": "Voorbeeldgegevens",
    "state.partial": "Onvolledige gegevens — sommige kanalen konden niet worden gelezen.",
    "state.configure": "Stel de basis-URL en het API-token in bij de widgetinstellingen.",

    "window.all": "Alle tijd",
    "window.7d": "Laatste 7 dagen",
    "window.30d": "Laatste 30 dagen",
    "window.90d": "Laatste 90 dagen",
    "window.12m": "Laatste 12 maanden",
    "window.custom": "Aangepaste periode",
    "window.widened": "Geen activiteit in de gekozen periode — alle tijd wordt getoond.",
    "window.updated": "Bijgewerkt",

    "metric.mostActive": "Meest actief",
    "metric.mostActive.sub": "Reacties, likes en berichten samen",
    "metric.mostEngaged": "Meest betrokken",
    "metric.mostEngaged.sub": "Gewogen naar diepte en breedte van deelname",
    "metric.topCommenter": "Topreageerder",
    "metric.topCommenter.sub": "De meeste reacties geschreven",
    "metric.topReactor": "Meeste likes gegeven",
    "metric.topReactor.sub": "De meeste reacties gegeven",
    "metric.mostAppreciated": "Meest gewaardeerd",
    "metric.mostAppreciated.sub": "De meeste likes op eigen berichten",
    "metric.topContributor": "Topbijdrager",
    "metric.topContributor.sub": "De meeste berichten gepubliceerd",
    "metric.risingStar": "Rijzende ster",
    "metric.risingStar.sub": "Grootste stijging ten opzichte van de vorige periode",
    "metric.advocacy": "Sociale ambassadeurs",
    "metric.advocacy.sub": "Meest gedeelde berichten, toegeschreven aan de auteur",

    "part.comments": "Reacties",
    "part.reactions": "Likes",
    "part.posts": "Berichten",
    "part.breadth": "Bereik",
    "part.shares": "Gedeeld",
    "part.clicks": "Kliks",

    "unit.actions": "acties",
    "unit.points": "punten",
    "unit.comments": "reacties",
    "unit.reactions": "likes",
    "reaction.LIKE": "Leuk",
    "reaction.CELEBRATE": "Gefeliciteerd",
    "reaction.SUPPORT": "Steun",
    "reaction.THANKS": "Bedankt",
    "reaction.INSIGHTFUL": "Verhelderend",
    "unit.received": "likes ontvangen",
    "unit.posts": "berichten",
    "unit.shares": "keer gedeeld",

    "advocacy.unknownPost": "Onbekend bericht",
    "chart.previous": "Vorige",
    "chart.current": "Huidig",
    "chart.breakdown": "Opbouw van de score",
    "chart.mix": "Verdeling van likes",
    "nav.previous": "Vorige maatstaf",
    "nav.next": "Volgende maatstaf",
    "map.title": "De betrokkenheidskaart",
    "map.sub": "Breedte van deelname tegenover puur volume",
    "map.label": "Betrokkenheidskaart: breedte van deelname tegenover totaal aantal acties",
    "map.axisX": "Breedte",
    "map.axisY": "Volume",
    "window.from": "Van",
    "window.to": "Tot",
    "state.partialN": "Onvolledige gegevens — {n} van {total} berichten konden niet worden gelezen.",
    "a11y.rank": "Positie",
  },
};

// fr_CA and es_MX differ only in a handful of conventions; they inherit the
// European bundle wholesale rather than duplicating 40 identical strings.
BUNDLES.fr_CA = { ...BUNDLES.fr_FR, "metric.advocacy": "Partage social" };
BUNDLES.es_MX = { ...BUNDLES.es_ES, "metric.advocacy": "Difusión social" };
