// i18n bundles for simple-task-widget.
// en_US is the canonical source; de_DE / ar_SA mirror the other task widgets so
// locale + RTL detection behave consistently. Missing keys fall back to en_US.
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    loading: "Loading…",
    empty: "No tasks to show",
    noneConfigured: "No tasks configured yet.",
    errorToggle: "Couldn't update the task. Please try again.",
    toggleTask: "Toggle task",
    markDone: "Mark as done",
    reopen: "Reopen task",
    description: "Description",
    noDescription: "No description provided.",
    dueLabel: "Due",
    overdueLabel: "Overdue",
    high: "High",
    medium: "Med",
    normal: "Low",
    recurring: "Recurring",
    attachments: "Attachments",
    add: "Add",
    noAttachments: "No attachments",
    comments: "Comments",
    addComment: "Add a comment…",
    noCommentsYet: "No comments yet.",
    couldntLoadComments: "Couldn't load comments.",
    send: "Send",
    attachFile: "Attach file",
    translateBtn: "Translate",
    showOriginal: "Show original",
    translating: "Translating…",
    noPreview: "No preview available",
  },
  de_DE: {
    loading: "Wird geladen…",
    empty: "Keine Aufgaben vorhanden",
    noneConfigured: "Noch keine Aufgaben konfiguriert.",
    errorToggle: "Aufgabe konnte nicht aktualisiert werden. Bitte erneut versuchen.",
    toggleTask: "Aufgabe umschalten",
    markDone: "Als erledigt markieren",
    reopen: "Aufgabe wieder öffnen",
    description: "Beschreibung",
    noDescription: "Keine Beschreibung vorhanden.",
    dueLabel: "Fällig",
    overdueLabel: "Überfällig",
    high: "Hoch",
    medium: "Mittel",
    normal: "Niedrig",
    recurring: "Wiederkehrend",
    attachments: "Anhänge",
    add: "Hinzufügen",
    noAttachments: "Keine Anhänge",
    comments: "Kommentare",
    addComment: "Kommentar hinzufügen…",
    noCommentsYet: "Noch keine Kommentare.",
    couldntLoadComments: "Kommentare konnten nicht geladen werden.",
    send: "Senden",
    attachFile: "Datei anhängen",
    translateBtn: "Übersetzen",
    showOriginal: "Original anzeigen",
    translating: "Wird übersetzt…",
    noPreview: "Keine Vorschau verfügbar",
  },
  ar_SA: {
    loading: "جارٍ التحميل…",
    empty: "لا توجد مهام لعرضها",
    noneConfigured: "لم يتم تكوين أي مهام بعد.",
    errorToggle: "تعذّر تحديث المهمة. يرجى المحاولة مرة أخرى.",
    toggleTask: "تبديل المهمة",
    markDone: "وضع علامة كمكتملة",
    reopen: "إعادة فتح المهمة",
    description: "الوصف",
    noDescription: "لا يوجد وصف.",
    dueLabel: "الاستحقاق",
    overdueLabel: "متأخرة",
    high: "عالية",
    medium: "متوسطة",
    normal: "منخفضة",
    recurring: "متكررة",
    attachments: "المرفقات",
    add: "إضافة",
    noAttachments: "لا توجد مرفقات",
    comments: "التعليقات",
    addComment: "أضف تعليقًا…",
    noCommentsYet: "لا توجد تعليقات بعد.",
    couldntLoadComments: "تعذّر تحميل التعليقات.",
    send: "إرسال",
    attachFile: "إرفاق ملف",
    translateBtn: "ترجمة",
    showOriginal: "إظهار الأصل",
    translating: "جارٍ الترجمة…",
    noPreview: "لا تتوفر معاينة",
  },
};
