// Pilot i18n bundles for my-tasks-widget.
// en_US is the canonical source (edit by hand). de_DE / ar_SA are the pilot
// translations. Add more locales by adding another keyed bundle; any missing
// key falls back to en_US via makeT().
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    myTasks: "My Tasks",
    // ── Manager view ──────────────────────────────────────────────────
    managerTitle: "Team Tasks",
    teamMember: "Team member",
    allTeamMembers: "All team members",
    noReports: "You have no direct reports.",
    noTeamConfigured: "No team members configured — add user IDs in the widget settings.",
    noTeamData: "No tasks to chart yet.",
    completionRate: "Completion",
    overdueStat: "Overdue",
    openTasks: "Open",
    totalLabel: "total",
    ofNOpen: "of {n} open",
    byPriority: "Open by priority",
    byMember: "By team member",
    priHigh: "High",
    priMed: "Medium",
    priLow: "Low",
    more: "more",
    showAllN: "Show all {n}",
    showFewer: "Show fewer",
    // Filters / sort
    allPriorities: "All priorities",
    overdueOnly: "Overdue only",
    sortDue: "Due date",
    sortPriority: "Priority",
    sortAssignee: "Assignee",
    sortNewest: "Newest",
    // Search + assigned-date-range filters
    searchTasks: "Search tasks",
    assignedLabel: "Assigned",
    assignedFrom: "Assigned from",
    assignedTo: "Assigned to",
    dateToLabel: "to",
    clearDates: "Clear dates",
    // Proof review gallery
    allStores: "All stores",
    allPeople: "All people",
    searchProof: "Search proof",
    noProofMatches: "No proof matches these filters.",
    nPhotos: "{n} photos",
    clearFilters: "Clear filters",
    // Activity feed
    recentActivity: "Recent activity",
    activityLog: "Activity log",
    viewAllActivity: "View full log ({n})",
    actCompleted: "completed",
    actCommented: "commented on",
    withProof: "with proof",
    actCreatedSelf: "created a task for themselves",
    actCreatedFor: "created a task for {who}",
    actCreatedPlain: "created a task",
    actAddedRecurringFor: "added a recurring task for {who}",
    actRecurringInstanceFor: "A recurring task was created for {who}",
    unassignedLabel: "someone",
    cadDaily: "daily",
    cadWeekdays: "on weekdays",
    cadWeeklyEvery: "every {d}",
    cadWeeklyDays: "on {d}",
    cadMonthlyDom: "monthly on the {n}",
    cadMonthly: "monthly",
    noActivity: "No recent activity.",
    notifyAssignedText: "You were assigned a new task: {title}",
    notifyGroupAssignedText: "Your group {group} was assigned a task: {title}",
    assignTo: "Assign to",
    someone: "Someone",
    save: "Save",
    clearAll: "Clear",
    nSelected: "{n} selected",
    noneSelected: "None selected",
    auditResults: "Audit Results",
    newTask: "New task",
    refresh: "Refresh",
    translateBtn: "Translate",
    showOriginal: "Show original",
    translating: "Translating…",
    auditHistory: "Audit History",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    allTypes: "All Types",
    nTypes: "{n} types",
    noTypeLabel: "No Type",
    open: "Open",
    done: "Done",
    both: "Both",
    close: "Close",
    noPreview: "No preview available — use Download",
    groups: "Groups",
    people: "People",
    loading: "Loading…",
    unassign: "Unassign",
    reassign: "Reassign",
    assign: "Assign",
    add: "Add",
    send: "Send",
    noCommentsYet: "No comments yet. Be the first to comment.",
    noAttachments: "No attachments",
    remove: "Remove",
    noAuditsFound: "No audits found",
    selectAudit: "Select an audit above.",
    noFailureTasks: "No failure tasks in this audit.",
    noTasksAssigned: "No tasks assigned to you in this audit.",
    allTasksComplete: "All tasks completed for this audit!",
    nTasksMarkedDone: "{n} tasks marked done",
    nTasksFlagged: "{n} tasks flagged",
    showOtherTasks: "Show {n} other tasks in this audit",
    hideOtherTasks: "Hide {n} other tasks in this audit",
    myTasksN: "My tasks ({n})",
    allCaughtUp: "No open tasks — all caught up!",
    notes: "Notes",
    attachments: "Attachments",
    tasksTab: "Tasks",
    proofTab: "Proof Review",
    proofLabel: "Proof",
    noProofYet: "No photo proof has been submitted yet.",
    onePhoto: "1 photo",
    manyPhotos: "{n} photos",
    categoryBreakdown: "Category breakdown",
    noGroupAssigned: "No group assigned",
    noIndividualAssignee: "No individual assignee",
    group: "Group",
    person: "Person",
    searchPeopleGroups: "Search people or groups…",
    auditFinding: "Audit Finding",
    description: "Description",
    noDescription: "No description",
    comments: "Comments",
    addComment: "Add a comment…",
    attachFile: "Attach file",
    noTaskSpaces: "No task spaces found",
    noTaskSpacesHint: "Make sure at least one Tasks installation exists.",
    failedToLoad: "Failed to load tasks",
    noTasksFound: "No tasks found",
    allCaughtUpPersonal: "No open tasks — you're all caught up!",
    noCompletedTasks: "No completed tasks yet",
    auditEmptyHint: "Submit an audit using the Audit Widget to see results here.",
    noMatches: "No matches",
    createFailedPrefix: "Couldn't create task:",
    newTaskHeading: "New Task",
    title: "Title",
    titlePlaceholder: "What needs to be done?",
    descriptionPlaceholder: "Add details (optional)",
    list: "List",
    type: "Type",
    newTypePlaceholder: "New type name",
    noType: "— No type —",
    createNewType: "+ Create new type…",
    dueDate: "Due date",
    dueLabel: "Due",
    createdLabel: "Created",
    overdueLabel: "Overdue",
    priority: "Priority",
    normal: "Normal",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    recurring: "Recurring",
    cancel: "Cancel",
    createTask: "Create Task",
    creating: "Creating…",
    debug: "Debug",
    copy: "Copy",
    clear: "Clear",
    hide: "Hide",
    copied: "Copied!",
    copyFailed: "Copy failed",
    hideCompleted: "Hide completed",
    showCompletedN: "Show completed ({n})",
    markAsOpen: "Mark as open",
    markAsDone: "Mark as done",
    passing: "Passing",
    failing: "Failing",
    notScored: "Not scored",
  },
  de_DE: {
    myTasks: "Meine Aufgaben",
    auditResults: "Audit-Ergebnisse",
    newTask: "Neue Aufgabe",
    refresh: "Aktualisieren",
    translateBtn: "Übersetzen",
    showOriginal: "Original anzeigen",
    translating: "Wird übersetzt…",
    auditHistory: "Audit-Verlauf",
    scrollLeft: "Nach links scrollen",
    scrollRight: "Nach rechts scrollen",
    allTypes: "Alle Typen",
    nTypes: "{n} Typen",
    noTypeLabel: "Kein Typ",
    open: "Offen",
    done: "Erledigt",
    both: "Beide",
    close: "Schließen",
    noPreview: "Keine Vorschau verfügbar – Download verwenden",
    groups: "Gruppen",
    people: "Personen",
    loading: "Wird geladen…",
    unassign: "Zuweisung aufheben",
    reassign: "Neu zuweisen",
    assign: "Zuweisen",
    add: "Hinzufügen",
    send: "Senden",
    noCommentsYet: "Noch keine Kommentare. Schreiben Sie den ersten Kommentar.",
    noAttachments: "Keine Anhänge",
    remove: "Entfernen",
    noAuditsFound: "Keine Audits gefunden",
    selectAudit: "Wählen Sie oben ein Audit aus.",
    noFailureTasks: "Keine Fehleraufgaben in diesem Audit.",
    noTasksAssigned: "Ihnen sind in diesem Audit keine Aufgaben zugewiesen.",
    allTasksComplete: "Alle Aufgaben für dieses Audit abgeschlossen!",
    nTasksMarkedDone: "{n} Aufgaben als erledigt markiert",
    nTasksFlagged: "{n} Aufgaben markiert",
    showOtherTasks: "{n} weitere Aufgaben in diesem Audit anzeigen",
    hideOtherTasks: "{n} weitere Aufgaben in diesem Audit ausblenden",
    myTasksN: "Meine Aufgaben ({n})",
    allCaughtUp: "Keine offenen Aufgaben – alles erledigt!",
    notes: "Notizen",
    attachments: "Anhänge",
    tasksTab: "Aufgaben",
    proofTab: "Nachweisprüfung",
    proofLabel: "Nachweis",
    noProofYet: "Es wurde noch kein Foto-Nachweis eingereicht.",
    onePhoto: "1 Foto",
    manyPhotos: "{n} Fotos",
    categoryBreakdown: "Kategorienaufschlüsselung",
    noGroupAssigned: "Keine Gruppe zugewiesen",
    noIndividualAssignee: "Keine Einzelperson zugewiesen",
    group: "Gruppe",
    person: "Person",
    searchPeopleGroups: "Personen oder Gruppen suchen…",
    auditFinding: "Audit-Feststellung",
    description: "Beschreibung",
    noDescription: "Keine Beschreibung",
    comments: "Kommentare",
    addComment: "Kommentar hinzufügen…",
    attachFile: "Datei anhängen",
    noTaskSpaces: "Keine Aufgabenbereiche gefunden",
    noTaskSpacesHint: "Stellen Sie sicher, dass mindestens eine Aufgaben-Installation vorhanden ist.",
    failedToLoad: "Aufgaben konnten nicht geladen werden",
    noTasksFound: "Keine Aufgaben gefunden",
    allCaughtUpPersonal: "Keine offenen Aufgaben – alles erledigt!",
    noCompletedTasks: "Noch keine erledigten Aufgaben",
    auditEmptyHint: "Reichen Sie ein Audit über das Audit-Widget ein, um hier Ergebnisse zu sehen.",
    noMatches: "Keine Treffer",
    createFailedPrefix: "Aufgabe konnte nicht erstellt werden:",
    newTaskHeading: "Neue Aufgabe",
    title: "Titel",
    titlePlaceholder: "Was ist zu tun?",
    descriptionPlaceholder: "Details hinzufügen (optional)",
    list: "Liste",
    type: "Typ",
    newTypePlaceholder: "Name des neuen Typs",
    noType: "— Kein Typ —",
    createNewType: "+ Neuen Typ erstellen…",
    dueDate: "Fälligkeitsdatum",
    dueLabel: "Fällig",
    overdueLabel: "Überfällig",
    priority: "Priorität",
    normal: "Normal",
    medium: "Mittel",
    high: "Hoch",
    critical: "Kritisch",
    recurring: "Wiederkehrend",
    cancel: "Abbrechen",
    createTask: "Aufgabe erstellen",
    creating: "Wird erstellt…",
    debug: "Debug",
    copy: "Kopieren",
    clear: "Leeren",
    hide: "Ausblenden",
    copied: "Kopiert!",
    copyFailed: "Kopieren fehlgeschlagen",
    hideCompleted: "Erledigte ausblenden",
    showCompletedN: "Erledigte anzeigen ({n})",
    markAsOpen: "Als offen markieren",
    markAsDone: "Als erledigt markieren",
    passing: "Bestanden",
    failing: "Nicht bestanden",
    notScored: "Nicht bewertet",
  },
  ar_SA: {
    myTasks: "مهامي",
    auditResults: "نتائج التدقيق",
    newTask: "مهمة جديدة",
    refresh: "تحديث",
    translateBtn: "ترجمة",
    showOriginal: "إظهار الأصل",
    translating: "جارٍ الترجمة…",
    auditHistory: "سجل التدقيق",
    scrollLeft: "التمرير لليسار",
    scrollRight: "التمرير لليمين",
    allTypes: "جميع الأنواع",
    nTypes: "{n} أنواع",
    noTypeLabel: "بلا نوع",
    open: "مفتوحة",
    done: "مكتملة",
    both: "كلاهما",
    close: "إغلاق",
    noPreview: "لا تتوفر معاينة — استخدم التنزيل",
    groups: "المجموعات",
    people: "الأشخاص",
    loading: "جارٍ التحميل…",
    unassign: "إلغاء التعيين",
    reassign: "إعادة التعيين",
    assign: "تعيين",
    add: "إضافة",
    send: "إرسال",
    noCommentsYet: "لا توجد تعليقات بعد. كن أول من يعلّق.",
    noAttachments: "لا توجد مرفقات",
    remove: "إزالة",
    noAuditsFound: "لم يتم العثور على عمليات تدقيق",
    selectAudit: "اختر عملية تدقيق من الأعلى.",
    noFailureTasks: "لا توجد مهام إخفاق في هذا التدقيق.",
    noTasksAssigned: "لم تُسنَد إليك أي مهام في هذا التدقيق.",
    allTasksComplete: "تم إكمال جميع المهام لهذا التدقيق!",
    nTasksMarkedDone: "{n} مهام تم وضع علامة الإنجاز عليها",
    nTasksFlagged: "{n} مهام تم تحديدها",
    showOtherTasks: "إظهار {n} مهام أخرى في هذا التدقيق",
    hideOtherTasks: "إخفاء {n} مهام أخرى في هذا التدقيق",
    myTasksN: "مهامي ({n})",
    allCaughtUp: "لا توجد مهام مفتوحة — كل شيء منجز!",
    notes: "ملاحظات",
    attachments: "المرفقات",
    tasksTab: "المهام",
    proofTab: "مراجعة الإثبات",
    proofLabel: "إثبات",
    noProofYet: "لم يتم إرسال أي إثبات بالصور بعد.",
    onePhoto: "صورة واحدة",
    manyPhotos: "{n} صور",
    categoryBreakdown: "تفصيل حسب الفئة",
    noGroupAssigned: "لم يتم تعيين مجموعة",
    noIndividualAssignee: "لم يتم تعيين شخص",
    group: "مجموعة",
    person: "شخص",
    searchPeopleGroups: "ابحث عن أشخاص أو مجموعات…",
    auditFinding: "ملاحظة التدقيق",
    description: "الوصف",
    noDescription: "لا يوجد وصف",
    comments: "التعليقات",
    addComment: "أضف تعليقًا…",
    attachFile: "إرفاق ملف",
    noTaskSpaces: "لم يتم العثور على مساحات مهام",
    noTaskSpacesHint: "تأكد من وجود تثبيت واحد للمهام على الأقل.",
    failedToLoad: "فشل تحميل المهام",
    noTasksFound: "لم يتم العثور على مهام",
    allCaughtUpPersonal: "لا توجد مهام مفتوحة — أنجزت كل شيء!",
    noCompletedTasks: "لا توجد مهام مكتملة بعد",
    auditEmptyHint: "أرسل عملية تدقيق باستخدام أداة التدقيق لرؤية النتائج هنا.",
    noMatches: "لا توجد نتائج",
    createFailedPrefix: "تعذّر إنشاء المهمة:",
    newTaskHeading: "مهمة جديدة",
    title: "العنوان",
    titlePlaceholder: "ما الذي يجب إنجازه؟",
    descriptionPlaceholder: "أضف تفاصيل (اختياري)",
    list: "القائمة",
    type: "النوع",
    newTypePlaceholder: "اسم النوع الجديد",
    noType: "— بلا نوع —",
    createNewType: "+ إنشاء نوع جديد…",
    dueDate: "تاريخ الاستحقاق",
    dueLabel: "الاستحقاق",
    overdueLabel: "متأخرة",
    priority: "الأولوية",
    normal: "عادية",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    recurring: "متكررة",
    cancel: "إلغاء",
    createTask: "إنشاء مهمة",
    creating: "جارٍ الإنشاء…",
    debug: "تصحيح الأخطاء",
    copy: "نسخ",
    clear: "مسح",
    hide: "إخفاء",
    copied: "تم النسخ!",
    copyFailed: "فشل النسخ",
    hideCompleted: "إخفاء المكتملة",
    showCompletedN: "إظهار المكتملة ({n})",
    markAsOpen: "وضع علامة مفتوحة",
    markAsDone: "وضع علامة منجزة",
    passing: "ناجح",
    failing: "غير ناجح",
    notScored: "غير مُقيَّم",
  },
  es_ES: {
    myTasks: "Mis tareas",
    auditResults: "Resultados de la auditoría",
    newTask: "Nueva tarea",
    refresh: "Actualizar",
    translateBtn: "Traducir",
    showOriginal: "Original del programa",
    translating: "Traduciendo...",
    auditHistory: "Historial de auditorías",
    scrollLeft: "Desplego a la izquierda",
    scrollRight: "Desplázate a la derecha",
    allTypes: "Todo Tipo",
    nTypes: "{n} tipos",
    noTypeLabel: "Sin tipo",
    open: "Abierto",
    done: "Hecho",
    both: "Ambos",
    close: "Cierre",
    noPreview: "No hay vista previa disponible — usar Descargar",
    groups: "Grupos",
    people: "Personas",
    loading: "Cargando...",
    unassign: "Desasignación",
    reassign: "Reasignación",
    assign: "Asignar",
    add: "Añadir",
    send: "Envía",
    noCommentsYet: "Aún no hay comentarios. Sé el primero en comentar.",
    noAttachments: "Sin accesorios",
    remove: "Eliminar",
    noAuditsFound: "No se han encontrado auditorías",
    selectAudit: "Selecciona una auditoría arriba.",
    noFailureTasks: "No hay tareas fallidas en esta auditoría.",
    noTasksAssigned: "No se te asignan tareas en esta auditoría.",
    allTasksComplete: "¡Todas las tareas completadas para esta auditoría!",
    nTasksMarkedDone: "{n} tareas marcadas como realizadas",
    nTasksFlagged: "{n} tareas marcadas",
    showOtherTasks: "Mostrar {n} otras tareas en esta auditoría",
    hideOtherTasks: "Ocultar {n} otras tareas en esta auditoría",
    myTasksN: "Mis tareas ({n})",
    allCaughtUp: "¡No hay tareas pendientes — todo puesto al día!",
    notes: "Notas",
    attachments: "Accesorios",
    categoryBreakdown: "Desglose por categorías",
    noGroupAssigned: "No hay grupo asignado",
    noIndividualAssignee: "No hay asignado individual",
    group: "Grupo",
    person: "Persona",
    searchPeopleGroups: "Busca personas o grupos...",
    auditFinding: "Hallazgo de auditoría",
    description: "Descripción",
    noDescription: "Sin descripción",
    comments: "Comentarios",
    addComment: "Añadir un comentario...",
    attachFile: "Adjuntar archivo",
    noTaskSpaces: "No se han encontrado espacios de tareas",
    noTaskSpacesHint: "Asegúrate de que exista al menos una instalación de Tasks.",
    failedToLoad: "No se han cargado tareas",
    noTasksFound: "No se han encontrado tareas",
    allCaughtUpPersonal: "¡No hay tareas pendientes — ya estáis al día!",
    noCompletedTasks: "Aún no he completado ninguna tarea",
    auditEmptyHint: "Envía una auditoría usando el Widget de Auditoría para ver los resultados aquí.",
    noMatches: "Sin partidos",
    createFailedPrefix: "No se pudo crear la tarea:",
    newTaskHeading: "Nueva tarea",
    title: "Título",
    titlePlaceholder: "¿Qué hay que hacer?",
    descriptionPlaceholder: "Añadir detalles (opcional)",
    list: "Lista",
    type: "Tipo",
    newTypePlaceholder: "Nuevo nombre tipo",
    noType: "— No hay tipo —",
    createNewType: "+ Crear un nuevo tipo...",
    dueDate: "Fecha prevista de parto",
    dueLabel: "Debido",
    overdueLabel: "Tarde",
    priority: "Prioridad",
    normal: "Normal",
    medium: "Medio",
    high: "Alto",
    critical: "Crítica",
    recurring: "Recurrentes",
    cancel: "Cancelar",
    createTask: "Crear tarea",
    creating: "Crear...",
    debug: "Depuración",
    copy: "Copiado",
    clear: "¡Libre",
    hide: "Escóndete",
    copied: "¡Copiado!",
    copyFailed: "Copia fallida",
    hideCompleted: "Escondite completado",
    showCompletedN: "Espectáculo finalizado ({n})",
    markAsOpen: "Marca como abierto",
    markAsDone: "Marca como hecho",
    passing: "Fallecimiento",
    failing: "Fracaso",
    notScored: "No puntuado",
  },
  fr_FR: {
    myTasks: "Mes tâches",
    auditResults: "Résultats de l’audit",
    newTask: "Nouvelle tâche",
    refresh: "Rafraîchissement",
    translateBtn: "Traduire",
    showOriginal: "Série originale",
    translating: "Traduction...",
    auditHistory: "Historique de l’audit",
    scrollLeft: "Scroller à gauche",
    scrollRight: "Faites défiler à droite",
    allTypes: "Tous types",
    nTypes: "{n} types",
    noTypeLabel: "Pas de type",
    open: "Ouvre",
    done: "Marché conclu",
    both: "Les deux",
    close: "Fermer",
    noPreview: "Aucun aperçu disponible — utiliser Télécharger",
    groups: "Groupes",
    people: "Personnalités",
    loading: "Chargement...",
    unassign: "Désaffectation",
    reassign: "Réaffectation",
    assign: "Assigner",
    add: "Ajouter",
    send: "Envoyer",
    noCommentsYet: "Pas encore de commentaires. Soyez le premier à commenter.",
    noAttachments: "Pas d’attaches",
    remove: "Retirer",
    noAuditsFound: "Aucun audit n’a été trouvé",
    selectAudit: "Sélectionnez un audit ci-dessus.",
    noFailureTasks: "Aucune défaillance dans cet audit.",
    noTasksAssigned: "Aucune tâche qui vous est assignée dans cet audit.",
    allTasksComplete: "Toutes les tâches accomplies pour cet audit !",
    nTasksMarkedDone: "{n} tâches marquées comme accomplies",
    nTasksFlagged: "{n} tâches signalées",
    showOtherTasks: "Montrez {n} autres tâches dans cet audit",
    hideOtherTasks: "Cacher {n} autres tâches dans cet audit",
    myTasksN: "Mes tâches ({n})",
    allCaughtUp: "Aucune tâche en cours — tout est à jour !",
    notes: "Notes",
    attachments: "Accessoires",
    categoryBreakdown: "Répartition par catégorie",
    noGroupAssigned: "Aucun groupe assigné",
    noIndividualAssignee: "Aucun assigné individuel",
    group: "Groupe",
    person: "Personne",
    searchPeopleGroups: "Fouillez des personnes ou des groupes...",
    auditFinding: "Constatation de l’audit",
    description: "Description",
    noDescription: "Aucune description",
    comments: "Commentaires",
    addComment: "Ajouter un commentaire...",
    attachFile: "Joindre fichier",
    noTaskSpaces: "Aucun espace de tâche trouvé",
    noTaskSpacesHint: "Assurez-vous qu’il existe au moins une installation de Tasks.",
    failedToLoad: "Échec du chargement des tâches",
    noTasksFound: "Aucune tâche trouvée",
    allCaughtUpPersonal: "Pas de tâches en cours — vous êtes à jour !",
    noCompletedTasks: "Aucune tâche terminée pour l’instant",
    auditEmptyHint: "Soumettez un audit en utilisant le widget d’audit pour voir les résultats ici.",
    noMatches: "Pas de matchs",
    createFailedPrefix: "Impossible de créer une tâche :",
    newTaskHeading: "Nouvelle tâche",
    title: "Titre",
    titlePlaceholder: "Que faut-il faire ?",
    descriptionPlaceholder: "Ajouter les détails (optionnel)",
    list: "Liste",
    type: "Type",
    newTypePlaceholder: "Nouveau nom de type",
    noType: "— Pas de type —",
    createNewType: "+ Créer un nouveau type...",
    dueDate: "Date d’accouchement",
    dueLabel: "Due",
    overdueLabel: "En retard",
    priority: "Priorité",
    normal: "Normal",
    medium: "Moyen",
    high: "Haut",
    critical: "Critique",
    recurring: "Récurrents",
    cancel: "Annuler",
    createTask: "Créer une tâche",
    creating: "Créer...",
    debug: "Débogage",
    copy: "Bien reçu",
    clear: "Clair",
    hide: "Cache-toi",
    copied: "Copié !",
    copyFailed: "Copie échouée",
    hideCompleted: "Cachette terminée",
    showCompletedN: "Émission terminée ({n})",
    markAsOpen: "Marquez comme ouvert",
    markAsDone: "Marque comme fait",
    passing: "Passage",
    failing: "Échec",
    notScored: "Non marqué",
  },
  nl_NL: {
    myTasks: "Mijn taken",
    auditResults: "Auditresultaten",
    newTask: "Nieuwe taak",
    refresh: "Verversen",
    translateBtn: "Vertalen",
    showOriginal: "Originele show",
    translating: "Vertalen...",
    auditHistory: "Auditgeschiedenis",
    scrollLeft: "Scroll naar links",
    scrollRight: "Scroll naar rechts",
    allTypes: "Alle typen",
    nTypes: "{n} types",
    noTypeLabel: "Geen Type",
    open: "Open",
    done: "Klaar",
    both: "Beide",
    close: "Sluit",
    noPreview: "Geen preview beschikbaar — gebruik Download",
    groups: "Groepen",
    people: "Mensen",
    loading: "Laden...",
    unassign: "Niet toewijzen",
    reassign: "Herplaatsen",
    assign: "Toewijzen",
    add: "Voeg toe",
    send: "Verzenden",
    noCommentsYet: "Nog geen opmerkingen. Wees de eerste die reageert.",
    noAttachments: "Geen gehechtheden",
    remove: "Verwijder",
    noAuditsFound: "Geen audits gevonden",
    selectAudit: "Selecteer hierboven een audit.",
    noFailureTasks: "Geen fouttaken in deze audit.",
    noTasksAssigned: "Geen taken toegewezen aan u in deze audit.",
    allTasksComplete: "Alle taken voltooid voor deze audit!",
    nTasksMarkedDone: "{n} taken als voltooid gemarkeerd",
    nTasksFlagged: "{n} taken gemarkeerd",
    showOtherTasks: "Toon {n} andere taken in deze audit",
    hideOtherTasks: "Verberg {n} andere taken in deze audit",
    myTasksN: "Mijn taken ({n})",
    allCaughtUp: "Geen open taken — alles is ingehaald!",
    notes: "Noten",
    attachments: "Bijlagen",
    categoryBreakdown: "Categorie-indeling",
    noGroupAssigned: "Geen groep toegewezen",
    noIndividualAssignee: "Geen individuele toegewezen",
    group: "Groep",
    person: "Persoon",
    searchPeopleGroups: "Zoek mensen of groepen...",
    auditFinding: "Auditbevinding",
    description: "Beschrijving",
    noDescription: "Geen beschrijving",
    comments: "Reacties",
    addComment: "Voeg een opmerking toe...",
    attachFile: "Bestand bijvoegen",
    noTaskSpaces: "Geen taakruimtes gevonden",
    noTaskSpacesHint: "Zorg dat er ten minste één Taken-installatie bestaat.",
    failedToLoad: "Taken zijn niet kunnen laden",
    noTasksFound: "Geen taken gevonden",
    allCaughtUpPersonal: "Geen open taken — je bent helemaal bij!",
    noCompletedTasks: "Nog geen voltooide taken",
    auditEmptyHint: "Dien een audit in via de Audit-widget om hier de resultaten te zien.",
    noMatches: "Geen wedstrijden",
    createFailedPrefix: "Taak niet aanmaken:",
    newTaskHeading: "Nieuwe taak",
    title: "Titel",
    titlePlaceholder: "Wat moet er gedaan worden?",
    descriptionPlaceholder: "Details toevoegen (optioneel)",
    list: "Lijst",
    type: "Type",
    newTypePlaceholder: "Nieuwe typenaam",
    noType: "— Geen type —",
    createNewType: "+ Maak een nieuw type...",
    dueDate: "Uitgerekende datum",
    dueLabel: "Te betalen",
    overdueLabel: "Achterstallig",
    priority: "Prioriteit",
    normal: "Normaal",
    medium: "Medium",
    high: "Hoog",
    critical: "Kritisch",
    recurring: "Terugkerend",
    cancel: "Annuleren",
    createTask: "Maak taak aan",
    creating: "Creëren...",
    debug: "Debug",
    copy: "Begrepen",
    clear: "Vrij",
    hide: "Verstop",
    copied: "Gekopieerd!",
    copyFailed: "Kopie mislukt",
    hideCompleted: "Verbergen voltooid",
    showCompletedN: "Show voltooid ({n})",
    markAsOpen: "Markeer als open",
    markAsDone: "Markeer als gedaan",
    passing: "Overlijden",
    failing: "Falen",
    notScored: "Niet gescoord",
  },
  zh_CN: {
    myTasks: "我的任务",
    auditResults: "审计结果",
    newTask: "新任务",
    refresh: "刷新",
    translateBtn: "翻译",
    showOriginal: "节目原版",
    translating: "翻译......",
    auditHistory: "审计历史",
    scrollLeft: "向左滚动",
    scrollRight: "向右滚动",
    allTypes: "所有类型",
    nTypes: "{n}类型",
    noTypeLabel: "无类型",
    open: "开门",
    done: "完成",
    both: "两者兼具",
    close: "结束",
    noPreview: "没有预览——请下载",
    groups: "团体",
    people: "人物",
    loading: "加载中......",
    unassign: "未分配",
    reassign: "重新分配",
    assign: "分配",
    add: "添加",
    send: "发送",
    noCommentsYet: "还没有评论。成为第一个评论的人。",
    noAttachments: "无附件",
    remove: "删除",
    noAuditsFound: "未发现审计",
    selectAudit: "请选择上方的审计。",
    noFailureTasks: "本次审计没有失败任务。",
    noTasksAssigned: "本次审计未分配任何任务。",
    allTasksComplete: "本次审计的所有任务都已完成！",
    nTasksMarkedDone: "{n}任务标记为完成",
    nTasksFlagged: "{n}任务标记",
    showOtherTasks: "本次审计中展示{n}其他任务",
    hideOtherTasks: "在本次审计中隐藏{n}其他任务",
    myTasksN: "我的任务（{n}）",
    allCaughtUp: "没有未完成任务——一切都赶上了！",
    notes: "注释",
    attachments: "附属品",
    categoryBreakdown: "类别分类",
    noGroupAssigned: "没有分配组别",
    noIndividualAssignee: "无个人受派人员",
    group: "集团",
    person: "人物",
    searchPeopleGroups: "搜索人员或群体......",
    auditFinding: "审计发现",
    description: "描述",
    noDescription: "无描述",
    comments: "评论",
    addComment: "添加一条评论......",
    attachFile: "附件文件",
    noTaskSpaces: "未找到任务空间",
    noTaskSpacesHint: "确保至少有一个任务安装。",
    failedToLoad: "任务加载失败",
    noTasksFound: "找不到任务",
    allCaughtUpPersonal: "没有未完成任务——你已经全部赶上了！",
    noCompletedTasks: "还没有完成任务",
    auditEmptyHint: "请使用审计小工具提交审计，查看结果。",
    noMatches: "没有匹配",
    createFailedPrefix: "无法创建任务：",
    newTaskHeading: "新任务",
    title: "标题",
    titlePlaceholder: "需要做什么？",
    descriptionPlaceholder: "添加细节（可选）",
    list: "列表",
    type: "类型",
    newTypePlaceholder: "新型号名称",
    noType: "—— 没有类型 ——",
    createNewType: "+ 创建新类型......",
    dueDate: "预产期",
    dueLabel: "该",
    overdueLabel: "逾期",
    priority: "优先级",
    normal: "普通",
    medium: "媒介",
    high: "高",
    critical: "批判",
    recurring: "常驻角色",
    cancel: "取消",
    createTask: "创建任务",
    creating: "创造......",
    debug: "调试",
    copy: "收到",
    clear: "清场",
    hide: "藏起来",
    copied: "复制了！",
    copyFailed: "复制失败",
    hideCompleted: "藏匿完成",
    showCompletedN: "节目已完结（{n}年）",
    markAsOpen: "标记为开",
    markAsDone: "标记为完成",
    passing: "通过",
    failing: "失败",
    notScored: "未得分",
  },
  ja_JP: {
    myTasks: "私の任務",
    auditResults: "監査結果",
    newTask: "新たな任務",
    refresh: "リフレッシュ",
    translateBtn: "翻訳",
    showOriginal: "番組オリジナル",
    translating: "翻訳中...",
    auditHistory: "監査履歴",
    scrollLeft: "左にスクロール",
    scrollRight: "右にスクロールしてください",
    allTypes: "すべてのタイプ",
    nTypes: "{n}の種類",
    noTypeLabel: "タイプなし",
    open: "開けて",
    done: "終わった",
    both: "両方とも",
    close: "閉じる",
    noPreview: "プレビューは利用できません — ダウンロードをご利用ください",
    groups: "グループ",
    people: "人々",
    loading: "読み込み中...",
    unassign: "割り当て解除",
    reassign: "再配属",
    assign: "割り当て",
    add: "追加",
    send: "送信",
    noCommentsYet: "まだコメントはありません。最初にコメントしてください。",
    noAttachments: "アタッチメントは一切ありません",
    remove: "削除",
    noAuditsFound: "監査は見つかりませんでした",
    selectAudit: "上記で監査を選択してください。",
    noFailureTasks: "この監査では失敗作業は一切ありません。",
    noTasksAssigned: "この監査で割り当てられたタスクはありません。",
    allTasksComplete: "この監査のためにすべての作業を完了させました!",
    nTasksMarkedDone: "{n}タスクは完了済みと表示されています",
    nTasksFlagged: "{n}タスクがフラグされています",
    showOtherTasks: "この監査で{n}他のタスクを表示してください",
    hideOtherTasks: "この監査で他のタスク{n}隠す",
    myTasksN: "私のタスク({n})",
    allCaughtUp: "未解決のタスクはなし — すべて追いついた!",
    notes: "注記",
    attachments: "付属施設",
    categoryBreakdown: "カテゴリー内訳",
    noGroupAssigned: "グループは割り当てられていません",
    noIndividualAssignee: "個人の譲受者はいない",
    group: "グループ",
    person: "人物",
    searchPeopleGroups: "人やグループを検索する...",
    auditFinding: "監査の判断",
    description: "概要",
    noDescription: "特徴なし",
    comments: "コメント",
    addComment: "コメントを追加してください...",
    attachFile: "ファイルを添付してください",
    noTaskSpaces: "タスクスペースは見つかりませんでした",
    noTaskSpacesHint: "少なくとも1つのタスクインストールが存在することを確認してください。",
    failedToLoad: "タスクの読み込み失敗",
    noTasksFound: "タスクは見つかりませんでした",
    allCaughtUpPersonal: "未解決のタスクはなく、すべて追いついた状態です!",
    noCompletedTasks: "まだ完成したタスクはありません",
    auditEmptyHint: "監査ウィジェットを使って監査を提出すると、こちらから結果をご覧ください。",
    noMatches: "一致なし",
    createFailedPrefix: "タスクを作成できなかった:",
    newTaskHeading: "新たな任務",
    title: "タイトル",
    titlePlaceholder: "何をすべきでしょうか?",
    descriptionPlaceholder: "詳細の追加(任意)",
    list: "一覧",
    type: "種類",
    newTypePlaceholder: "新しいタイプ名",
    noType: "— タイプなし —",
    createNewType: "+ 新しいタイプを作成...",
    dueDate: "出産予定日",
    dueLabel: "期限",
    overdueLabel: "遅れてる",
    priority: "優先順位",
    normal: "ノーマル",
    medium: "メディア",
    high: "ハイ",
    critical: "重要な点",
    recurring: "レギュラー出演者",
    cancel: "キャンセル",
    createTask: "タスク作成",
    creating: "創造...",
    debug: "デバッグ",
    copy: "了解",
    clear: "クリア",
    hide: "隠れて",
    copied: "コピーしました!",
    copyFailed: "コピー失敗",
    hideCompleted: "隠れ膑完了",
    showCompletedN: "番組完了({n}年)",
    markAsOpen: "マークを開いたと示す",
    markAsDone: "完了したとマークする",
    passing: "パス",
    failing: "失敗",
    notScored: "スコアは取れていません",
  },
  th_TH: {
    myTasks: "งานของฉัน",
    auditResults: "ผลการตรวจสอบ",
    newTask: "งานใหม่",
    refresh: "รีเฟรช",
    translateBtn: "แปล",
    showOriginal: "แสดงต้นฉบับ",
    translating: "แปล...",
    auditHistory: "ประวัติการตรวจสอบ",
    scrollLeft: "เลื่อนไปทางซ้าย",
    scrollRight: "เลื่อนไปทางขวา",
    allTypes: "ทุกประเภท",
    nTypes: "ประเภท{n}",
    noTypeLabel: "ไม่มีประเภท",
    open: "เปิด",
    done: "เสร็จสิ้น",
    both: "ทั้งสองอย่าง",
    close: "ปิด",
    noPreview: "ไม่มีการแสดงตัวอย่าง — ใช้ดาวน์โหลด",
    groups: "กลุ่ม",
    people: "บุคลากร",
    loading: "กําลังโหลด...",
    unassign: "ยกเลิกการมอบหมาย",
    reassign: "มอบหมายใหม่",
    assign: "มอบหมาย",
    add: "เพิ่ม",
    send: "ส่ง",
    noCommentsYet: "ยังไม่มีความคิดเห็น มาเป็นคนแรกที่แสดงความคิดเห็น",
    noAttachments: "ไม่มีไฟล์แนบ",
    remove: "ลบ",
    noAuditsFound: "ไม่พบการตรวจสอบ",
    selectAudit: "เลือกการตรวจสอบด้านบน",
    noFailureTasks: "ไม่มีงานที่ล้มเหลวในการตรวจสอบนี้",
    noTasksAssigned: "ไม่มีงานที่มอบหมายให้คุณในการตรวจสอบนี้",
    allTasksComplete: "งานทั้งหมดเสร็จสมบูรณ์สําหรับการตรวจสอบนี้!",
    nTasksMarkedDone: "{n}งานที่ทําเครื่องหมายว่าเสร็จสิ้น",
    nTasksFlagged: "{n}งานที่ถูกตั้งค่าสถานะ",
    showOtherTasks: "แสดง{n}งานอื่นๆ ในการตรวจสอบนี้",
    hideOtherTasks: "ซ่อนงาน{n}อื่นๆ ในการตรวจสอบนี้",
    myTasksN: "งานของฉัน ({n})",
    allCaughtUp: "ไม่มีงานที่เปิดอยู่ — ทั้งหมดตามทัน!",
    notes: "หมายเหตุ",
    attachments: "เอกสารแนบ",
    categoryBreakdown: "รายละเอียดหมวดหมู่",
    noGroupAssigned: "ไม่มีการกําหนดกลุ่ม",
    noIndividualAssignee: "ไม่มีผู้รับมอบหมายเป็นรายบุคคล",
    group: "กลุ่มเพื่อน",
    person: "คน",
    searchPeopleGroups: "ค้นหาผู้คนหรือกลุ่ม...",
    auditFinding: "ผลการตรวจสอบ",
    description: "คําอธิบาย",
    noDescription: "ไม่มีคําอธิบาย",
    comments: "ความคิดเห็น",
    addComment: "เพิ่มความคิดเห็น...",
    attachFile: "แนบไฟล์",
    noTaskSpaces: "ไม่พบพื้นที่งาน",
    noTaskSpacesHint: "ตรวจสอบให้แน่ใจว่ามีการติดตั้งงานอย่างน้อยหนึ่งรายการ",
    failedToLoad: "โหลดงานไม่สําเร็จ",
    noTasksFound: "ไม่พบงาน",
    allCaughtUpPersonal: "ไม่มีงานที่เปิดอยู่ — คุณตามทันแล้ว!",
    noCompletedTasks: "ยังไม่มีงานที่เสร็จสมบูรณ์",
    auditEmptyHint: "ส่งการตรวจสอบโดยใช้วิดเจ็ตการตรวจสอบเพื่อดูผลลัพธ์ที่นี่",
    noMatches: "ไม่มีการแข่งขัน",
    createFailedPrefix: "สร้างงานไม่ได้:",
    newTaskHeading: "ภารกิจใหม่",
    title: "ชื่อเรื่อง",
    titlePlaceholder: "ต้องทําอะไรบ้าง?",
    descriptionPlaceholder: "เพิ่มรายละเอียด (ไม่บังคับ)",
    list: "รายการ",
    type: "ชนิดภาพเขียน",
    newTypePlaceholder: "ชื่อประเภทใหม่",
    noType: "— ไม่มีประเภท —",
    createNewType: "+ สร้างประเภทใหม่...",
    dueDate: "วันครบกําหนด",
    dueLabel: "ครบกําหนด",
    overdueLabel: "ค้างชําระ",
    priority: "ลําดับความสําคัญ",
    normal: "ปกติ",
    medium: "ปานกลาง",
    high: "จุดสูง",
    critical: "วิกฤต",
    recurring: "เกิดซ้ํา",
    cancel: "ยกเลิก",
    createTask: "สร้างงาน",
    creating: "กําลังสร้าง...",
    debug: "แก้ไขข้อบกพร่อง",
    copy: "สําเนา",
    clear: "ล้างค่าการค้นหา",
    hide: "ปิด",
    copied: "คัดลอกแล้ว!",
    copyFailed: "คัดลอกล้มเหลว",
    hideCompleted: "ซ่อนเสร็จสมบูรณ์",
    showCompletedN: "แสดงเสร็จสมบูรณ์ ({n})",
    markAsOpen: "ทําเครื่องหมายว่าเปิด",
    markAsDone: "ทําเครื่องหมายว่าเสร็จสิ้น",
    passing: "ผ่าน",
    failing: "ล้มเหลว",
    notScored: "ไม่ได้คะแนน",
  },
  es_MX: {
    myTasks: "Mis tareas",
    auditResults: "Resultados de la auditoría",
    newTask: "Nueva tarea",
    refresh: "Actualizar",
    translateBtn: "Traducir",
    showOriginal: "Original del programa",
    translating: "Traduciendo...",
    auditHistory: "Historial de auditorías",
    scrollLeft: "Desplego a la izquierda",
    scrollRight: "Desplázate a la derecha",
    allTypes: "Todo Tipo",
    nTypes: "{n} tipos",
    noTypeLabel: "Sin tipo",
    open: "Abierto",
    done: "Hecho",
    both: "Ambos",
    close: "Cierre",
    noPreview: "No hay vista previa disponible — usar Descargar",
    groups: "Grupos",
    people: "Personas",
    loading: "Cargando...",
    unassign: "Desasignación",
    reassign: "Reasignación",
    assign: "Asignar",
    add: "Añadir",
    send: "Envía",
    noCommentsYet: "Aún no hay comentarios. Sé el primero en comentar.",
    noAttachments: "Sin accesorios",
    remove: "Eliminar",
    noAuditsFound: "No se han encontrado auditorías",
    selectAudit: "Selecciona una auditoría arriba.",
    noFailureTasks: "No hay tareas fallidas en esta auditoría.",
    noTasksAssigned: "No se te asignan tareas en esta auditoría.",
    allTasksComplete: "¡Todas las tareas completadas para esta auditoría!",
    nTasksMarkedDone: "{n} tareas marcadas como realizadas",
    nTasksFlagged: "{n} tareas marcadas",
    showOtherTasks: "Mostrar {n} otras tareas en esta auditoría",
    hideOtherTasks: "Ocultar {n} otras tareas en esta auditoría",
    myTasksN: "Mis tareas ({n})",
    allCaughtUp: "¡No hay tareas pendientes — todo puesto al día!",
    notes: "Notas",
    attachments: "Accesorios",
    categoryBreakdown: "Desglose por categorías",
    noGroupAssigned: "No hay grupo asignado",
    noIndividualAssignee: "No hay asignado individual",
    group: "Grupo",
    person: "Persona",
    searchPeopleGroups: "Busca personas o grupos...",
    auditFinding: "Hallazgo de auditoría",
    description: "Descripción",
    noDescription: "Sin descripción",
    comments: "Comentarios",
    addComment: "Añadir un comentario...",
    attachFile: "Adjuntar archivo",
    noTaskSpaces: "No se han encontrado espacios de tareas",
    noTaskSpacesHint: "Asegúrate de que exista al menos una instalación de Tasks.",
    failedToLoad: "No se han cargado tareas",
    noTasksFound: "No se han encontrado tareas",
    allCaughtUpPersonal: "¡No hay tareas pendientes — ya estáis al día!",
    noCompletedTasks: "Aún no he completado ninguna tarea",
    auditEmptyHint: "Envía una auditoría usando el Widget de Auditoría para ver los resultados aquí.",
    noMatches: "Sin partidos",
    createFailedPrefix: "No se pudo crear la tarea:",
    newTaskHeading: "Nueva tarea",
    title: "Título",
    titlePlaceholder: "¿Qué hay que hacer?",
    descriptionPlaceholder: "Añadir detalles (opcional)",
    list: "Lista",
    type: "Tipo",
    newTypePlaceholder: "Nuevo nombre tipo",
    noType: "— No hay tipo —",
    createNewType: "+ Crear un nuevo tipo...",
    dueDate: "Fecha prevista de parto",
    dueLabel: "Debido",
    overdueLabel: "Tarde",
    priority: "Prioridad",
    normal: "Normal",
    medium: "Medio",
    high: "Alto",
    critical: "Crítica",
    recurring: "Recurrentes",
    cancel: "Cancelar",
    createTask: "Crear tarea",
    creating: "Crear...",
    debug: "Depuración",
    copy: "Copiado",
    clear: "¡Libre",
    hide: "Escóndete",
    copied: "¡Copiado!",
    copyFailed: "Copia fallida",
    hideCompleted: "Escondite completado",
    showCompletedN: "Espectáculo finalizado ({n})",
    markAsOpen: "Marca como abierto",
    markAsDone: "Marca como hecho",
    passing: "Fallecimiento",
    failing: "Fracaso",
    notScored: "No puntuado",
  },
  vi_VN: {
    myTasks: "Nhiệm vụ của tôi",
    auditResults: "Kết quả kiểm toán",
    newTask: "Nhiệm vụ mới",
    refresh: "Làm mới",
    translateBtn: "Dịch",
    showOriginal: "Xem bản gốc",
    translating: "Đang dịch...",
    auditHistory: "Lịch sử kiểm toán",
    scrollLeft: "Cuộn sang trái",
    scrollRight: "Cuộn sang phải",
    allTypes: "Tất cả các loại",
    nTypes: "Các loại {n}",
    noTypeLabel: "Không có loại",
    open: "Mở",
    done: "Xong",
    both: "Cả hai",
    close: "Đóng",
    noPreview: "Không có bản xem trước - sử dụng Tải xuống",
    groups: "Nhóm",
    people: "Con người",
    loading: "Đang tải...",
    unassign: "Hủy chỉ định",
    reassign: "Chỉ định lại",
    assign: "Chỉ định",
    add: "Thêm",
    send: "Gửi",
    noCommentsYet: "Chưa có bình luận nào. Hãy là người đầu tiên bình luận.",
    noAttachments: "Không có tệp đính kèm",
    remove: "Loại bỏ",
    noAuditsFound: "Không tìm thấy kiểm toán",
    selectAudit: "Chọn một cuộc kiểm tra ở trên.",
    noFailureTasks: "Không có nhiệm vụ thất bại trong cuộc kiểm toán này.",
    noTasksAssigned: "Không có nhiệm vụ nào được giao cho bạn trong cuộc kiểm tra này.",
    allTasksComplete: "Tất cả các nhiệm vụ đã hoàn thành cho cuộc kiểm toán này!",
    nTasksMarkedDone: "{n} nhiệm vụ được đánh dấu là đã hoàn thành",
    nTasksFlagged: "{n} nhiệm vụ được gắn cờ",
    showOtherTasks: "Hiển thị {n} nhiệm vụ khác trong cuộc kiểm tra này",
    hideOtherTasks: "Ẩn {n} nhiệm vụ khác trong kiểm tra này",
    myTasksN: "Nhiệm vụ của tôi ({n})",
    allCaughtUp: "Không có nhiệm vụ mở - tất cả đều bắt kịp!",
    notes: "Ghi chú",
    attachments: "Tệp đính kèm",
    categoryBreakdown: "Phân tích danh mục",
    noGroupAssigned: "Không có nhóm nào được chỉ định",
    noIndividualAssignee: "Không có người được chuyển nhượng cá nhân",
    group: "Nhóm",
    person: "Người",
    searchPeopleGroups: "Tìm kiếm mọi người hoặc nhóm...",
    auditFinding: "Kết quả kiểm toán",
    description: "Sự miêu tả",
    noDescription: "Không có mô tả",
    comments: "Bình luận",
    addComment: "Thêm bình luận...",
    attachFile: "Đính kèm tệp",
    noTaskSpaces: "Không tìm thấy không gian nhiệm vụ",
    noTaskSpacesHint: "Đảm bảo có ít nhất một cài đặt Tác vụ.",
    failedToLoad: "Không tải được tác vụ",
    noTasksFound: "Không tìm thấy nhiệm vụ nào",
    allCaughtUpPersonal: "Không có nhiệm vụ mở - tất cả các bạn đều bị bắt kịp!",
    noCompletedTasks: "Chưa có nhiệm vụ nào đã hoàn thành",
    auditEmptyHint: "Gửi đánh giá bằng Tiện ích kiểm tra để xem kết quả tại đây.",
    noMatches: "Không trùng khớp",
    createFailedPrefix: "Không thể tạo tác vụ:",
    newTaskHeading: "Nhiệm vụ mới",
    title: "Tiêu đề",
    titlePlaceholder: "Cần phải làm gì?",
    descriptionPlaceholder: "Thêm chi tiết (tùy chọn)",
    list: "Danh sách",
    type: "Kiểu",
    newTypePlaceholder: "Tên kiểu mới",
    noType: "- Không có loại -",
    createNewType: "+ Tạo kiểu mới...",
    dueDate: "Ngày đến hạn",
    dueLabel: "Đến hạn",
    overdueLabel: "Quá hạn",
    priority: "Ưu tiên",
    normal: "Bình thường",
    medium: "Trung bình",
    high: "Cao",
    critical: "Quan trọng",
    recurring: "Định kỳ",
    cancel: "Hủy bỏ",
    createTask: "Tạo nhiệm vụ",
    creating: "Đang tạo...",
    debug: "Gỡ lỗi",
    copy: "Sao chép",
    clear: "Xóa",
    hide: "Ẩn giấu",
    copied: "Đã sao chép!",
    copyFailed: "Sao chép không thành công",
    hideCompleted: "Ẩn đã hoàn thành",
    showCompletedN: "Hiển thị đã hoàn thành ({n})",
    markAsOpen: "Đánh dấu là mở",
    markAsDone: "Đánh dấu là xong",
    passing: "Vượt qua",
    failing: "Không thành công",
    notScored: "Không được ghi bàn",
  },
  ko_KR: {
    myTasks: "나의 임무",
    auditResults: "감사 결과",
    newTask: "새로운 임무",
    refresh: "새로고침",
    translateBtn: "번역해",
    showOriginal: "쇼 오리지널",
    translating: "번역 중...",
    auditHistory: "감사 이력",
    scrollLeft: "왼쪽으로 스크롤",
    scrollRight: "오른쪽으로 스크롤하세요",
    allTypes: "모든 유형",
    nTypes: "{n} 종류",
    noTypeLabel: "타입 없음",
    open: "오픈",
    done: "끝났어",
    both: "둘 다",
    close: "닫습니다",
    noPreview: "미리보기는 제공되지 않습니다 — 다운로드 사용",
    groups: "그룹",
    people: "인물",
    loading: "로딩 중...",
    unassign: "언배정",
    reassign: "재배치",
    assign: "할당",
    add: "추가",
    send: "보내세요",
    noCommentsYet: "아직 댓글은 없습니다. 가장 먼저 댓글을 달아보세요.",
    noAttachments: "부착물 없어",
    remove: "제거",
    noAuditsFound: "감사 기록은 발견되지 않았습니다",
    selectAudit: "위에서 감사를 선택하세요.",
    noFailureTasks: "이번 감사에는 실패 과제가 없습니다.",
    noTasksAssigned: "이번 감사에서는 당신에게 할당된 업무가 없습니다.",
    allTasksComplete: "이번 감사를 위한 모든 업무가 완료되었습니다!",
    nTasksMarkedDone: "{n} 완료 표시 작업",
    nTasksFlagged: "{n} 작업 플래그됨",
    showOtherTasks: "이 감사에서 {n} 다른 업무를 보여줘",
    hideOtherTasks: "이 감사에서 다른 {n} 작업을 숨기세요",
    myTasksN: "나의 과제 ({n})",
    allCaughtUp: "미해결 과제는 없고 — 모두 완료했습니다!",
    notes: "주석",
    attachments: "부속 자료",
    categoryBreakdown: "카테고리 분류",
    noGroupAssigned: "그룹 배정 없음",
    noIndividualAssignee: "개별 파견자는 없습니다",
    group: "그룹",
    person: "인물",
    searchPeopleGroups: "사람이나 집단을 검색해보세요...",
    auditFinding: "감사 조사 결과",
    description: "설명",
    noDescription: "묘사는 없어",
    comments: "댓글",
    addComment: "댓글을 추가하세요...",
    attachFile: "파일 첨부",
    noTaskSpaces: "작업 공간이 없음",
    noTaskSpacesHint: "최소한 하나의 Tasks 설치가 존재하는지 확인하세요.",
    failedToLoad: "작업 불러오지 않음",
    noTasksFound: "과제가 없음",
    allCaughtUpPersonal: "미해결 과제는 없어요 — 모두 끝났으니까요!",
    noCompletedTasks: "아직 완료된 작업은 없습니다",
    auditEmptyHint: "감사 위젯을 통해 감사를 제출하여 결과를 확인할 수 있습니다.",
    noMatches: "일치하는 사람이 없어",
    createFailedPrefix: "작업을 만들 수 없었다:",
    newTaskHeading: "새로운 임무",
    title: "제목",
    titlePlaceholder: "무엇을 해야 할까요?",
    descriptionPlaceholder: "세부 정보 추가(선택 사항)",
    list: "목록",
    type: "유형",
    newTypePlaceholder: "새로운 유형명입니다",
    noType: "— 종류 없음 —",
    createNewType: "+ 새로운 타입 생성...",
    dueDate: "출산 예정일",
    dueLabel: "기분",
    overdueLabel: "기한이 지났어",
    priority: "우선순위",
    normal: "정상",
    medium: "매체",
    high: "높게",
    critical: "비평",
    recurring: "반복 출연",
    cancel: "취소",
    createTask: "작업 만들기",
    creating: "창조...",
    debug: "디버그",
    copy: "알겠습니다",
    clear: "비켜",
    hide: "숨어",
    copied: "복사했어요!",
    copyFailed: "복사 실패",
    hideCompleted: "숨기기 완료",
    showCompletedN: "쇼 완결 ({n})",
    markAsOpen: "표시 열려 있음",
    markAsDone: "완료된 것으로 표시하세요",
    passing: "통과",
    failing: "실패",
    notScored: "점수 부여되지 않았습니다",
  },
  tl_PH: {
    myTasks: "Ang Aking Mga Gawain",
    auditResults: "Mga Resulta ng Pag-audit",
    newTask: "Bagong gawain",
    refresh: "I-refresh",
    translateBtn: "Magsalin",
    showOriginal: "Ipakita ang orihinal",
    translating: "Pagsasalin ...",
    auditHistory: "Kasaysayan ng Audit",
    scrollLeft: "Mag-scroll pakaliwa",
    scrollRight: "Mag-scroll pakanan",
    allTypes: "Lahat ng Uri",
    nTypes: "{n} uri",
    noTypeLabel: "Walang Uri",
    open: "Buksan",
    done: "Tapos na",
    both: "Parehong",
    close: "Isara",
    noPreview: "Walang preview na magagamit — gamitin ang I-download",
    groups: "Mga Grupo",
    people: "Mga Tao",
    loading: "Naglo-load...",
    unassign: "I-unassign",
    reassign: "Muling Pagtatalaga",
    assign: "Email Address *",
    add: "Magdagdag",
    send: "Email Address *",
    noCommentsYet: "Walang mga komento pa. Maging ang unang magkomento.",
    noAttachments: "Walang mga attachment",
    remove: "Alisin",
    noAuditsFound: "Walang natagpuang mga audit",
    selectAudit: "Pumili ng isang audit sa itaas.",
    noFailureTasks: "Walang mga gawain sa pagkabigo sa audit na ito.",
    noTasksAssigned: "Walang mga gawain na itinalaga sa iyo sa pag-audit na ito.",
    allTasksComplete: "Lahat ng gawain ay nakumpleto para sa audit na ito!",
    nTasksMarkedDone: "{n} mga gawain na minarkahan na tapos na",
    nTasksFlagged: "{n} mga gawain na na-flag",
    showOtherTasks: "Ipakita {n} iba pang mga gawain sa audit na ito",
    hideOtherTasks: "Itago {n} iba pang mga gawain sa audit na ito",
    myTasksN: "Ang Aking Mga Gawain ({n})",
    allCaughtUp: "Walang bukas na gawain - lahat ay naabutan!",
    notes: "Mga Tala",
    attachments: "Mga Attachment",
    categoryBreakdown: "Pagkasira ng kategorya",
    noGroupAssigned: "Walang pangkat na itinalaga",
    noIndividualAssignee: "Walang indibidwal na tagapag-atas",
    group: "Pangkat",
    person: "Tao",
    searchPeopleGroups: "Hanapin ang mga tao o pangkat ...",
    auditFinding: "Paghahanap ng Audit",
    description: "Paglalarawan",
    noDescription: "Walang paglalarawan",
    comments: "Mga Komento",
    addComment: "Magdagdag ng komento ...",
    attachFile: "Email Address *",
    noTaskSpaces: "Walang natagpuan na mga puwang ng gawain",
    noTaskSpacesHint: "Tiyaking umiiral ang hindi bababa sa isang pag-install ng Mga Gawain.",
    failedToLoad: "Nabigong mag-load ng mga gawain",
    noTasksFound: "Walang natagpuang mga gawain",
    allCaughtUpPersonal: "Walang bukas na gawain - lahat kayo ay nahuli!",
    noCompletedTasks: "Wala pang nakumpletong gawain",
    auditEmptyHint: "Magsumite ng audit gamit ang Audit Widget para makita ang mga resulta dito.",
    noMatches: "Walang mga tugma",
    createFailedPrefix: "Hindi ko magawa ang gawain:",
    newTaskHeading: "Bagong Gawain",
    title: "Pamagat",
    titlePlaceholder: "Ano ang kailangang gawin?",
    descriptionPlaceholder: "Magdagdag ng mga detalye (opsyonal)",
    list: "Listahan",
    type: "Uri",
    newTypePlaceholder: "Bagong uri ng pangalan",
    noType: "— Walang uri —",
    createNewType: "+ Lumikha ng bagong uri ...",
    dueDate: "Takdang petsa",
    dueLabel: "Dahil",
    overdueLabel: "Huli na",
    priority: "Prayoridad",
    normal: "Normal",
    medium: "Katamtaman",
    high: "Mataas",
    critical: "Kritikal",
    recurring: "Paulit-ulit",
    cancel: "Kanselahin",
    createTask: "Lumikha ng Gawain",
    creating: "Paglikha ...",
    debug: "I-debug",
    copy: "Kopyahin",
    clear: "I-clear",
    hide: "Itago",
    copied: "Kinopya!",
    copyFailed: "Nabigo ang kopya",
    hideCompleted: "Kumpleto na ang Itago",
    showCompletedN: "Kumpleto ang Ipakita ({n})",
    markAsOpen: "Markahan bilang bukas",
    markAsDone: "Markahan bilang tapos na",
    passing: "Pagpasa",
    failing: "Pagkabigo",
    notScored: "Hindi nakapuntos",
  },
  pt_BR: {
    myTasks: "Minhas Tarefas",
    auditResults: "Resultados da Auditoria",
    newTask: "Nova tarefa",
    refresh: "Atualizar",
    translateBtn: "Traduzir",
    showOriginal: "Original do programa",
    translating: "Traduzindo...",
    auditHistory: "Histórico de Auditoria",
    scrollLeft: "Rola à esquerda",
    scrollRight: "Rola para a direita",
    allTypes: "Todos os Tipos",
    nTypes: "{n} Tipos",
    noTypeLabel: "Sem Tipo",
    open: "Aberto",
    done: "Feito",
    both: "Ambos",
    close: "Fechar",
    noPreview: "Sem prévia disponível — use Download",
    groups: "Grupos",
    people: "Pessoas",
    loading: "Carregando...",
    unassign: "Desatribuição",
    reassign: "Reatribuição",
    assign: "Atribuir",
    add: "Adicionar",
    send: "Enviar",
    noCommentsYet: "Ainda sem comentários. Seja o primeiro a comentar.",
    noAttachments: "Sem anexos",
    remove: "Remover",
    noAuditsFound: "Nenhuma auditoria foi encontrada",
    selectAudit: "Selecione uma auditoria acima.",
    noFailureTasks: "Nenhuma falha nessa auditoria.",
    noTasksAssigned: "Nenhuma tarefa atribuída a você nesta auditoria.",
    allTasksComplete: "Todas as tarefas concluídas para esta auditoria!",
    nTasksMarkedDone: "{n} tarefas marcadas como concluídas",
    nTasksFlagged: "{n} tarefas sinalizadas",
    showOtherTasks: "Mostre {n} outras tarefas nesta auditoria",
    hideOtherTasks: "Esconda {n} outras tarefas nesta auditoria",
    myTasksN: "Minhas tarefas ({n})",
    allCaughtUp: "Nenhuma tarefa em aberto — tudo estava em dia!",
    notes: "Notas",
    attachments: "Anexos",
    categoryBreakdown: "Divisão por categorias",
    noGroupAssigned: "Nenhum grupo designado",
    noIndividualAssignee: "Sem um cedente individual",
    group: "Grupo",
    person: "Pessoa",
    searchPeopleGroups: "Procurem pessoas ou grupos...",
    auditFinding: "Constatação da Auditoria",
    description: "Descrição",
    noDescription: "Sem descrição",
    comments: "Comentários",
    addComment: "Adicione um comentário...",
    attachFile: "Anexar arquivo",
    noTaskSpaces: "Nenhum espaço de tarefas encontrado",
    noTaskSpacesHint: "Certifique-se de que existe pelo menos uma instalação de Tarefas.",
    failedToLoad: "Falharam ao carregar tarefas",
    noTasksFound: "Nenhuma tarefa encontrada",
    allCaughtUpPersonal: "Sem tarefas em aberto — você está em dia!",
    noCompletedTasks: "Ainda nenhuma tarefa concluída",
    auditEmptyHint: "Submeta uma auditoria usando o Widget de Auditoria para ver os resultados aqui.",
    noMatches: "Sem matches",
    createFailedPrefix: "Não consegui criar tarefa:",
    newTaskHeading: "Nova Tarefa",
    title: "Título",
    titlePlaceholder: "O que precisa ser feito?",
    descriptionPlaceholder: "Adicionar detalhes (opcional)",
    list: "Lista",
    type: "Tipo",
    newTypePlaceholder: "Novo nome de tipo",
    noType: "— Sem tipo —",
    createNewType: "+ Criar novo tipo...",
    dueDate: "Data prevista para o parto",
    dueLabel: "Devido",
    overdueLabel: "Atrasado",
    priority: "Prioridade",
    normal: "Normal",
    medium: "Médio",
    high: "Alto",
    critical: "Crítica",
    recurring: "Recorrentes",
    cancel: "Cancelar",
    createTask: "Criar Tarefa",
    creating: "Criando...",
    debug: "Depuração",
    copy: "Cópia",
    clear: "Limpo",
    hide: "Esconder",
    copied: "Copiado!",
    copyFailed: "Cópia falhou",
    hideCompleted: "Esconderijo concluído",
    showCompletedN: "Exposição concluída ({n})",
    markAsOpen: "Marque como aberto",
    markAsDone: "Marque como feito",
    passing: "Passagem",
    failing: "Fracasso",
    notScored: "Não pontuado",
  },
  ht_HT: {
    myTasks: "Travay mwen yo",
    auditResults: "Rezilta Kontwòl Odit",
    newTask: "Nouvo travay",
    refresh: "Rafrechi",
    translateBtn: "Tradwi",
    showOriginal: "Montre orijinal la",
    translating: "Tradui...",
    auditHistory: "Istwa odit",
    scrollLeft: "Scroll bò gòch",
    scrollRight: "Scroll dwat",
    allTypes: "Tout kalite",
    nTypes: "{n} kalite",
    noTypeLabel: "Pa gen kalite",
    open: "ouvè",
    done: "Fè",
    both: "Tou de",
    close: "Fèmen",
    noPreview: "Pa gen preview disponib — itilize Download",
    groups: "Gwoup yo",
    people: "Moun",
    loading: "Chaje ...",
    unassign: "Unattribut",
    reassign: "Reasiyen",
    assign: "Asiyen",
    add: "Ajoute",
    send: "Voye",
    noCommentsYet: "Pa gen kòmantè ankò. Fè premye moun ki fè kòmantè.",
    noAttachments: "Pa gen atachman",
    remove: "Retire",
    noAuditsFound: "Pa jwenn odit",
    selectAudit: "Chwazi yon odit pi wo a.",
    noFailureTasks: "Pa gen okenn travay echèk nan odit sa a.",
    noTasksAssigned: "Pa gen travay ki asiyen ou nan odit sa a.",
    allTasksComplete: "Tout travay ki te fini pou odit sa a!",
    nTasksMarkedDone: "{n} travay make fè",
    nTasksFlagged: "{n} travay ki make",
    showOtherTasks: "Montre {n} lòt travay nan odit sa a",
    hideOtherTasks: "Kache {n} lòt travay nan odit sa a",
    myTasksN: "Travay mwen ({n})",
    allCaughtUp: "Pa gen travay ouvè - tout kenbe moute!",
    notes: "Nòt yo",
    attachments: "Atachman",
    categoryBreakdown: "Kategori pann",
    noGroupAssigned: "Pa gen gwoup asiyen",
    noIndividualAssignee: "Pa gen moun asiyen endividyèl",
    group: "Gwoup",
    person: "Moun",
    searchPeopleGroups: "Rechèch moun oswa gwoup...",
    auditFinding: "Odit Jwenn",
    description: "Deskripsyon",
    noDescription: "Pa gen deskripsyon",
    comments: "Kòmantè",
    addComment: "Ajoute yon kòmantè...",
    attachFile: "Tache dosye",
    noTaskSpaces: "Pa gen espas travay yo te jwenn",
    noTaskSpacesHint: "Asire w ke omwen yon enstalasyon Travay egziste.",
    failedToLoad: "Echwe pou pou chaje travay yo",
    noTasksFound: "Pa gen travay yo te jwenn",
    allCaughtUpPersonal: "Pa gen travay ouvè - ou tout kenbe moute!",
    noCompletedTasks: "Pa gen travay fini ankò",
    auditEmptyHint: "Soumèt yon odit lè l sèvi avèk Widget Odit la pou wè rezilta isit la.",
    noMatches: "Pa gen alimèt",
    createFailedPrefix: "Pa t &#39;kapab kreye travay:",
    newTaskHeading: "Nouvo Travay",
    title: "",
    titlePlaceholder: "Kisa ki dwe fè?",
    descriptionPlaceholder: "Ajoute detay (si ou vle)",
    list: "Lis",
    type: "Kalite",
    newTypePlaceholder: "Nouvo non kalite",
    noType: "— Pa gen kalite —",
    createNewType: "+ Kreye nouvo kalite...",
    dueDate: "Dat limit yo",
    dueLabel: "Akòz",
    overdueLabel: "Anreta",
    priority: "Priyorite",
    normal: "Nòmal",
    medium: "Mwayen",
    high: "Segondè",
    critical: "Kritik",
    recurring: "Renouvlab",
    cancel: "Anile",
    createTask: "Kreye Travay",
    creating: "Kreye...",
    debug: "Debogaj",
    copy: "Kopi",
    clear: "Klè",
    hide: "Kache",
    copied: "Kopye!",
    copyFailed: "Kopi echwe",
    hideCompleted: "Kache ranpli",
    showCompletedN: "Montre fini ({n})",
    markAsOpen: "Make kòm louvri",
    markAsDone: "Make kòm fè",
    passing: "Pase",
    failing: "Echwe",
    notScored: "Pa bay nòt",
  },
};
