// Renders the Lucide icons into icons.generated.ts as plain SVG strings, so the
// browser bundle carries markup instead of ~90 KiB of React. Runs before build.

const fs = require("fs");
const path = require("path");
const { createElement } = require("react");
const { renderToStaticMarkup } = require("react-dom/server");
const Lu = require("react-icons/lu");

// One family only: Lucide, via react-icons/lu.
// Names an editor can use in the widget's `icon` field.
const NAMED = {
  users: "LuUsers",
  building: "LuBuilding2",
  briefcase: "LuBriefcase",
  store: "LuStore",
  warehouse: "LuWarehouse",
  factory: "LuFactory",
  truck: "LuTruck",
  car: "LuCar",
  ship: "LuShip",
  plane: "LuPlane",
  tractor: "LuTractor",
  package: "LuPackage",
  cart: "LuShoppingCart",
  hospital: "LuStethoscope",
  health: "LuHeartPulse",
  pharmacy: "LuPill",
  lab: "LuFlaskConical",
  school: "LuGraduationCap",
  book: "LuBookOpen",
  bank: "LuBanknote",
  government: "LuLandmark",
  legal: "LuScale",
  tech: "LuCpu",
  laptop: "LuLaptop",
  telecom: "LuWifi",
  energy: "LuZap",
  fuel: "LuFuel",
  construction: "LuHardHat",
  tools: "LuWrench",
  hammer: "LuHammer",
  safety: "LuShieldCheck",
  hotel: "LuHotel",
  restaurant: "LuUtensilsCrossed",
  support: "LuHeadset",
  marketing: "LuMegaphone",
  design: "LuPalette",
  environment: "LuLeaf",
  global: "LuGlobe",
};

// Glyphs used by the widget's chrome. Not selectable in the config.
const UI = {
  check: "LuCheck",
  arrow: "LuArrowRight",
  alert: "LuTriangleAlert",
  info: "LuInfo",
  spinner: "LuLoaderCircle",
};

function render(exportName) {
  const Icon = Lu[exportName];
  if (!Icon) throw new Error(`react-icons/lu has no export named ${exportName}`);
  return renderToStaticMarkup(
    createElement(Icon, { "aria-hidden": "true", focusable: "false" })
  );
}

function entries(map) {
  return Object.keys(map)
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(render(map[key]))},`)
    .join("\n");
}

const output = `// Generated by scripts/generate-icons.js — do not edit by hand.
// Run \`npm run icons\` after changing the icon set in that script.
//
// Every glyph here is Lucide, rendered from react-icons/lu at build time so the
// browser bundle carries the markup instead of the React renderer.

/** Icon names selectable in the widget's \`icon\` config field. */
export const NAMED_ICONS: { readonly [name: string]: string } = {
${entries(NAMED)}
};

/** Glyphs used by the widget's own chrome. */
export const UI_ICONS = {
${entries(UI)}
} as const;
`;

const target = path.join(__dirname, "..", "icons.generated.ts");
fs.writeFileSync(target, output, "utf8");
console.log(
  `Wrote ${path.relative(process.cwd(), target)} — ` +
    `${Object.keys(NAMED).length} named icons, ${Object.keys(UI).length} UI icons.`
);
