// Pilot i18n bundles for recurring-tasks-widget. en_US canonical; de_DE / ar_SA
// pilot translations; missing keys fall back to en_US via makeT().
//
// NOTE: priority levels and the recurrence-rule summary text are task DATA
// (content), not chrome — they are intentionally NOT translated here.
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    recurringTasks: "Recurring Tasks",
    list: "List",
    calendar: "Calendar",
    newBtn: "New",
    taskDetails: "Task Details",
    title: "Title",
    titlePlaceholder: "What needs to be done?",
    description: "Description",
    descriptionPlaceholder: "Add details (optional)",
    type: "Type",
    noType: "— No type —",
    createNewType: "+ Create new type…",
    newTypePlaceholder: "New type name",
    priority: "Priority",
    normal: "Normal",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    recurrence: "Recurrence",
    repeats: "Repeats",
    every: "Every",
    days: "day(s)",
    weeks: "week(s)",
    months: "month(s)",
    onDay: "On day",
    onThe: "On the",
    last: "last",
    timeOfDay: "Time of day",
    dueDaysAfter: "Due (days after)",
    startDate: "Start date",
    endDate: "End date",
    optional: "(optional)",
    recurrenceHelp: "Created at the chosen time (within ~15 min). Starts today by default.",
    targetStores: "Target {stores}",
    findStores: "Find {stores}",
    loadingStores: "Loading {stores}…",
    searchStores: "Search {stores}…",
    loading: "Loading…",
    listHelp: 'Tasks land in a "Recurring Tasks" list in each {store}.',
    assignTo: "Assign To",
    searchUsersGroups: "Search users and groups…",
    users: "Users",
    groups: "Groups",
    cancel: "Cancel",
    createSchedule: "Create Schedule",
    saveChanges: "Save Changes",
    errorLoading: "Error loading",
    failedToLoad: "Failed to load",
    selectStore: "Select a {store}…",
    noStoresFound: "No {stores} found",
    failedLoadStores: "Failed to load {stores}",
    noSchedulesYet: "No recurring schedules yet.",
    clickNewToCreate: "Click <b>New</b> to create one.",
    month: "Month",
    today: "Today",
    pickWeekday: "Pick at least one weekday.",
    startNotPast: "Start date can't be in the past.",
    endAfterStart: "End date must be on or after the start date.",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    nextRun: "Next run",
    activeRange: "Active range",
    due: "Due",
    assignedTo: "Assigned to",
    anyoneWithAccess: "Anyone with access to the list",
    threeDay: "3 Day",
    daysAfterCreation: "{n} days after creation",
    tomorrow: "Tomorrow",
    nextPrefix: "Next:",
    rangeStarts: "Starts {date} · no end date",
    tasksWillBeCreated: "Tasks will be created — {summary}",
    scheduleSavedMsg: "Schedule saved to {n} {store}. Tasks will be created automatically — {summary}.",
    everyDay: "Every day",
    everyNDays: "Every {n} days",
    weekly: "Weekly",
    everyNWeeks: "Every {n} weeks",
    everyWeekday: "Every weekday",
    monthly: "Monthly",
    everyNMonths: "Every {n} months",
    ruleOnDays: "{every} on {days}",
    ruleOnDom: "{every} on day {dom}",
    ruleOnNth: "{every} on the {ord} {day}",
    ruleAtTime: "{base} at {time} {tz}",
    ord1: "1st", ord2: "2nd", ord3: "3rd", ord4: "4th", ordLast: "last",
    sfEveryDay: "every day",
    sfEveryNDays: "every {n} days",
    sfEveryWeekday: "every weekday",
    sfEveryWeekend: "every weekend",
    sfDaysWeekly: "{days} every week",
    sfDaysEveryNWeek: "{days} every {ord} week",
    sfEveryDom: "every {ord}",
    sfEveryNDom: "every {int} {ord}",
    sfEveryNth: "every {nth} {day}",
    sfEveryNMoNth: "every {int} mo · {nth} {day}",
  },
  de_DE: {
    recurringTasks: "Wiederkehrende Aufgaben",
    list: "Liste",
    calendar: "Kalender",
    newBtn: "Neu",
    taskDetails: "Aufgabendetails",
    title: "Titel",
    titlePlaceholder: "Was ist zu tun?",
    description: "Beschreibung",
    descriptionPlaceholder: "Details hinzufügen (optional)",
    type: "Typ",
    noType: "— Kein Typ —",
    createNewType: "+ Neuen Typ erstellen…",
    newTypePlaceholder: "Name des neuen Typs",
    priority: "Priorität",
    normal: "Normal",
    medium: "Mittel",
    high: "Hoch",
    critical: "Kritisch",
    recurrence: "Wiederholung",
    repeats: "Wiederholt sich",
    every: "Alle",
    days: "Tag(e)",
    weeks: "Woche(n)",
    months: "Monat(e)",
    onDay: "Am Tag",
    onThe: "Am",
    last: "letzten",
    timeOfDay: "Uhrzeit",
    dueDaysAfter: "Fällig (Tage danach)",
    startDate: "Startdatum",
    endDate: "Enddatum",
    optional: "(optional)",
    recurrenceHelp: "Wird zur gewählten Zeit erstellt (innerhalb von ~15 Min.). Beginnt standardmäßig heute.",
    targetStores: "Ziel-{stores}",
    findStores: "{stores} finden",
    loadingStores: "{stores} werden geladen…",
    searchStores: "{stores} suchen…",
    loading: "Wird geladen…",
    listHelp: 'Aufgaben landen in einer Liste „Wiederkehrende Aufgaben" in jeder {store}.',
    assignTo: "Zuweisen an",
    searchUsersGroups: "Benutzer und Gruppen suchen…",
    users: "Benutzer",
    groups: "Gruppen",
    cancel: "Abbrechen",
    createSchedule: "Zeitplan erstellen",
    saveChanges: "Änderungen speichern",
    errorLoading: "Fehler beim Laden",
    failedToLoad: "Laden fehlgeschlagen",
    selectStore: "{store} auswählen…",
    noStoresFound: "Keine {stores} gefunden",
    failedLoadStores: "{stores} konnten nicht geladen werden",
    noSchedulesYet: "Noch keine wiederkehrenden Zeitpläne.",
    clickNewToCreate: "Klicken Sie auf <b>Neu</b>, um einen zu erstellen.",
    month: "Monat",
    today: "Heute",
    pickWeekday: "Wählen Sie mindestens einen Wochentag.",
    startNotPast: "Das Startdatum darf nicht in der Vergangenheit liegen.",
    endAfterStart: "Das Enddatum muss am oder nach dem Startdatum liegen.",
    close: "Schließen",
    delete: "Löschen",
    edit: "Bearbeiten",
    nextRun: "Nächste Ausführung",
    activeRange: "Aktiver Zeitraum",
    due: "Fällig",
    assignedTo: "Zugewiesen an",
    anyoneWithAccess: "Jeder mit Zugriff auf die Liste",
    threeDay: "3 Tage",
    daysAfterCreation: "{n} Tage nach Erstellung",
    tomorrow: "Morgen",
    nextPrefix: "Nächste:",
    rangeStarts: "Beginnt am {date} · kein Enddatum",
    tasksWillBeCreated: "Aufgaben werden erstellt — {summary}",
    scheduleSavedMsg: "Zeitplan für {n} {store} gespeichert. Aufgaben werden automatisch erstellt — {summary}.",
    everyDay: "Jeden Tag",
    everyNDays: "Alle {n} Tage",
    weekly: "Wöchentlich",
    everyNWeeks: "Alle {n} Wochen",
    everyWeekday: "Jeden Wochentag",
    monthly: "Monatlich",
    everyNMonths: "Alle {n} Monate",
    ruleOnDays: "{every} am {days}",
    ruleOnDom: "{every} am {dom}. Tag",
    ruleOnNth: "{every} am {ord} {day}",
    ruleAtTime: "{base} um {time} {tz}",
    ord1: "1.", ord2: "2.", ord3: "3.", ord4: "4.", ordLast: "letzten",
    sfEveryDay: "jeden Tag",
    sfEveryNDays: "alle {n} Tage",
    sfEveryWeekday: "jeden Wochentag",
    sfEveryWeekend: "jedes Wochenende",
    sfDaysWeekly: "{days} jede Woche",
    sfDaysEveryNWeek: "{days} jede {ord} Woche",
    sfEveryDom: "jeden {ord}",
    sfEveryNDom: "alle {int} {ord}",
    sfEveryNth: "jeden {nth} {day}",
    sfEveryNMoNth: "alle {int} Mon · {nth} {day}",
  },
  ar_SA: {
    recurringTasks: "المهام المتكررة",
    list: "قائمة",
    calendar: "تقويم",
    newBtn: "جديد",
    taskDetails: "تفاصيل المهمة",
    title: "العنوان",
    titlePlaceholder: "ما الذي يجب إنجازه؟",
    description: "الوصف",
    descriptionPlaceholder: "أضف تفاصيل (اختياري)",
    type: "النوع",
    noType: "— بلا نوع —",
    createNewType: "+ إنشاء نوع جديد…",
    newTypePlaceholder: "اسم النوع الجديد",
    priority: "الأولوية",
    normal: "عادية",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    recurrence: "التكرار",
    repeats: "يتكرر",
    every: "كل",
    days: "يوم/أيام",
    weeks: "أسبوع/أسابيع",
    months: "شهر/أشهر",
    onDay: "في يوم",
    onThe: "في",
    last: "الأخير",
    timeOfDay: "وقت اليوم",
    dueDaysAfter: "الاستحقاق (بعد أيام)",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    optional: "(اختياري)",
    recurrenceHelp: "تُنشأ في الوقت المحدد (خلال ~15 دقيقة). تبدأ اليوم افتراضيًا.",
    targetStores: "{stores} المستهدفة",
    findStores: "ابحث عن {stores}",
    loadingStores: "جارٍ تحميل {stores}…",
    searchStores: "ابحث في {stores}…",
    loading: "جارٍ التحميل…",
    listHelp: 'تظهر المهام في قائمة «المهام المتكررة» في كل {store}.',
    assignTo: "إسناد إلى",
    searchUsersGroups: "ابحث عن مستخدمين ومجموعات…",
    users: "المستخدمون",
    groups: "المجموعات",
    cancel: "إلغاء",
    createSchedule: "إنشاء جدول",
    saveChanges: "حفظ التغييرات",
    errorLoading: "خطأ في التحميل",
    failedToLoad: "فشل التحميل",
    selectStore: "اختر {store}…",
    noStoresFound: "لم يتم العثور على {stores}",
    failedLoadStores: "فشل تحميل {stores}",
    noSchedulesYet: "لا توجد جداول متكررة بعد.",
    clickNewToCreate: "انقر على <b>جديد</b> لإنشاء واحد.",
    month: "شهر",
    today: "اليوم",
    pickWeekday: "اختر يوم أسبوع واحدًا على الأقل.",
    startNotPast: "لا يمكن أن يكون تاريخ البدء في الماضي.",
    endAfterStart: "يجب أن يكون تاريخ الانتهاء في تاريخ البدء أو بعده.",
    close: "إغلاق",
    delete: "حذف",
    edit: "تعديل",
    nextRun: "التشغيل التالي",
    activeRange: "النطاق النشط",
    due: "الاستحقاق",
    assignedTo: "مُسنَدة إلى",
    anyoneWithAccess: "أي شخص لديه حق الوصول إلى القائمة",
    threeDay: "3 أيام",
    daysAfterCreation: "{n} يوم بعد الإنشاء",
    tomorrow: "غدًا",
    nextPrefix: "التالي:",
    rangeStarts: "يبدأ في {date} · بلا تاريخ انتهاء",
    tasksWillBeCreated: "ستُنشأ المهام — {summary}",
    scheduleSavedMsg: "تم حفظ الجدول لـ {n} {store}. ستُنشأ المهام تلقائيًا — {summary}.",
    everyDay: "كل يوم",
    everyNDays: "كل {n} أيام",
    weekly: "أسبوعيًا",
    everyNWeeks: "كل {n} أسابيع",
    everyWeekday: "كل يوم عمل",
    monthly: "شهريًا",
    everyNMonths: "كل {n} أشهر",
    ruleOnDays: "{every} يوم {days}",
    ruleOnDom: "{every} في اليوم {dom}",
    ruleOnNth: "{every} في {ord} {day}",
    ruleAtTime: "{base} الساعة {time} {tz}",
    ord1: "الأول", ord2: "الثاني", ord3: "الثالث", ord4: "الرابع", ordLast: "الأخير",
    sfEveryDay: "كل يوم",
    sfEveryNDays: "كل {n} أيام",
    sfEveryWeekday: "كل يوم عمل",
    sfEveryWeekend: "كل عطلة أسبوع",
    sfDaysWeekly: "{days} كل أسبوع",
    sfDaysEveryNWeek: "{days} كل {ord} أسبوع",
    sfEveryDom: "كل {ord}",
    sfEveryNDom: "كل {int} {ord}",
    sfEveryNth: "كل {nth} {day}",
    sfEveryNMoNth: "كل {int} شهر · {nth} {day}",
  },
};
