// Pilot i18n bundles for recurring-tasks-widget. en_US canonical; de_DE / ar_SA
// pilot translations; missing keys fall back to en_US via makeT().
//
// NOTE: priority levels and the recurrence-rule summary text are task DATA
// (content), not chrome — they are intentionally NOT translated here.
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    recurringTasks: "Recurring Tasks",
    list: "List",
    calendar: "Calendar",
    newBtn: "New",
    taskDetails: "Task Details",
    title: "Title",
    titlePlaceholder: "What needs to be done?",
    description: "Description",
    descriptionPlaceholder: "Add details (optional)",
    type: "Type",
    noType: "— No type —",
    createNewType: "+ Create new type…",
    newTypePlaceholder: "New type name",
    priority: "Priority",
    normal: "Normal",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    recurrence: "Recurrence",
    repeats: "Repeats",
    every: "Every",
    days: "day(s)",
    weeks: "week(s)",
    months: "month(s)",
    onDay: "On day",
    onThe: "On the",
    last: "last",
    timeOfDay: "Time of day",
    dueDaysAfter: "Due (days after)",
    startDate: "Start date",
    endDate: "End date",
    optional: "(optional)",
    recurrenceHelp: "Created at the chosen time (within ~15 min). Starts today by default.",
    targetStores: "Target {stores}",
    findStores: "Find {stores}",
    loadingStores: "Loading {stores}…",
    searchStores: "Search {stores}…",
    loading: "Loading…",
    listHelp: 'Tasks land in a "Recurring Tasks" list in each {store}.',
    assignTo: "Assign To",
    searchUsersGroups: "Search users and groups…",
    users: "Users",
    groups: "Groups",
    cancel: "Cancel",
    createSchedule: "Create Schedule",
    saveChanges: "Save Changes",
    errorLoading: "Error loading",
    failedToLoad: "Failed to load",
    selectStore: "Select a {store}…",
    noStoresFound: "No {stores} found",
    failedLoadStores: "Failed to load {stores}",
    noSchedulesYet: "No recurring schedules yet.",
    clickNewToCreate: "Click <b>New</b> to create one.",
    month: "Month",
    today: "Today",
    pickWeekday: "Pick at least one weekday.",
    startNotPast: "Start date can't be in the past.",
    endAfterStart: "End date must be on or after the start date.",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    nextRun: "Next run",
    activeRange: "Active range",
    due: "Due",
    assignedTo: "Assigned to",
    anyoneWithAccess: "Anyone with access to the list",
    threeDay: "3 Day",
    daysAfterCreation: "{n} days after creation",
    tomorrow: "Tomorrow",
    nextPrefix: "Next:",
    rangeStarts: "Starts {date} · no end date",
    tasksWillBeCreated: "Tasks will be created — {summary}",
    scheduleSavedMsg: "Schedule saved to {n} {store}. Tasks will be created automatically — {summary}.",
    everyDay: "Every day",
    everyNDays: "Every {n} days",
    weekly: "Weekly",
    everyNWeeks: "Every {n} weeks",
    everyWeekday: "Every weekday",
    monthly: "Monthly",
    everyNMonths: "Every {n} months",
    ruleOnDays: "{every} on {days}",
    ruleOnDom: "{every} on day {dom}",
    ruleOnNth: "{every} on the {ord} {day}",
    ruleAtTime: "{base} at {time} {tz}",
    ord1: "1st", ord2: "2nd", ord3: "3rd", ord4: "4th", ordLast: "last",
    sfEveryDay: "every day",
    sfEveryNDays: "every {n} days",
    sfEveryWeekday: "every weekday",
    sfEveryWeekend: "every weekend",
    sfDaysWeekly: "{days} every week",
    sfDaysEveryNWeek: "{days} every {ord} week",
    sfEveryDom: "every {ord}",
    sfEveryNDom: "every {int} {ord}",
    sfEveryNth: "every {nth} {day}",
    sfEveryNMoNth: "every {int} mo · {nth} {day}",
  },
  de_DE: {
    recurringTasks: "Wiederkehrende Aufgaben",
    list: "Liste",
    calendar: "Kalender",
    newBtn: "Neu",
    taskDetails: "Aufgabendetails",
    title: "Titel",
    titlePlaceholder: "Was ist zu tun?",
    description: "Beschreibung",
    descriptionPlaceholder: "Details hinzufügen (optional)",
    type: "Typ",
    noType: "— Kein Typ —",
    createNewType: "+ Neuen Typ erstellen…",
    newTypePlaceholder: "Name des neuen Typs",
    priority: "Priorität",
    normal: "Normal",
    medium: "Mittel",
    high: "Hoch",
    critical: "Kritisch",
    recurrence: "Wiederholung",
    repeats: "Wiederholt sich",
    every: "Alle",
    days: "Tag(e)",
    weeks: "Woche(n)",
    months: "Monat(e)",
    onDay: "Am Tag",
    onThe: "Am",
    last: "letzten",
    timeOfDay: "Uhrzeit",
    dueDaysAfter: "Fällig (Tage danach)",
    startDate: "Startdatum",
    endDate: "Enddatum",
    optional: "(optional)",
    recurrenceHelp: "Wird zur gewählten Zeit erstellt (innerhalb von ~15 Min.). Beginnt standardmäßig heute.",
    targetStores: "Ziel-{stores}",
    findStores: "{stores} finden",
    loadingStores: "{stores} werden geladen…",
    searchStores: "{stores} suchen…",
    loading: "Wird geladen…",
    listHelp: 'Aufgaben landen in einer Liste „Wiederkehrende Aufgaben" in jeder {store}.',
    assignTo: "Zuweisen an",
    searchUsersGroups: "Benutzer und Gruppen suchen…",
    users: "Benutzer",
    groups: "Gruppen",
    cancel: "Abbrechen",
    createSchedule: "Zeitplan erstellen",
    saveChanges: "Änderungen speichern",
    errorLoading: "Fehler beim Laden",
    failedToLoad: "Laden fehlgeschlagen",
    selectStore: "{store} auswählen…",
    noStoresFound: "Keine {stores} gefunden",
    failedLoadStores: "{stores} konnten nicht geladen werden",
    noSchedulesYet: "Noch keine wiederkehrenden Zeitpläne.",
    clickNewToCreate: "Klicken Sie auf <b>Neu</b>, um einen zu erstellen.",
    month: "Monat",
    today: "Heute",
    pickWeekday: "Wählen Sie mindestens einen Wochentag.",
    startNotPast: "Das Startdatum darf nicht in der Vergangenheit liegen.",
    endAfterStart: "Das Enddatum muss am oder nach dem Startdatum liegen.",
    close: "Schließen",
    delete: "Löschen",
    edit: "Bearbeiten",
    nextRun: "Nächste Ausführung",
    activeRange: "Aktiver Zeitraum",
    due: "Fällig",
    assignedTo: "Zugewiesen an",
    anyoneWithAccess: "Jeder mit Zugriff auf die Liste",
    threeDay: "3 Tage",
    daysAfterCreation: "{n} Tage nach Erstellung",
    tomorrow: "Morgen",
    nextPrefix: "Nächste:",
    rangeStarts: "Beginnt am {date} · kein Enddatum",
    tasksWillBeCreated: "Aufgaben werden erstellt — {summary}",
    scheduleSavedMsg: "Zeitplan für {n} {store} gespeichert. Aufgaben werden automatisch erstellt — {summary}.",
    everyDay: "Jeden Tag",
    everyNDays: "Alle {n} Tage",
    weekly: "Wöchentlich",
    everyNWeeks: "Alle {n} Wochen",
    everyWeekday: "Jeden Wochentag",
    monthly: "Monatlich",
    everyNMonths: "Alle {n} Monate",
    ruleOnDays: "{every} am {days}",
    ruleOnDom: "{every} am {dom}. Tag",
    ruleOnNth: "{every} am {ord} {day}",
    ruleAtTime: "{base} um {time} {tz}",
    ord1: "1.", ord2: "2.", ord3: "3.", ord4: "4.", ordLast: "letzten",
    sfEveryDay: "jeden Tag",
    sfEveryNDays: "alle {n} Tage",
    sfEveryWeekday: "jeden Wochentag",
    sfEveryWeekend: "jedes Wochenende",
    sfDaysWeekly: "{days} jede Woche",
    sfDaysEveryNWeek: "{days} jede {ord} Woche",
    sfEveryDom: "jeden {ord}",
    sfEveryNDom: "alle {int} {ord}",
    sfEveryNth: "jeden {nth} {day}",
    sfEveryNMoNth: "alle {int} Mon · {nth} {day}",
  },
  ar_SA: {
    recurringTasks: "المهام المتكررة",
    list: "قائمة",
    calendar: "تقويم",
    newBtn: "جديد",
    taskDetails: "تفاصيل المهمة",
    title: "العنوان",
    titlePlaceholder: "ما الذي يجب إنجازه؟",
    description: "الوصف",
    descriptionPlaceholder: "أضف تفاصيل (اختياري)",
    type: "النوع",
    noType: "— بلا نوع —",
    createNewType: "+ إنشاء نوع جديد…",
    newTypePlaceholder: "اسم النوع الجديد",
    priority: "الأولوية",
    normal: "عادية",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    recurrence: "التكرار",
    repeats: "يتكرر",
    every: "كل",
    days: "يوم/أيام",
    weeks: "أسبوع/أسابيع",
    months: "شهر/أشهر",
    onDay: "في يوم",
    onThe: "في",
    last: "الأخير",
    timeOfDay: "وقت اليوم",
    dueDaysAfter: "الاستحقاق (بعد أيام)",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    optional: "(اختياري)",
    recurrenceHelp: "تُنشأ في الوقت المحدد (خلال ~15 دقيقة). تبدأ اليوم افتراضيًا.",
    targetStores: "{stores} المستهدفة",
    findStores: "ابحث عن {stores}",
    loadingStores: "جارٍ تحميل {stores}…",
    searchStores: "ابحث في {stores}…",
    loading: "جارٍ التحميل…",
    listHelp: 'تظهر المهام في قائمة «المهام المتكررة» في كل {store}.',
    assignTo: "إسناد إلى",
    searchUsersGroups: "ابحث عن مستخدمين ومجموعات…",
    users: "المستخدمون",
    groups: "المجموعات",
    cancel: "إلغاء",
    createSchedule: "إنشاء جدول",
    saveChanges: "حفظ التغييرات",
    errorLoading: "خطأ في التحميل",
    failedToLoad: "فشل التحميل",
    selectStore: "اختر {store}…",
    noStoresFound: "لم يتم العثور على {stores}",
    failedLoadStores: "فشل تحميل {stores}",
    noSchedulesYet: "لا توجد جداول متكررة بعد.",
    clickNewToCreate: "انقر على <b>جديد</b> لإنشاء واحد.",
    month: "شهر",
    today: "اليوم",
    pickWeekday: "اختر يوم أسبوع واحدًا على الأقل.",
    startNotPast: "لا يمكن أن يكون تاريخ البدء في الماضي.",
    endAfterStart: "يجب أن يكون تاريخ الانتهاء في تاريخ البدء أو بعده.",
    close: "إغلاق",
    delete: "حذف",
    edit: "تعديل",
    nextRun: "التشغيل التالي",
    activeRange: "النطاق النشط",
    due: "الاستحقاق",
    assignedTo: "مُسنَدة إلى",
    anyoneWithAccess: "أي شخص لديه حق الوصول إلى القائمة",
    threeDay: "3 أيام",
    daysAfterCreation: "{n} يوم بعد الإنشاء",
    tomorrow: "غدًا",
    nextPrefix: "التالي:",
    rangeStarts: "يبدأ في {date} · بلا تاريخ انتهاء",
    tasksWillBeCreated: "ستُنشأ المهام — {summary}",
    scheduleSavedMsg: "تم حفظ الجدول لـ {n} {store}. ستُنشأ المهام تلقائيًا — {summary}.",
    everyDay: "كل يوم",
    everyNDays: "كل {n} أيام",
    weekly: "أسبوعيًا",
    everyNWeeks: "كل {n} أسابيع",
    everyWeekday: "كل يوم عمل",
    monthly: "شهريًا",
    everyNMonths: "كل {n} أشهر",
    ruleOnDays: "{every} يوم {days}",
    ruleOnDom: "{every} في اليوم {dom}",
    ruleOnNth: "{every} في {ord} {day}",
    ruleAtTime: "{base} الساعة {time} {tz}",
    ord1: "الأول", ord2: "الثاني", ord3: "الثالث", ord4: "الرابع", ordLast: "الأخير",
    sfEveryDay: "كل يوم",
    sfEveryNDays: "كل {n} أيام",
    sfEveryWeekday: "كل يوم عمل",
    sfEveryWeekend: "كل عطلة أسبوع",
    sfDaysWeekly: "{days} كل أسبوع",
    sfDaysEveryNWeek: "{days} كل {ord} أسبوع",
    sfEveryDom: "كل {ord}",
    sfEveryNDom: "كل {int} {ord}",
    sfEveryNth: "كل {nth} {day}",
    sfEveryNMoNth: "كل {int} شهر · {nth} {day}",
  },
  es_ES: {
    recurringTasks: "Tareas recurrentes",
    list: "Lista",
    calendar: "Calendario",
    newBtn: "Nuevo",
    taskDetails: "Detalles de la tarea",
    title: "Título",
    titlePlaceholder: "¿Qué hay que hacer?",
    description: "Descripción",
    descriptionPlaceholder: "Añadir detalles (opcional)",
    type: "Tipo",
    noType: "— No hay tipo —",
    createNewType: "+ Crear un nuevo tipo...",
    newTypePlaceholder: "Nuevo nombre tipo",
    priority: "Prioridad",
    normal: "Normal",
    medium: "Medio",
    high: "Alto",
    critical: "Crítica",
    recurrence: "Recurrencia",
    repeats: "Repeticiones",
    every: "Cada",
    days: "Día(s)",
    weeks: "Semana(s)",
    months: "Mes o meses",
    onDay: "En el día",
    onThe: "En el",
    last: "Última",
    timeOfDay: "Hora del día",
    dueDaysAfter: "Fecha límite (días después)",
    startDate: "Fecha de inicio",
    endDate: "Fecha de finalización",
    optional: "(opcional)",
    recurrenceHelp: "Creado en el momento elegido (en ~15 minutos). Empieza hoy por defecto.",
    targetStores: "Objetivo {stores}",
    findStores: "Encuentra {stores}",
    loadingStores: "Cargando {stores}...",
    searchStores: "Registrar {stores}...",
    loading: "Cargando...",
    listHelp: "Las tareas aparecen en una lista de &#34;Tareas recurrentes&#34; en cada {store}.",
    assignTo: "Asignar a",
    searchUsersGroups: "Buscar usuarios y grupos...",
    users: "Usuarios",
    groups: "Grupos",
    cancel: "Cancelar",
    createSchedule: "Crear Horario",
    saveChanges: "Guardar cambios",
    errorLoading: "Carga de errores",
    failedToLoad: "No se ha cargado",
    selectStore: "Elige un {store}...",
    noStoresFound: "No se encontró {stores}",
    failedLoadStores: "No se ha podido cargar {stores}",
    noSchedulesYet: "Todavía no hay calendarios recurrentes.",
    clickNewToCreate: "Haz <b>clic en Nuevo</b> para crear uno.",
    month: "Mes",
    today: "Hoy",
    pickWeekday: "Elige al menos un día laborable.",
    startNotPast: "La fecha de inicio no puede ser del pasado.",
    endAfterStart: "La fecha de finalización debe ser en o después de la fecha de inicio.",
    close: "Cierre",
    delete: "Borrar",
    edit: "Edición",
    nextRun: "Próxima carrera",
    activeRange: "Rango activo",
    due: "Debido",
    assignedTo: "Asignado a",
    anyoneWithAccess: "¿Alguien con acceso a la lista",
    threeDay: "3 días",
    daysAfterCreation: "{n} días después de la creación",
    tomorrow: "Mañana",
    nextPrefix: "Siguiente:",
    rangeStarts: "Empieza {date} · Sin fecha de finalización",
    tasksWillBeCreated: "Se crearán tareas — {summary}",
    scheduleSavedMsg: "Horario guardado en {n} {store}. Las tareas se crearán automáticamente — {summary}.",
    everyDay: "Cada día",
    everyNDays: "Cada {n} días",
    weekly: "Semanal",
    everyNWeeks: "Cada {n} semanas",
    everyWeekday: "Todos los días laborables",
    monthly: "Mensual",
    everyNMonths: "Cada {n} meses",
    ruleOnDays: "{every} en {days}",
    ruleOnDom: "{every} el día {dom}",
    ruleOnNth: "{every} en el {ord} {day}",
    ruleAtTime: "{base} a {time} {tz}",
    ord1: "1º",
    ord2: "2º",
    ord3: "3º",
    ord4: "4º",
    ordLast: "Última",
    sfEveryDay: "todos los días",
    sfEveryNDays: "cada {n} días",
    sfEveryWeekday: "todos los días laborables",
    sfEveryWeekend: "todos los fines de semana",
    sfDaysWeekly: "{days} cada semana",
    sfDaysEveryNWeek: "{days} cada {ord} semana",
    sfEveryDom: "Cada {ord}",
    sfEveryNDom: "cada {int} {ord}",
    sfEveryNth: "cada {nth} {day}",
    sfEveryNMoNth: "cada {int} mes · {nth} {day}",
  },
  fr_FR: {
    recurringTasks: "Tâches récurrentes",
    list: "Liste",
    calendar: "Calendrier",
    newBtn: "Nouveau",
    taskDetails: "Détails de la tâche",
    title: "Titre",
    titlePlaceholder: "Que faut-il faire ?",
    description: "Description",
    descriptionPlaceholder: "Ajouter les détails (optionnel)",
    type: "Type",
    noType: "— Pas de type —",
    createNewType: "+ Créer un nouveau type...",
    newTypePlaceholder: "Nouveau nom de type",
    priority: "Priorité",
    normal: "Normal",
    medium: "Moyen",
    high: "Haut",
    critical: "Critique",
    recurrence: "Récidive",
    repeats: "Reprises",
    every: "Tous",
    days: "Jour(s)",
    weeks: "Semaine(s)",
    months: "Mois(s)",
    onDay: "On Day",
    onThe: "Sur le",
    last: "Dernier",
    timeOfDay: "Heure de la journée",
    dueDaysAfter: "Délai (jours après)",
    startDate: "Date de début",
    endDate: "Date de fin",
    optional: "(optionnel)",
    recurrenceHelp: "Créé à l’heure choisie (dans ~15 minutes). Ça commence aujourd’hui par défaut.",
    targetStores: "Cible {stores}",
    findStores: "Trouver {stores}",
    loadingStores: "Chargement {stores}...",
    searchStores: "Fouillez {stores}...",
    loading: "Chargement...",
    listHelp: "Les tâches figurent dans une liste « Tâches récurrentes » dans chaque {store}.",
    assignTo: "Assigner à",
    searchUsersGroups: "Rechercher utilisateurs et groupes...",
    users: "Utilisateurs",
    groups: "Groupes",
    cancel: "Annuler",
    createSchedule: "Créer un planning",
    saveChanges: "Modifications de sauvegarde",
    errorLoading: "Chargement d’erreur",
    failedToLoad: "Échec de chargement",
    selectStore: "Sélectionnez un {store}...",
    noStoresFound: "Aucune {stores} trouvée",
    failedLoadStores: "Échec de charger {stores}",
    noSchedulesYet: "Pas encore de plannings récurrents.",
    clickNewToCreate: "Cliquez <b>sur Nouveau</b> pour en créer un.",
    month: "Mois",
    today: "Aujourd’hui",
    pickWeekday: "Choisissez au moins un jour de la semaine.",
    startNotPast: "La date de début ne peut pas être passée.",
    endAfterStart: "La date de fin doit être la même fois que la date de début ou après.",
    close: "Fermer",
    delete: "Supprimer",
    edit: "Édit",
    nextRun: "Prochaine course",
    activeRange: "Portée active",
    due: "Due",
    assignedTo: "Affecté à",
    anyoneWithAccess: "Quelqu’un ayant accès à la liste",
    threeDay: "3 jours",
    daysAfterCreation: "{n} jours après la création",
    tomorrow: "Demain",
    nextPrefix: "À suivre :",
    rangeStarts: "Commence {date} · Pas de date de fin",
    tasksWillBeCreated: "Des tâches seront créées — {summary}",
    scheduleSavedMsg: "Planning enregistré à {n} {store}. Les tâches seront créées automatiquement — {summary}.",
    everyDay: "Tous les jours",
    everyNDays: "Tous les {n} jours",
    weekly: "Hebdomadaire",
    everyNWeeks: "Toutes les {n} semaines",
    everyWeekday: "Tous les jours de la semaine",
    monthly: "Mensuelle",
    everyNMonths: "Tous les {n} mois",
    ruleOnDays: "{every} sur {days}",
    ruleOnDom: "{every} le jour {dom}",
    ruleOnNth: "{every} sur le {ord} {day}",
    ruleAtTime: "{base} à {time} {tz}",
    ord1: "1er",
    ord2: "2e",
    ord3: "3e",
    ord4: "4e",
    ordLast: "Dernier",
    sfEveryDay: "tous les jours",
    sfEveryNDays: "tous les {n} jours",
    sfEveryWeekday: "chaque jour de la semaine",
    sfEveryWeekend: "Tous les week-ends",
    sfDaysWeekly: "{days} chaque semaine",
    sfDaysEveryNWeek: "{days} toutes les {ord} semaines",
    sfEveryDom: "Chaque {ord}",
    sfEveryNDom: "Chaque {int} {ord}",
    sfEveryNth: "Chaque {nth} {day}",
    sfEveryNMoNth: "tous les {int} mois · {nth} {day}",
  },
  nl_NL: {
    recurringTasks: "Terugkerende taken",
    list: "Lijst",
    calendar: "Kalender",
    newBtn: "Nieuw",
    taskDetails: "Taakdetails",
    title: "Titel",
    titlePlaceholder: "Wat moet er gedaan worden?",
    description: "Beschrijving",
    descriptionPlaceholder: "Details toevoegen (optioneel)",
    type: "Type",
    noType: "— Geen type —",
    createNewType: "+ Maak een nieuw type...",
    newTypePlaceholder: "Nieuwe typenaam",
    priority: "Prioriteit",
    normal: "Normaal",
    medium: "Medium",
    high: "Hoog",
    critical: "Kritisch",
    recurrence: "Recidief",
    repeats: "Herhalingen",
    every: "Elke",
    days: "Dag(en)",
    weeks: "Weken(en)",
    months: "maand(en)",
    onDay: "Op een dag",
    onThe: "Op de",
    last: "Laatste",
    timeOfDay: "Tijd van de dag",
    dueDaysAfter: "Uitgerekend (dagen erna)",
    startDate: "Startdatum",
    endDate: "Einddatum",
    optional: "(optioneel)",
    recurrenceHelp: "Gemaakt op het gekozen tijdstip (binnen ~15 minuten). Begint vandaag standaard.",
    targetStores: "Doelwit {stores}",
    findStores: "Vind {stores}",
    loadingStores: "Laad {stores}...",
    searchStores: "Zoek {stores}...",
    loading: "Laden...",
    listHelp: "Taken komen in een &#34;Terugkerende taken&#34;-lijst in elke {store}.",
    assignTo: "Toewijzen aan",
    searchUsersGroups: "Zoek gebruikers en groepen...",
    users: "Gebruikers",
    groups: "Groepen",
    cancel: "Annuleren",
    createSchedule: "Maak schema aan",
    saveChanges: "Wijzigingen in het opslaan",
    errorLoading: "Foutlading",
    failedToLoad: "Niet geladen",
    selectStore: "Kies een {store}...",
    noStoresFound: "Geen {stores} gevonden",
    failedLoadStores: "Niet geladen {stores}",
    noSchedulesYet: "Nog geen terugkerende schema&#39;s.",
    clickNewToCreate: "Klik <b>op Nieuw</b> om er een aan te maken.",
    month: "Maand",
    today: "Vandaag de dag",
    pickWeekday: "Kies minstens één doordeweekse dag.",
    startNotPast: "De startdatum kan niet in het verleden zijn.",
    endAfterStart: "De einddatum moet op of na de startdatum zijn.",
    close: "Sluit",
    delete: "Verwijderen",
    edit: "Bewerking",
    nextRun: "Volgende run",
    activeRange: "Actief bereik",
    due: "Te betalen",
    assignedTo: "Toegewezen aan",
    anyoneWithAccess: "Iedereen met toegang tot de lijst",
    threeDay: "3 Dagen",
    daysAfterCreation: "{n} dagen na de schepping",
    tomorrow: "Morgen",
    nextPrefix: "Volgende:",
    rangeStarts: "Begint {date} · Geen einddatum",
    tasksWillBeCreated: "Er zullen taken worden aangemaakt — {summary}",
    scheduleSavedMsg: "Planning opgeslagen op {n} {store}. Taken worden automatisch aangemaakt — {summary}.",
    everyDay: "Elke dag",
    everyNDays: "Elke {n} dagen",
    weekly: "Wekelijks",
    everyNWeeks: "Elke {n} weken",
    everyWeekday: "Elke doordeweekse dag",
    monthly: "Maandelijks",
    everyNMonths: "Elke {n} maanden",
    ruleOnDays: "{every} op {days}",
    ruleOnDom: "{every} op dag {dom}",
    ruleOnNth: "{every} op de {ord} {day}",
    ruleAtTime: "{base} bij {time} {tz}",
    ord1: "1e",
    ord2: "2e",
    ord3: "3e",
    ord4: "4e",
    ordLast: "Laatste",
    sfEveryDay: "elke dag",
    sfEveryNDays: "elke {n} dagen",
    sfEveryWeekday: "Elke doordeweekse dag",
    sfEveryWeekend: "Elk weekend",
    sfDaysWeekly: "{days} elke week",
    sfDaysEveryNWeek: "{days} elke {ord} week",
    sfEveryDom: "Elke {ord}",
    sfEveryNDom: "Elke {int} {ord}",
    sfEveryNth: "Elke {nth} {day}",
    sfEveryNMoNth: "Elke {int} maand · {nth} {day}",
  },
  zh_CN: {
    recurringTasks: "重复任务",
    list: "列表",
    calendar: "赛程",
    newBtn: "新",
    taskDetails: "任务细节",
    title: "标题",
    titlePlaceholder: "需要做什么？",
    description: "描述",
    descriptionPlaceholder: "添加细节（可选）",
    type: "类型",
    noType: "—— 没有类型 ——",
    createNewType: "+ 创建新类型......",
    newTypePlaceholder: "新型号名称",
    priority: "优先级",
    normal: "普通",
    medium: "媒介",
    high: "高",
    critical: "批判",
    recurrence: "复发",
    repeats: "重复播放",
    every: "每一个",
    days: "日数",
    weeks: "周数",
    months: "月份",
    onDay: "白天",
    onThe: "在",
    last: "最后",
    timeOfDay: "一天中的时间",
    dueDaysAfter: "预产期（几天后）",
    startDate: "开始日期",
    endDate: "结束日期",
    optional: "（可选）",
    recurrenceHelp: "在指定时间创建（约15分钟内）。默认从今天开始。",
    targetStores: "目标{stores}",
    findStores: "找到{stores}",
    loadingStores: "正在加载{stores}......",
    searchStores: "搜查{stores}......",
    loading: "加载中......",
    listHelp: "任务会在每个{store}的“重复任务”列表中出现。",
    assignTo: "分配到",
    searchUsersGroups: "搜索用户和组......",
    users: "用户",
    groups: "团体",
    cancel: "取消",
    createSchedule: "创建日程",
    saveChanges: "存档更改",
    errorLoading: "错误加载",
    failedToLoad: "加载失败",
    selectStore: "选择一个{store}......",
    noStoresFound: "未发现{stores}",
    failedLoadStores: "加载失败{stores}",
    noSchedulesYet: "目前还没有固定的排班。",
    clickNewToCreate: "点击 <b>新建</b> 即可创建。",
    month: "月份",
    today: "现今",
    pickWeekday: "至少选一个工作日。",
    startNotPast: "入职日期不能是过去。",
    endAfterStart: "结束日期必须在开始日期当天或之后。",
    close: "结束",
    delete: "删除",
    edit: "编辑",
    nextRun: "下一次运行",
    activeRange: "活跃范围",
    due: "该",
    assignedTo: "隶属",
    anyoneWithAccess: "任何能访问名单的人",
    threeDay: "3天",
    daysAfterCreation: "创建后{n}天",
    tomorrow: "明天",
    nextPrefix: "下一篇：",
    rangeStarts: "开始时间{date}·无终止日期",
    tasksWillBeCreated: "任务会被创建——{summary}",
    scheduleSavedMsg: "日程保存在{n} {store}。任务会自动生成——{summary}。",
    everyDay: "每天都在",
    everyNDays: "每隔{n}天",
    weekly: "每周刊",
    everyNWeeks: "每{n}周一次",
    everyWeekday: "每个工作日",
    monthly: "月刊",
    everyNMonths: "每隔{n}个月一次",
    ruleOnDays: "{every}{days}",
    ruleOnDom: "{every}{dom}",
    ruleOnNth: "{every}在{ord} {day}",
    ruleAtTime: "{base} at {time} {tz}",
    ord1: "第一",
    ord2: "第二",
    ord3: "第三",
    ord4: "第四",
    ordLast: "最后",
    sfEveryDay: "每天都在",
    sfEveryNDays: "每隔{n}天",
    sfEveryWeekday: "每个工作日",
    sfEveryWeekend: "每个周末",
    sfDaysWeekly: "每周{days}",
    sfDaysEveryNWeek: "{days}每周{ord}一次",
    sfEveryDom: "每一个{ord}",
    sfEveryNDom: "每一个{int} {ord}",
    sfEveryNth: "每一个{nth} {day}",
    sfEveryNMoNth: "每隔{int}月 ·{nth} {day}",
  },
  ja_JP: {
    recurringTasks: "繰り返しの課題",
    list: "一覧",
    calendar: "カレンダー",
    newBtn: "新作",
    taskDetails: "タスク詳細",
    title: "タイトル",
    titlePlaceholder: "何をすべきでしょうか?",
    description: "概要",
    descriptionPlaceholder: "詳細の追加(任意)",
    type: "種類",
    noType: "— タイプなし —",
    createNewType: "+ 新しいタイプを作成...",
    newTypePlaceholder: "新しいタイプ名",
    priority: "優先順位",
    normal: "ノーマル",
    medium: "メディア",
    high: "ハイ",
    critical: "重要な点",
    recurrence: "再発",
    repeats: "リピート",
    every: "すべての",
    days: "日数",
    weeks: "週数",
    months: "月(s)",
    onDay: "昼間に",
    onThe: "その上での",
    last: "最後",
    timeOfDay: "時間帯",
    dueDaysAfter: "予定日(数日後)",
    startDate: "開始日",
    endDate: "終了日",
    optional: "(任意)",
    recurrenceHelp: "指定された時間(~15分以内)に作成されます。今日からデフォルトで開始されます。",
    targetStores: "ターゲット{stores}",
    findStores: "見つけ{stores}",
    loadingStores: "読み込み{stores}...",
    searchStores: "{stores}を捜索...",
    loading: "読み込み中...",
    listHelp: "タスクは各{store}の「繰り返しタスク」リストに表示されます。",
    assignTo: "割り当て",
    searchUsersGroups: "ユーザーやグループを検索...",
    users: "ユーザー",
    groups: "グループ",
    cancel: "キャンセル",
    createSchedule: "スケジュール作成",
    saveChanges: "セーブの変更",
    errorLoading: "エラーロード",
    failedToLoad: "ロードに失敗しました",
    selectStore: "{store}を選んで...",
    noStoresFound: "{stores}は見つかりませんでした",
    failedLoadStores: "ロードに失敗{stores}",
    noSchedulesYet: "まだ定期的なスケジュールはありません。",
    clickNewToCreate: "「 <b>新設</b> 」をクリックして作成してください。",
    month: "月間",
    today: "現在",
    pickWeekday: "少なくとも平日を1日は選んでください。",
    startNotPast: "開始日が過去のものではありえません。",
    endAfterStart: "終了日は開始日以降でなければなりません。",
    close: "閉じる",
    delete: "削除",
    edit: "編集",
    nextRun: "次の運行",
    activeRange: "アクティブレンジ",
    due: "期限",
    assignedTo: "配属先",
    anyoneWithAccess: "リストにアクセスできる人はいません",
    threeDay: "3日間",
    daysAfterCreation: "創設から{n}日",
    tomorrow: "明日",
    nextPrefix: "次回:",
    rangeStarts: "開始時間{date} ·終了日は不明です",
    tasksWillBeCreated: "タスクが作成されます — {summary}",
    scheduleSavedMsg: "スケジュールは{n} {store}に保存されました。タスクは自動的に作成されます — {summary}。",
    everyDay: "毎日",
    everyNDays: "{n}日ごとに",
    weekly: "週刊",
    everyNWeeks: "{n}週間ごとに",
    everyWeekday: "平日は毎回",
    monthly: "月刊",
    everyNMonths: "{n}ヶ月ごとに",
    ruleOnDays: "{every}{days}",
    ruleOnDom: "{every}日{dom}",
    ruleOnNth: "{every}{ord} {day}",
    ruleAtTime: "{base} at {time} {tz}",
    ord1: "1位",
    ord2: "第2位",
    ord3: "第3回",
    ord4: "第4戦",
    ordLast: "最後",
    sfEveryDay: "毎日",
    sfEveryNDays: "{n}日に一度",
    sfEveryWeekday: "平日は毎日",
    sfEveryWeekend: "毎週末",
    sfDaysWeekly: "毎週{days}",
    sfDaysEveryNWeek: "{days}週{ord}回",
    sfEveryDom: "毎{ord}",
    sfEveryNDom: "毎回{int} {ord}",
    sfEveryNth: "毎回{nth} {day}",
    sfEveryNMoNth: "毎{int}・{nth} {day}",
  },
  th_TH: {
    recurringTasks: "งานที่เกิดซ้ํา",
    list: "รายการ",
    calendar: "ปฏิทิน",
    newBtn: "ใหม่",
    taskDetails: "รายละเอียดงาน",
    title: "ชื่อเรื่อง",
    titlePlaceholder: "ต้องทําอะไรบ้าง?",
    description: "คําอธิบาย",
    descriptionPlaceholder: "เพิ่มรายละเอียด (ไม่บังคับ)",
    type: "ชนิดภาพเขียน",
    noType: "— ไม่มีประเภท —",
    createNewType: "+ สร้างประเภทใหม่...",
    newTypePlaceholder: "ชื่อประเภทใหม่",
    priority: "ลําดับความสําคัญ",
    normal: "ปกติ",
    medium: "ปานกลาง",
    high: "จุดสูง",
    critical: "วิกฤต",
    recurrence: "การเกิดซ้ํา",
    repeats: "ทําซ้ํา",
    every: "ทุก",
    days: "วัน",
    weeks: "สัปดาห์",
    months: "เดือน",
    onDay: "ในวันนั้น",
    onThe: "บน",
    last: "ล่าสุด",
    timeOfDay: "ช่วงเวลาของวัน",
    dueDaysAfter: "ครบกําหนดชําระ (วันหลังจาก)",
    startDate: "วันที่เริ่มต้น",
    endDate: "วันที่สิ้นสุด",
    optional: "(ไม่บังคับ)",
    recurrenceHelp: "สร้างขึ้นตามเวลาที่เลือก (ภายใน ~15 นาที) เริ่มวันนี้โดยค่าเริ่มต้น",
    targetStores: "เป้าหมาย {stores}",
    findStores: "ค้นหา{stores}",
    loadingStores: "กําลังโหลด{stores}...",
    searchStores: "ค้นหา{stores}...",
    loading: "กําลังโหลด...",
    listHelp: "งานจะอยู่ในรายการ &#34;งานที่เกิดซ้ํา&#34; ในแต่ละ{store}",
    assignTo: "มอบหมายให้",
    searchUsersGroups: "ค้นหาผู้ใช้และกลุ่ม...",
    users: "ผู้ใช้",
    groups: "กลุ่ม",
    cancel: "ยกเลิก",
    createSchedule: "สร้างกําหนดการ",
    saveChanges: "บันทึกการเปลี่ยนแปลง",
    errorLoading: "โหลดผิดพลาด",
    failedToLoad: "โหลดไม่สําเร็จ",
    selectStore: "เลือก{store}...",
    noStoresFound: "ไม่พบ{stores}",
    failedLoadStores: "โหลด{stores}ไม่สําเร็จ",
    noSchedulesYet: "ยังไม่มีกําหนดการที่เกิดซ้ํา",
    clickNewToCreate: "คลิก <b>สร้าง</b> เพื่อสร้าง",
    month: "เดือน",
    today: "วันนี้",
    pickWeekday: "เลือกอย่างน้อยหนึ่งวันธรรมดา",
    startNotPast: "วันที่เริ่มต้นต้องไม่เป็นอดีต",
    endAfterStart: "วันที่สิ้นสุดต้องตรงกับหรือหลังวันที่เริ่มต้น",
    close: "ปิด",
    delete: "ลบ",
    edit: "แก้ไข",
    nextRun: "การวิ่งครั้งต่อไป",
    activeRange: "ช่วงที่ใช้งานอยู่",
    due: "ครบกําหนด",
    assignedTo: "มอบหมายให้",
    anyoneWithAccess: "ทุกคนที่มีสิทธิ์เข้าถึงรายการ",
    threeDay: "3 วัน",
    daysAfterCreation: "{n} วันหลังจากสร้าง",
    tomorrow: "พรุ่งนี้",
    nextPrefix: "ต่อไป:",
    rangeStarts: "เริ่ม {date} · ไม่มีวันที่สิ้นสุด",
    tasksWillBeCreated: "งานจะถูกสร้างขึ้น — {summary}",
    scheduleSavedMsg: "กําหนดการที่บันทึกไว้ใน {n} {store} งานจะถูกสร้างขึ้นโดยอัตโนมัติ — {summary}",
    everyDay: "ทุกวัน",
    everyNDays: "ทุก {n} วัน",
    weekly: "รายสัปดาห์",
    everyNWeeks: "ทุก {n} สัปดาห์",
    everyWeekday: "ทุกวันธรรมดา",
    monthly: "รายเดือน",
    everyNMonths: "ทุก {n} เดือน",
    ruleOnDays: "{every}บน {days}",
    ruleOnDom: "{every}ในวันที่ {dom}",
    ruleOnNth: "{every}บน{ord} {day}",
    ruleAtTime: "{base}ที่ {time} {tz}",
    ord1: "อันดับ 1",
    ord2: "อันดับ 2",
    ord3: "อันดับ 3",
    ord4: "อันดับ 4",
    ordLast: "ล่าสุด",
    sfEveryDay: "ทุกวัน",
    sfEveryNDays: "ทุก {n} วัน",
    sfEveryWeekday: "ทุกวันธรรมดา",
    sfEveryWeekend: "ทุกสุดสัปดาห์",
    sfDaysWeekly: "{days}ทุกสัปดาห์",
    sfDaysEveryNWeek: "{days}ทุก {ord} สัปดาห์",
    sfEveryDom: "ทุก{ord}",
    sfEveryNDom: "ทุก{int} {ord}",
    sfEveryNth: "ทุก{nth} {day}",
    sfEveryNMoNth: "ทุก {int} เดือน · {nth} {day}",
  },
  es_MX: {
    recurringTasks: "Tareas recurrentes",
    list: "Lista",
    calendar: "Calendario",
    newBtn: "Nuevo",
    taskDetails: "Detalles de la tarea",
    title: "Título",
    titlePlaceholder: "¿Qué hay que hacer?",
    description: "Descripción",
    descriptionPlaceholder: "Añadir detalles (opcional)",
    type: "Tipo",
    noType: "— No hay tipo —",
    createNewType: "+ Crear un nuevo tipo...",
    newTypePlaceholder: "Nuevo nombre tipo",
    priority: "Prioridad",
    normal: "Normal",
    medium: "Medio",
    high: "Alto",
    critical: "Crítica",
    recurrence: "Recurrencia",
    repeats: "Repeticiones",
    every: "Cada",
    days: "Día(s)",
    weeks: "Semana(s)",
    months: "Mes o meses",
    onDay: "En el día",
    onThe: "En el",
    last: "Última",
    timeOfDay: "Hora del día",
    dueDaysAfter: "Fecha límite (días después)",
    startDate: "Fecha de inicio",
    endDate: "Fecha de finalización",
    optional: "(opcional)",
    recurrenceHelp: "Creado en el momento elegido (en ~15 minutos). Empieza hoy por defecto.",
    targetStores: "Objetivo {stores}",
    findStores: "Encuentra {stores}",
    loadingStores: "Cargando {stores}...",
    searchStores: "Registrar {stores}...",
    loading: "Cargando...",
    listHelp: "Las tareas aparecen en una lista de &#34;Tareas recurrentes&#34; en cada {store}.",
    assignTo: "Asignar a",
    searchUsersGroups: "Buscar usuarios y grupos...",
    users: "Usuarios",
    groups: "Grupos",
    cancel: "Cancelar",
    createSchedule: "Crear Horario",
    saveChanges: "Guardar cambios",
    errorLoading: "Carga de errores",
    failedToLoad: "No se ha cargado",
    selectStore: "Elige un {store}...",
    noStoresFound: "No se encontró {stores}",
    failedLoadStores: "No se ha podido cargar {stores}",
    noSchedulesYet: "Todavía no hay calendarios recurrentes.",
    clickNewToCreate: "Haz <b>clic en Nuevo</b> para crear uno.",
    month: "Mes",
    today: "Hoy",
    pickWeekday: "Elige al menos un día laborable.",
    startNotPast: "La fecha de inicio no puede ser del pasado.",
    endAfterStart: "La fecha de finalización debe ser en o después de la fecha de inicio.",
    close: "Cierre",
    delete: "Borrar",
    edit: "Edición",
    nextRun: "Próxima carrera",
    activeRange: "Rango activo",
    due: "Debido",
    assignedTo: "Asignado a",
    anyoneWithAccess: "¿Alguien con acceso a la lista",
    threeDay: "3 días",
    daysAfterCreation: "{n} días después de la creación",
    tomorrow: "Mañana",
    nextPrefix: "Siguiente:",
    rangeStarts: "Empieza {date} · Sin fecha de finalización",
    tasksWillBeCreated: "Se crearán tareas — {summary}",
    scheduleSavedMsg: "Horario guardado en {n} {store}. Las tareas se crearán automáticamente — {summary}.",
    everyDay: "Cada día",
    everyNDays: "Cada {n} días",
    weekly: "Semanal",
    everyNWeeks: "Cada {n} semanas",
    everyWeekday: "Todos los días laborables",
    monthly: "Mensual",
    everyNMonths: "Cada {n} meses",
    ruleOnDays: "{every} en {days}",
    ruleOnDom: "{every} el día {dom}",
    ruleOnNth: "{every} en el {ord} {day}",
    ruleAtTime: "{base} a {time} {tz}",
    ord1: "1º",
    ord2: "2º",
    ord3: "3º",
    ord4: "4º",
    ordLast: "Última",
    sfEveryDay: "todos los días",
    sfEveryNDays: "cada {n} días",
    sfEveryWeekday: "todos los días laborables",
    sfEveryWeekend: "todos los fines de semana",
    sfDaysWeekly: "{days} cada semana",
    sfDaysEveryNWeek: "{days} cada {ord} semana",
    sfEveryDom: "Cada {ord}",
    sfEveryNDom: "cada {int} {ord}",
    sfEveryNth: "cada {nth} {day}",
    sfEveryNMoNth: "cada {int} mes · {nth} {day}",
  },
  vi_VN: {
    recurringTasks: "Nhiệm vụ định kỳ",
    list: "Danh sách",
    calendar: "Lịch",
    newBtn: "Mới",
    taskDetails: "Chi tiết nhiệm vụ",
    title: "Tiêu đề",
    titlePlaceholder: "Cần phải làm gì?",
    description: "Sự miêu tả",
    descriptionPlaceholder: "Thêm chi tiết (tùy chọn)",
    type: "Kiểu",
    noType: "- Không có loại -",
    createNewType: "+ Tạo kiểu mới...",
    newTypePlaceholder: "Tên kiểu mới",
    priority: "Ưu tiên",
    normal: "Bình thường",
    medium: "Trung bình",
    high: "Cao",
    critical: "Quan trọng",
    recurrence: "Tái phát",
    repeats: "Lặp lại",
    every: "Mỗi",
    days: "Ngày",
    weeks: "Tuần",
    months: "Tháng",
    onDay: "Vào ngày",
    onThe: "Trên",
    last: "Cuối cùng",
    timeOfDay: "Thời gian trong ngày",
    dueDaysAfter: "Đến hạn (ngày sau)",
    startDate: "Ngày bắt đầu",
    endDate: "Ngày kết thúc",
    optional: "(tùy chọn)",
    recurrenceHelp: "Được tạo vào thời gian đã chọn (trong vòng ~15 phút). Bắt đầu từ hôm nay theo mặc định.",
    targetStores: "Mục tiêu {stores}",
    findStores: "Tìm {stores}",
    loadingStores: "Đang tải {stores}...",
    searchStores: "Tìm kiếm {stores}...",
    loading: "Đang tải...",
    listHelp: "Nhiệm vụ nằm trong danh sách &#34;Nhiệm vụ định kỳ&#34; trong mỗi {store}.",
    assignTo: "Gán cho",
    searchUsersGroups: "Tìm kiếm người dùng và nhóm...",
    users: "Người dùng",
    groups: "Nhóm",
    cancel: "Hủy bỏ",
    createSchedule: "Tạo lịch trình",
    saveChanges: "Lưu thay đổi",
    errorLoading: "Lỗi tải",
    failedToLoad: "Không tải được",
    selectStore: "Chọn một {store}...",
    noStoresFound: "Không tìm thấy {stores}",
    failedLoadStores: "Không tải được {stores}",
    noSchedulesYet: "Chưa có lịch trình định kỳ.",
    clickNewToCreate: "Nhấp vào <b>Mới</b> để tạo một tài khoản.",
    month: "Tháng",
    today: "Hôm nay",
    pickWeekday: "Chọn ít nhất một ngày trong tuần.",
    startNotPast: "Ngày bắt đầu không được quá khứ.",
    endAfterStart: "Ngày kết thúc phải vào hoặc sau ngày bắt đầu.",
    close: "Đóng",
    delete: "Xóa",
    edit: "Chỉnh sửa",
    nextRun: "Lần chạy tiếp theo",
    activeRange: "Phạm vi hoạt động",
    due: "Đến hạn",
    assignedTo: "Được chỉ định cho",
    anyoneWithAccess: "Bất kỳ ai có quyền truy cập vào danh sách",
    threeDay: "3 ngày",
    daysAfterCreation: "{n} ngày sau khi tạo",
    tomorrow: "Ngày mai",
    nextPrefix: "Kế tiếp:",
    rangeStarts: "Bắt đầu {date} · Không có ngày kết thúc",
    tasksWillBeCreated: "Nhiệm vụ sẽ được tạo — {summary}",
    scheduleSavedMsg: "Lịch trình được lưu vào {n} {store}. Nhiệm vụ sẽ được tạo tự động - {summary}.",
    everyDay: "Mỗi ngày",
    everyNDays: "{n} ngày một lần",
    weekly: "Hàng tuần",
    everyNWeeks: "{n} tuần một lần",
    everyWeekday: "Mỗi ngày trong tuần",
    monthly: "Hàng tháng",
    everyNMonths: "{n} tháng một lần",
    ruleOnDays: "{every} trên {days}",
    ruleOnDom: "{every} vào ngày {dom}",
    ruleOnNth: "{every} trên {ord} {day}",
    ruleAtTime: "{base} tại {time} {tz}",
    ord1: "Hạng 1",
    ord2: "Thứ 2",
    ord3: "Thứ 3",
    ord4: "Thứ 4",
    ordLast: "Cuối cùng",
    sfEveryDay: "mỗi ngày",
    sfEveryNDays: "{n} ngày một lần",
    sfEveryWeekday: "mỗi ngày trong tuần",
    sfEveryWeekend: "mỗi cuối tuần",
    sfDaysWeekly: "{days} mỗi tuần",
    sfDaysEveryNWeek: "{days} {ord} tuần một lần",
    sfEveryDom: "mỗi {ord}",
    sfEveryNDom: "mỗi {int} {ord}",
    sfEveryNth: "mỗi {nth} {day}",
    sfEveryNMoNth: "Mỗi {int} tháng · {nth} {day}",
  },
  ko_KR: {
    recurringTasks: "반복 과제",
    list: "목록",
    calendar: "일정",
    newBtn: "신규",
    taskDetails: "과제 세부사항",
    title: "제목",
    titlePlaceholder: "무엇을 해야 할까요?",
    description: "설명",
    descriptionPlaceholder: "세부 정보 추가(선택 사항)",
    type: "유형",
    noType: "— 종류 없음 —",
    createNewType: "+ 새로운 타입 생성...",
    newTypePlaceholder: "새로운 유형명입니다",
    priority: "우선순위",
    normal: "정상",
    medium: "매체",
    high: "높게",
    critical: "비평",
    recurrence: "재발",
    repeats: "반복 방송",
    every: "모든",
    days: "일(일)",
    weeks: "주(주)",
    months: "월(들)",
    onDay: "낮에",
    onThe: "그",
    last: "마지막이야",
    timeOfDay: "시간대",
    dueDaysAfter: "예정일 (며칠 후)",
    startDate: "시작일",
    endDate: "종료일",
    optional: "(선택 사항)",
    recurrenceHelp: "선택한 시간(~15분 이내)에 생성됩니다. 오늘부터 기본적으로 시작됩니다.",
    targetStores: "타겟 {stores}",
    findStores: "찾아{stores}",
    loadingStores: "로딩 {stores}...",
    searchStores: "수색{stores}...",
    loading: "로딩 중...",
    listHelp: "각 {store}에서 작업은 &#34;반복 작업&#34; 목록에 표시됩니다.",
    assignTo: "할당",
    searchUsersGroups: "사용자 및 그룹을 검색하세요...",
    users: "사용자",
    groups: "그룹",
    cancel: "취소",
    createSchedule: "일정 만들기",
    saveChanges: "저장 변경 사항",
    errorLoading: "오류 로딩",
    failedToLoad: "로딩 실패",
    selectStore: "{store} 선택하세요...",
    noStoresFound: "{stores} 발견되지 않았습니다",
    failedLoadStores: "로드에 실패{stores}",
    noSchedulesYet: "아직 반복 일정은 없습니다.",
    clickNewToCreate: "새로 <b>만들기</b> 를 클릭하세요.",
    month: "한 달",
    today: "오늘날",
    pickWeekday: "평일 중 최소 한 명을 골라보세요.",
    startNotPast: "시작일이 과거일 수는 없습니다.",
    endAfterStart: "종료일은 시작일과 맞거나 그 이후에 있어야 합니다.",
    close: "닫습니다",
    delete: "삭제",
    edit: "수정",
    nextRun: "다음 연주",
    activeRange: "활성 범위",
    due: "기분",
    assignedTo: "배속",
    anyoneWithAccess: "명단에 접근할 수 있는 사람",
    threeDay: "3일",
    daysAfterCreation: "창설 후 {n}일",
    tomorrow: "내일",
    nextPrefix: "다음:",
    rangeStarts: "시작 {date} · 종료일은 없습니다",
    tasksWillBeCreated: "과제가 생성될 것입니다 — {summary}",
    scheduleSavedMsg: "일정은 {n} {store}에 저장됨. 작업은 자동으로 생성됩니다 — {summary}.",
    everyDay: "매일",
    everyNDays: "{n}일마다",
    weekly: "주간",
    everyNWeeks: "{n}주마다",
    everyWeekday: "매주 평일",
    monthly: "월간",
    everyNMonths: "{n}개월마다",
    ruleOnDays: "{every} {days}",
    ruleOnDom: "{every} 날 {dom}",
    ruleOnNth: "{every} {ord} {day}",
    ruleAtTime: "{base} {time} {tz}",
    ord1: "1차",
    ord2: "2차",
    ord3: "3차",
    ord4: "4차",
    ordLast: "마지막이야",
    sfEveryDay: "매일",
    sfEveryNDays: "매 {n}일마다",
    sfEveryWeekday: "매주 평일",
    sfEveryWeekend: "매주 주말",
    sfDaysWeekly: "매주 {days}",
    sfDaysEveryNWeek: "{days} 주 {ord} 번씩",
    sfEveryDom: "매 {ord}",
    sfEveryNDom: "매 {int} {ord}",
    sfEveryNth: "매 {nth} {day}",
    sfEveryNMoNth: "한 {int} 모 · {nth} {day}",
  },
  tl_PH: {
    recurringTasks: "Mga Paulit-ulit na Gawain",
    list: "Listahan",
    calendar: "Kalendaryo",
    newBtn: "Bago",
    taskDetails: "Mga Detalye ng Gawain",
    title: "Pamagat",
    titlePlaceholder: "Ano ang kailangang gawin?",
    description: "Paglalarawan",
    descriptionPlaceholder: "Magdagdag ng mga detalye (opsyonal)",
    type: "Uri",
    noType: "— Walang uri —",
    createNewType: "+ Lumikha ng bagong uri ...",
    newTypePlaceholder: "Bagong uri ng pangalan",
    priority: "Prayoridad",
    normal: "Normal",
    medium: "Katamtaman",
    high: "Mataas",
    critical: "Kritikal",
    recurrence: "Pag-ulit",
    repeats: "Mga Pag-uulit",
    every: "Bawat",
    days: "(mga) araw",
    weeks: "(mga) linggo",
    months: "buwan",
    onDay: "Sa araw",
    onThe: "Sa",
    last: "huling",
    timeOfDay: "Oras ng araw",
    dueDaysAfter: "Takdang Panahon (Mga Araw Pagkatapos)",
    startDate: "Petsa ng pagsisimula",
    endDate: "Petsa ng pagtatapos",
    optional: "(opsyonal)",
    recurrenceHelp: "Nilikha sa napiling oras (sa loob ng ~ 15 min). Nagsisimula ngayon sa pamamagitan ng default.",
    targetStores: "Target {stores}",
    findStores: "Hanapin {stores}",
    loadingStores: "Pag-load {stores} ...",
    searchStores: "Hanapin {stores} ...",
    loading: "Naglo-load...",
    listHelp: "Ang mga gawain ay nakalapag sa listahan ng &#34;Mga Paulit-ulit na Gawain&#34; sa bawat {store}.",
    assignTo: "Magtalaga sa",
    searchUsersGroups: "Hanapin ang mga gumagamit at pangkat ...",
    users: "Mga Gumagamit",
    groups: "Mga Grupo",
    cancel: "Kanselahin",
    createSchedule: "Lumikha ng Iskedyul",
    saveChanges: "I-save ang Mga Pagbabago",
    errorLoading: "Error sa paglo-load",
    failedToLoad: "Nabigong mag-load",
    selectStore: "Pumili ng isang {store} ...",
    noStoresFound: "Walang {stores} natagpuan",
    failedLoadStores: "Nabigo akong mag-load ng {stores}",
    noSchedulesYet: "Wala pang paulit-ulit na iskedyul.",
    clickNewToCreate: "I-click ang <b>Bago</b> upang lumikha ng isa.",
    month: "Buwan",
    today: "Ngayong araw",
    pickWeekday: "Pumili ng hindi bababa sa isang araw ng linggo.",
    startNotPast: "Ang petsa ng pagsisimula ay hindi maaaring nasa nakaraan.",
    endAfterStart: "Ang petsa ng pagtatapos ay dapat na nasa o pagkatapos ng petsa ng pagsisimula.",
    close: "Isara",
    delete: "Tanggalin",
    edit: "Baguhin",
    nextRun: "Susunod na pagtakbo",
    activeRange: "Aktibong saklaw",
    due: "Dahil",
    assignedTo: "Itinalaga sa",
    anyoneWithAccess: "Sinuman ang may access sa listahan",
    threeDay: "3 Araw",
    daysAfterCreation: "{n} araw pagkatapos ng paglikha",
    tomorrow: "Bukas",
    nextPrefix: "Susunod:",
    rangeStarts: "Nagsisimula {date} · Walang Petsa ng Pagtatapos",
    tasksWillBeCreated: "Ang mga gawain ay lilikha - {summary}",
    scheduleSavedMsg: "I-save ang iskedyul para sa {n} {store}. Ang mga gawain ay awtomatikong nilikha - {summary}.",
    everyDay: "Araw-araw",
    everyNDays: "Bawat {n} araw",
    weekly: "Lingguhan",
    everyNWeeks: "Tuwing {n} linggo",
    everyWeekday: "Bawat araw ng linggo",
    monthly: "Buwanang",
    everyNMonths: "Tuwing {n} buwan",
    ruleOnDays: "{every} sa {days}",
    ruleOnDom: "{every} sa araw {dom}",
    ruleOnNth: "{every} sa {ord} {day}",
    ruleAtTime: "{base} sa {time} {tz}",
    ord1: "Ika-1",
    ord2: "Ika-2",
    ord3: "Ika-3",
    ord4: "Ika-4",
    ordLast: "huling",
    sfEveryDay: "araw-araw",
    sfEveryNDays: "Bawat {n} araw",
    sfEveryWeekday: "Araw-araw ng Linggo",
    sfEveryWeekend: "tuwing katapusan ng linggo",
    sfDaysWeekly: "{days} linggu-linggo",
    sfDaysEveryNWeek: "{days} bawat {ord} linggo",
    sfEveryDom: "bawat {ord}",
    sfEveryNDom: "bawat {int} {ord}",
    sfEveryNth: "bawat {nth} {day}",
    sfEveryNMoNth: "bawat {int} mo · {nth} {day}",
  },
  pt_BR: {
    recurringTasks: "Tarefas Recorrentes",
    list: "Lista",
    calendar: "Calendário",
    newBtn: "Novo",
    taskDetails: "Detalhes da Tarefa",
    title: "Título",
    titlePlaceholder: "O que precisa ser feito?",
    description: "Descrição",
    descriptionPlaceholder: "Adicionar detalhes (opcional)",
    type: "Tipo",
    noType: "— Sem tipo —",
    createNewType: "+ Criar novo tipo...",
    newTypePlaceholder: "Novo nome de tipo",
    priority: "Prioridade",
    normal: "Normal",
    medium: "Médio",
    high: "Alto",
    critical: "Crítica",
    recurrence: "Recorrência",
    repeats: "Reprises",
    every: "Cada",
    days: "Dia",
    weeks: "Semana(s)",
    months: "Mês(s)",
    onDay: "No dia",
    onThe: "No",
    last: "Última",
    timeOfDay: "Horário do dia",
    dueDaysAfter: "Prazo (dias depois)",
    startDate: "Data de início",
    endDate: "Data de término",
    optional: "(opcional)",
    recurrenceHelp: "Criado no tempo escolhido (dentro de ~15 minutos). Começa hoje por padrão.",
    targetStores: "Alvo {stores}",
    findStores: "Encontre {stores}",
    loadingStores: "Carregando {stores}...",
    searchStores: "Procurem {stores}...",
    loading: "Carregando...",
    listHelp: "As tarefas aparecem em uma lista de &#34;Tarefas Recorrentes&#34; em cada {store}.",
    assignTo: "Atribuir a",
    searchUsersGroups: "Pesquise usuários e grupos...",
    users: "Usuários",
    groups: "Grupos",
    cancel: "Cancelar",
    createSchedule: "Criar Cronograma",
    saveChanges: "Alterações de Salvamento",
    errorLoading: "Carregamento de erros",
    failedToLoad: "Falharam ao carregar",
    selectStore: "Escolha um {store}...",
    noStoresFound: "Nenhuma {stores} encontrada",
    failedLoadStores: "Não carreguei {stores}",
    noSchedulesYet: "Ainda não tem rotina recorrente.",
    clickNewToCreate: "Clique <b>em Novo</b> para criar um.",
    month: "Mês",
    today: "Hoje",
    pickWeekday: "Escolha pelo menos um dia da semana.",
    startNotPast: "A data de início não pode ser passada.",
    endAfterStart: "A data de término deve ser no dia de início ou depois dela.",
    close: "Fechar",
    delete: "Excluir",
    edit: "Edit",
    nextRun: "Próxima corrida",
    activeRange: "Alcance ativo",
    due: "Devido",
    assignedTo: "Designado para",
    anyoneWithAccess: "Alguém com acesso à lista",
    threeDay: "3 dias",
    daysAfterCreation: "{n} dias após a criação",
    tomorrow: "Amanhã",
    nextPrefix: "Próximo:",
    rangeStarts: "Começa {date} · Sem data de término",
    tasksWillBeCreated: "As tarefas serão criadas — {summary}",
    scheduleSavedMsg: "Horário salvo para {n} {store}. As tarefas serão criadas automaticamente — {summary}.",
    everyDay: "Todos os dias",
    everyNDays: "A cada {n} dias",
    weekly: "Semanal",
    everyNWeeks: "A cada {n} semanas",
    everyWeekday: "Todos os dias úteis",
    monthly: "Mensal",
    everyNMonths: "A cada {n} meses",
    ruleOnDays: "{every} em {days}",
    ruleOnDom: "{every} no dia {dom}",
    ruleOnNth: "{every} no {ord} {day}",
    ruleAtTime: "{base} {time} {tz}",
    ord1: "1º",
    ord2: "2º",
    ord3: "3º",
    ord4: "4º",
    ordLast: "Última",
    sfEveryDay: "todos os dias",
    sfEveryNDays: "a cada {n} dias",
    sfEveryWeekday: "Todos os dias úteis",
    sfEveryWeekend: "Todo fim de semana",
    sfDaysWeekly: "{days} toda semana",
    sfDaysEveryNWeek: "{days} toda {ord} semana",
    sfEveryDom: "todo {ord}",
    sfEveryNDom: "Todo {int} {ord}",
    sfEveryNth: "Todo {nth} {day}",
    sfEveryNMoNth: "a cada {int} mês · {nth} {day}",
  },
  ht_HT: {
    recurringTasks: "Travay renouvlab",
    list: "Lis",
    calendar: "Kalandriye a",
    newBtn: "Nouvo",
    taskDetails: "Detay Travay la",
    title: "",
    titlePlaceholder: "Kisa ki dwe fè?",
    description: "Deskripsyon",
    descriptionPlaceholder: "Ajoute detay (si ou vle)",
    type: "Kalite",
    noType: "— Pa gen kalite —",
    createNewType: "+ Kreye nouvo kalite...",
    newTypePlaceholder: "Nouvo non kalite",
    priority: "Priyorite",
    normal: "Nòmal",
    medium: "Mwayen",
    high: "Segondè",
    critical: "Kritik",
    recurrence: "Renouvèlte",
    repeats: "Repete",
    every: "Chak",
    days: "Jou (yo)",
    weeks: "semèn(yo)",
    months: "mwa (yo)",
    onDay: "Nan jou",
    onThe: "Sou la",
    last: "dènye",
    timeOfDay: "Lè nan jounen an",
    dueDaysAfter: "Akòz (jou apre)",
    startDate: "Kòmanse dat",
    endDate: "Dat fen",
    optional: "(si ou vle)",
    recurrenceHelp: "Kreye nan moman chwazi a (nan ~ 15 min) Kòmanse jodi a pa default.",
    targetStores: "Sib {stores}",
    findStores: "Jwenn {stores}",
    loadingStores: "Loading {stores}...",
    searchStores: "Rechèch {stores}...",
    loading: "Chaje ...",
    listHelp: "Travay yo ateri nan yon lis &#34;Travay renouvlab&#34; nan chak {store}.",
    assignTo: "Asiyen a",
    searchUsersGroups: "Itilizatè rechèch ak gwoup ...",
    users: "Itilizatè yo",
    groups: "Gwoup yo",
    cancel: "Anile",
    createSchedule: "Kreye Orè",
    saveChanges: "Sove chanjman yo",
    errorLoading: "Erè loading",
    failedToLoad: "Echwe pou pou chaje",
    selectStore: "Chwazi yon {store}...",
    noStoresFound: "Pa gen {stores} jwenn",
    failedLoadStores: "Echwe pou pou chaje {stores}",
    noSchedulesYet: "Pa gen orè renouvlab ankò.",
    clickNewToCreate: "Klike <b>sou Nouvo</b> pou kreye youn.",
    month: "Mwa",
    today: "Jodi a",
    pickWeekday: "Chwazi omwen yon jou lasemèn",
    startNotPast: "Kòmanse dat pa ka nan tan lontan an.",
    endAfterStart: "Dat fen yo dwe sou oswa apre dat kòmansman an.",
    close: "Fèmen",
    delete: "Efase",
    edit: "modifye",
    nextRun: "Next kouri",
    activeRange: "Aktif ranje",
    due: "Akòz",
    assignedTo: "Asiyen nan",
    anyoneWithAccess: "Nenpòt moun ki gen aksè nan lis la",
    threeDay: "3 Jou",
    daysAfterCreation: "{n} jou apre kreyasyon an",
    tomorrow: "Demen",
    nextPrefix: "Pwochen:",
    rangeStarts: "kòmanse {date} · Pa gen dat fen",
    tasksWillBeCreated: "Travay yo pral kreye — {summary}",
    scheduleSavedMsg: "Orè sove {n} {store} Travay yo pral kreye otomatikman — {summary}",
    everyDay: "Chak jou",
    everyNDays: "Chak {n} jou",
    weekly: "Chak semèn",
    everyNWeeks: "Chak {n} semèn",
    everyWeekday: "Chak jou lasemèn",
    monthly: "Chak mwa",
    everyNMonths: "Chak {n} mwa",
    ruleOnDays: "{every} sou {days}",
    ruleOnDom: "{every} jou {dom}",
    ruleOnNth: "{every} sou {ord} {day}",
    ruleAtTime: "{base} nan {time} {tz}",
    ord1: "1ye",
    ord2: "2º",
    ord3: "3yèm",
    ord4: "4yèm",
    ordLast: "dènye",
    sfEveryDay: "chak jou",
    sfEveryNDays: "chak {n} jou",
    sfEveryWeekday: "chak jou lasemèn",
    sfEveryWeekend: "chak wikenn",
    sfDaysWeekly: "{days} chak semèn",
    sfDaysEveryNWeek: "{days} chak {ord} semèn",
    sfEveryDom: "chak {ord}",
    sfEveryNDom: "chak {int} {ord}",
    sfEveryNth: "chak {nth} {day}",
    sfEveryNMoNth: "chak {int} mwa · {nth} {day}",
  },
};
