// Pilot i18n bundles for recurring-tasks-widget. en_US canonical; de_DE / ar_SA
// pilot translations; missing keys fall back to en_US via makeT().
//
// NOTE: priority levels and the recurrence-rule summary text are task DATA
// (content), not chrome — they are intentionally NOT translated here.
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    recurringTasks: "Recurring Tasks",
    list: "List",
    calendar: "Calendar",
    newBtn: "New",
    taskDetails: "Task Details",
    title: "Title",
    titlePlaceholder: "What needs to be done?",
    description: "Description",
    descriptionPlaceholder: "Add details (optional)",
    type: "Type",
    noType: "— No type —",
    createNewType: "+ Create new type…",
    newTypePlaceholder: "New type name",
    priority: "Priority",
    normal: "Normal",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    recurrence: "Recurrence",
    repeats: "Repeats",
    every: "Every",
    days: "day(s)",
    weeks: "week(s)",
    months: "month(s)",
    onDay: "On day",
    onThe: "On the",
    last: "last",
    timeOfDay: "Time of day",
    dueDaysAfter: "Due (days after)",
    startDate: "Start date",
    endDate: "End date",
    optional: "(optional)",
    recurrenceHelp: "Created at the chosen time (within ~15 min). Starts today by default.",
    targetStores: "Target {stores}",
    findStores: "Find {stores}",
    loadingStores: "Loading {stores}…",
    searchStores: "Search {stores}…",
    loading: "Loading…",
    listHelp: 'Tasks land in a "Recurring Tasks" list in each {store}.',
    assignTo: "Assign To",
    searchUsersGroups: "Search users and groups…",
    users: "Users",
    groups: "Groups",
    cancel: "Cancel",
    createSchedule: "Create Schedule",
    saveChanges: "Save Changes",
    errorLoading: "Error loading",
    failedToLoad: "Failed to load",
    selectStore: "Select a {store}…",
    noStoresFound: "No {stores} found",
    failedLoadStores: "Failed to load {stores}",
    noSchedulesYet: "No recurring schedules yet.",
    clickNewToCreate: "Click <b>New</b> to create one.",
    month: "Month",
    today: "Today",
    pickWeekday: "Pick at least one weekday.",
    startNotPast: "Start date can't be in the past.",
    endAfterStart: "End date must be on or after the start date.",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    nextRun: "Next run",
    activeRange: "Active range",
    due: "Due",
    assignedTo: "Assigned to",
    anyoneWithAccess: "Anyone with access to the list",
    threeDay: "3 Day",
    daysAfterCreation: "{n} days after creation",
  },
  de_DE: {
    recurringTasks: "Wiederkehrende Aufgaben",
    list: "Liste",
    calendar: "Kalender",
    newBtn: "Neu",
    taskDetails: "Aufgabendetails",
    title: "Titel",
    titlePlaceholder: "Was ist zu tun?",
    description: "Beschreibung",
    descriptionPlaceholder: "Details hinzufügen (optional)",
    type: "Typ",
    noType: "— Kein Typ —",
    createNewType: "+ Neuen Typ erstellen…",
    newTypePlaceholder: "Name des neuen Typs",
    priority: "Priorität",
    normal: "Normal",
    medium: "Mittel",
    high: "Hoch",
    critical: "Kritisch",
    recurrence: "Wiederholung",
    repeats: "Wiederholt sich",
    every: "Alle",
    days: "Tag(e)",
    weeks: "Woche(n)",
    months: "Monat(e)",
    onDay: "Am Tag",
    onThe: "Am",
    last: "letzten",
    timeOfDay: "Uhrzeit",
    dueDaysAfter: "Fällig (Tage danach)",
    startDate: "Startdatum",
    endDate: "Enddatum",
    optional: "(optional)",
    recurrenceHelp: "Wird zur gewählten Zeit erstellt (innerhalb von ~15 Min.). Beginnt standardmäßig heute.",
    targetStores: "Ziel-{stores}",
    findStores: "{stores} finden",
    loadingStores: "{stores} werden geladen…",
    searchStores: "{stores} suchen…",
    loading: "Wird geladen…",
    listHelp: 'Aufgaben landen in einer Liste „Wiederkehrende Aufgaben" in jeder {store}.',
    assignTo: "Zuweisen an",
    searchUsersGroups: "Benutzer und Gruppen suchen…",
    users: "Benutzer",
    groups: "Gruppen",
    cancel: "Abbrechen",
    createSchedule: "Zeitplan erstellen",
    saveChanges: "Änderungen speichern",
    errorLoading: "Fehler beim Laden",
    failedToLoad: "Laden fehlgeschlagen",
    selectStore: "{store} auswählen…",
    noStoresFound: "Keine {stores} gefunden",
    failedLoadStores: "{stores} konnten nicht geladen werden",
    noSchedulesYet: "Noch keine wiederkehrenden Zeitpläne.",
    clickNewToCreate: "Klicken Sie auf <b>Neu</b>, um einen zu erstellen.",
    month: "Monat",
    today: "Heute",
    pickWeekday: "Wählen Sie mindestens einen Wochentag.",
    startNotPast: "Das Startdatum darf nicht in der Vergangenheit liegen.",
    endAfterStart: "Das Enddatum muss am oder nach dem Startdatum liegen.",
    close: "Schließen",
    delete: "Löschen",
    edit: "Bearbeiten",
    nextRun: "Nächste Ausführung",
    activeRange: "Aktiver Zeitraum",
    due: "Fällig",
    assignedTo: "Zugewiesen an",
    anyoneWithAccess: "Jeder mit Zugriff auf die Liste",
    threeDay: "3 Tage",
    daysAfterCreation: "{n} Tage nach Erstellung",
  },
  ar_SA: {
    recurringTasks: "المهام المتكررة",
    list: "قائمة",
    calendar: "تقويم",
    newBtn: "جديد",
    taskDetails: "تفاصيل المهمة",
    title: "العنوان",
    titlePlaceholder: "ما الذي يجب إنجازه؟",
    description: "الوصف",
    descriptionPlaceholder: "أضف تفاصيل (اختياري)",
    type: "النوع",
    noType: "— بلا نوع —",
    createNewType: "+ إنشاء نوع جديد…",
    newTypePlaceholder: "اسم النوع الجديد",
    priority: "الأولوية",
    normal: "عادية",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    recurrence: "التكرار",
    repeats: "يتكرر",
    every: "كل",
    days: "يوم/أيام",
    weeks: "أسبوع/أسابيع",
    months: "شهر/أشهر",
    onDay: "في يوم",
    onThe: "في",
    last: "الأخير",
    timeOfDay: "وقت اليوم",
    dueDaysAfter: "الاستحقاق (بعد أيام)",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    optional: "(اختياري)",
    recurrenceHelp: "تُنشأ في الوقت المحدد (خلال ~15 دقيقة). تبدأ اليوم افتراضيًا.",
    targetStores: "{stores} المستهدفة",
    findStores: "ابحث عن {stores}",
    loadingStores: "جارٍ تحميل {stores}…",
    searchStores: "ابحث في {stores}…",
    loading: "جارٍ التحميل…",
    listHelp: 'تظهر المهام في قائمة «المهام المتكررة» في كل {store}.',
    assignTo: "إسناد إلى",
    searchUsersGroups: "ابحث عن مستخدمين ومجموعات…",
    users: "المستخدمون",
    groups: "المجموعات",
    cancel: "إلغاء",
    createSchedule: "إنشاء جدول",
    saveChanges: "حفظ التغييرات",
    errorLoading: "خطأ في التحميل",
    failedToLoad: "فشل التحميل",
    selectStore: "اختر {store}…",
    noStoresFound: "لم يتم العثور على {stores}",
    failedLoadStores: "فشل تحميل {stores}",
    noSchedulesYet: "لا توجد جداول متكررة بعد.",
    clickNewToCreate: "انقر على <b>جديد</b> لإنشاء واحد.",
    month: "شهر",
    today: "اليوم",
    pickWeekday: "اختر يوم أسبوع واحدًا على الأقل.",
    startNotPast: "لا يمكن أن يكون تاريخ البدء في الماضي.",
    endAfterStart: "يجب أن يكون تاريخ الانتهاء في تاريخ البدء أو بعده.",
    close: "إغلاق",
    delete: "حذف",
    edit: "تعديل",
    nextRun: "التشغيل التالي",
    activeRange: "النطاق النشط",
    due: "الاستحقاق",
    assignedTo: "مُسنَدة إلى",
    anyoneWithAccess: "أي شخص لديه حق الوصول إلى القائمة",
    threeDay: "3 أيام",
    daysAfterCreation: "{n} يوم بعد الإنشاء",
  },
};
