// Pilot i18n bundles for tasks-integration-widget. en_US canonical; de_DE / ar_SA
// pilot; missing keys fall back to en_US via makeT(). NOTE: this widget uses `tr`
// as a table-row variable, so the translator is bound as `tx` (not `tr`).
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    targetStores: "Target {stores}",
    findStores: "Find {stores}",
    loadingStores: "Loading {stores}…",
    searchStores: "Search {stores}…",
    selectStore: "Select a {store}…",
    noStoresFound: "No {stores} found",
    failedLoadStores: "Failed to load {stores}",
    errorLoading: "Error loading",
    loading: "Loading…",
    pullReviewTasks: "Pull & Review Tasks",
    taskListName: "Task List Name",
    taskListNamePlaceholder: "e.g., Q2 Store Checklist",
    pullFromExternal: "Pull from External Services",
    reviewEditTasks: "Review & Edit Tasks",
    nTasks: "{n} tasks",
    title: "Title",
    taskTitlePlaceholder: "Task title",
    description: "Description",
    type: "Type",
    noneOption: "— none —",
    dueDate: "Due Date",
    addTask: "Add task",
    attachFiles: "Attach files",
    remove: "Remove",
    attached: "attached:",
    assignTo: "Assign To",
    optional: "(optional)",
    searchUsersGroups: "Search users and groups…",
    users: "Users",
    groups: "Groups",
    noUsersFound: "No users found",
    noGroupsFound: "No groups found",
    failedToLoad: "Failed to load",
    updateExistingList: "Update Existing List",
    selectListToUpdate: "Select a list to update",
    createNewList: "— Create a new list —",
    replaceHint: "If selected, all tasks in that list are replaced. Leave blank to create a new list.",
    working: "Working…",
    updateYourTasks: "Update your Tasks",
    noTasksInSheet: "No tasks found in the sheet.",
    nTasksAdded: "{n} tasks added",
    done: "Done!",
  },
  de_DE: {
    targetStores: "Ziel-{stores}",
    findStores: "{stores} finden",
    loadingStores: "{stores} werden geladen…",
    searchStores: "{stores} suchen…",
    selectStore: "{store} auswählen…",
    noStoresFound: "Keine {stores} gefunden",
    failedLoadStores: "{stores} konnten nicht geladen werden",
    errorLoading: "Fehler beim Laden",
    loading: "Wird geladen…",
    pullReviewTasks: "Aufgaben abrufen & prüfen",
    taskListName: "Name der Aufgabenliste",
    taskListNamePlaceholder: "z. B. Q2 Filial-Checkliste",
    pullFromExternal: "Aus externen Diensten abrufen",
    reviewEditTasks: "Aufgaben prüfen & bearbeiten",
    nTasks: "{n} Aufgaben",
    title: "Titel",
    taskTitlePlaceholder: "Aufgabentitel",
    description: "Beschreibung",
    type: "Typ",
    noneOption: "— keine —",
    dueDate: "Fälligkeitsdatum",
    addTask: "Aufgabe hinzufügen",
    attachFiles: "Dateien anhängen",
    remove: "Entfernen",
    attached: "angehängt:",
    assignTo: "Zuweisen an",
    optional: "(optional)",
    searchUsersGroups: "Benutzer und Gruppen suchen…",
    users: "Benutzer",
    groups: "Gruppen",
    noUsersFound: "Keine Benutzer gefunden",
    noGroupsFound: "Keine Gruppen gefunden",
    failedToLoad: "Laden fehlgeschlagen",
    updateExistingList: "Bestehende Liste aktualisieren",
    selectListToUpdate: "Liste zum Aktualisieren auswählen",
    createNewList: "— Neue Liste erstellen —",
    replaceHint: "Wenn ausgewählt, werden alle Aufgaben in dieser Liste ersetzt. Leer lassen, um eine neue Liste zu erstellen.",
    working: "Wird bearbeitet…",
    updateYourTasks: "Aufgaben aktualisieren",
    noTasksInSheet: "Keine Aufgaben in der Tabelle gefunden.",
    nTasksAdded: "{n} Aufgaben hinzugefügt",
    done: "Fertig!",
  },
  ar_SA: {
    targetStores: "{stores} المستهدفة",
    findStores: "ابحث عن {stores}",
    loadingStores: "جارٍ تحميل {stores}…",
    searchStores: "ابحث في {stores}…",
    selectStore: "اختر {store}…",
    noStoresFound: "لم يتم العثور على {stores}",
    failedLoadStores: "فشل تحميل {stores}",
    errorLoading: "خطأ في التحميل",
    loading: "جارٍ التحميل…",
    pullReviewTasks: "سحب ومراجعة المهام",
    taskListName: "اسم قائمة المهام",
    taskListNamePlaceholder: "مثال: قائمة تدقيق الربع الثاني",
    pullFromExternal: "السحب من الخدمات الخارجية",
    reviewEditTasks: "مراجعة وتحرير المهام",
    nTasks: "{n} مهام",
    title: "العنوان",
    taskTitlePlaceholder: "عنوان المهمة",
    description: "الوصف",
    type: "النوع",
    noneOption: "— بلا —",
    dueDate: "تاريخ الاستحقاق",
    addTask: "إضافة مهمة",
    attachFiles: "إرفاق ملفات",
    remove: "إزالة",
    attached: "مرفق:",
    assignTo: "إسناد إلى",
    optional: "(اختياري)",
    searchUsersGroups: "ابحث عن مستخدمين ومجموعات…",
    users: "المستخدمون",
    groups: "المجموعات",
    noUsersFound: "لم يتم العثور على مستخدمين",
    noGroupsFound: "لم يتم العثور على مجموعات",
    failedToLoad: "فشل التحميل",
    updateExistingList: "تحديث قائمة موجودة",
    selectListToUpdate: "اختر قائمة لتحديثها",
    createNewList: "— إنشاء قائمة جديدة —",
    replaceHint: "في حال التحديد، سيتم استبدال جميع المهام في تلك القائمة. اتركه فارغًا لإنشاء قائمة جديدة.",
    working: "جارٍ العمل…",
    updateYourTasks: "تحديث مهامك",
    noTasksInSheet: "لم يتم العثور على مهام في الورقة.",
    nTasksAdded: "{n} مهام مُضافة",
    done: "تم!",
  },
};
