// Pilot i18n bundles for my-tasks-widget.
// en_US is the canonical source (edit by hand). de_DE / ar_SA are the pilot
// translations. Add more locales by adding another keyed bundle; any missing
// key falls back to en_US via makeT().
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    myTasks: "My Tasks",
    auditResults: "Audit Results",
    newTask: "New task",
    refresh: "Refresh",
    translateBtn: "Translate",
    showOriginal: "Show original",
    translating: "Translating…",
    auditHistory: "Audit History",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    allTypes: "All Types",
    nTypes: "{n} types",
    noTypeLabel: "No Type",
    open: "Open",
    done: "Done",
    both: "Both",
    close: "Close",
    noPreview: "No preview available — use Download",
    groups: "Groups",
    people: "People",
    loading: "Loading…",
    unassign: "Unassign",
    reassign: "Reassign",
    assign: "Assign",
    add: "Add",
    send: "Send",
    noCommentsYet: "No comments yet. Be the first to comment.",
    noAttachments: "No attachments",
    remove: "Remove",
    noAuditsFound: "No audits found",
    selectAudit: "Select an audit above.",
    noFailureTasks: "No failure tasks in this audit.",
    noTasksAssigned: "No tasks assigned to you in this audit.",
    allTasksComplete: "All tasks completed for this audit!",
    nTasksMarkedDone: "{n} tasks marked done",
    nTasksFlagged: "{n} tasks flagged",
    showOtherTasks: "Show {n} other tasks in this audit",
    hideOtherTasks: "Hide {n} other tasks in this audit",
    myTasksN: "My tasks ({n})",
    allCaughtUp: "No open tasks — all caught up!",
    notes: "Notes",
    attachments: "Attachments",
    categoryBreakdown: "Category breakdown",
    noGroupAssigned: "No group assigned",
    noIndividualAssignee: "No individual assignee",
    group: "Group",
    person: "Person",
    searchPeopleGroups: "Search people or groups…",
    auditFinding: "Audit Finding",
    description: "Description",
    noDescription: "No description",
    comments: "Comments",
    addComment: "Add a comment…",
    attachFile: "Attach file",
    noTaskSpaces: "No task spaces found",
    noTaskSpacesHint: "Make sure at least one Tasks installation exists.",
    failedToLoad: "Failed to load tasks",
    noTasksFound: "No tasks found",
    allCaughtUpPersonal: "No open tasks — you're all caught up!",
    noCompletedTasks: "No completed tasks yet",
    auditEmptyHint: "Submit an audit using the Audit Widget to see results here.",
    noMatches: "No matches",
    createFailedPrefix: "Couldn't create task:",
    newTaskHeading: "New Task",
    title: "Title",
    titlePlaceholder: "What needs to be done?",
    descriptionPlaceholder: "Add details (optional)",
    list: "List",
    type: "Type",
    newTypePlaceholder: "New type name",
    noType: "— No type —",
    createNewType: "+ Create new type…",
    dueDate: "Due date",
    dueLabel: "Due",
    overdueLabel: "Overdue",
    priority: "Priority",
    normal: "Normal",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    recurring: "Recurring",
    cancel: "Cancel",
    createTask: "Create Task",
    creating: "Creating…",
    debug: "Debug",
    copy: "Copy",
    clear: "Clear",
    hide: "Hide",
    copied: "Copied!",
    copyFailed: "Copy failed",
    hideCompleted: "Hide completed",
    showCompletedN: "Show completed ({n})",
    markAsOpen: "Mark as open",
    markAsDone: "Mark as done",
    passing: "Passing",
    failing: "Failing",
    notScored: "Not scored",
  },
  de_DE: {
    myTasks: "Meine Aufgaben",
    auditResults: "Audit-Ergebnisse",
    newTask: "Neue Aufgabe",
    refresh: "Aktualisieren",
    translateBtn: "Übersetzen",
    showOriginal: "Original anzeigen",
    translating: "Wird übersetzt…",
    auditHistory: "Audit-Verlauf",
    scrollLeft: "Nach links scrollen",
    scrollRight: "Nach rechts scrollen",
    allTypes: "Alle Typen",
    nTypes: "{n} Typen",
    noTypeLabel: "Kein Typ",
    open: "Offen",
    done: "Erledigt",
    both: "Beide",
    close: "Schließen",
    noPreview: "Keine Vorschau verfügbar – Download verwenden",
    groups: "Gruppen",
    people: "Personen",
    loading: "Wird geladen…",
    unassign: "Zuweisung aufheben",
    reassign: "Neu zuweisen",
    assign: "Zuweisen",
    add: "Hinzufügen",
    send: "Senden",
    noCommentsYet: "Noch keine Kommentare. Schreiben Sie den ersten Kommentar.",
    noAttachments: "Keine Anhänge",
    remove: "Entfernen",
    noAuditsFound: "Keine Audits gefunden",
    selectAudit: "Wählen Sie oben ein Audit aus.",
    noFailureTasks: "Keine Fehleraufgaben in diesem Audit.",
    noTasksAssigned: "Ihnen sind in diesem Audit keine Aufgaben zugewiesen.",
    allTasksComplete: "Alle Aufgaben für dieses Audit abgeschlossen!",
    nTasksMarkedDone: "{n} Aufgaben als erledigt markiert",
    nTasksFlagged: "{n} Aufgaben markiert",
    showOtherTasks: "{n} weitere Aufgaben in diesem Audit anzeigen",
    hideOtherTasks: "{n} weitere Aufgaben in diesem Audit ausblenden",
    myTasksN: "Meine Aufgaben ({n})",
    allCaughtUp: "Keine offenen Aufgaben – alles erledigt!",
    notes: "Notizen",
    attachments: "Anhänge",
    categoryBreakdown: "Kategorienaufschlüsselung",
    noGroupAssigned: "Keine Gruppe zugewiesen",
    noIndividualAssignee: "Keine Einzelperson zugewiesen",
    group: "Gruppe",
    person: "Person",
    searchPeopleGroups: "Personen oder Gruppen suchen…",
    auditFinding: "Audit-Feststellung",
    description: "Beschreibung",
    noDescription: "Keine Beschreibung",
    comments: "Kommentare",
    addComment: "Kommentar hinzufügen…",
    attachFile: "Datei anhängen",
    noTaskSpaces: "Keine Aufgabenbereiche gefunden",
    noTaskSpacesHint: "Stellen Sie sicher, dass mindestens eine Aufgaben-Installation vorhanden ist.",
    failedToLoad: "Aufgaben konnten nicht geladen werden",
    noTasksFound: "Keine Aufgaben gefunden",
    allCaughtUpPersonal: "Keine offenen Aufgaben – alles erledigt!",
    noCompletedTasks: "Noch keine erledigten Aufgaben",
    auditEmptyHint: "Reichen Sie ein Audit über das Audit-Widget ein, um hier Ergebnisse zu sehen.",
    noMatches: "Keine Treffer",
    createFailedPrefix: "Aufgabe konnte nicht erstellt werden:",
    newTaskHeading: "Neue Aufgabe",
    title: "Titel",
    titlePlaceholder: "Was ist zu tun?",
    descriptionPlaceholder: "Details hinzufügen (optional)",
    list: "Liste",
    type: "Typ",
    newTypePlaceholder: "Name des neuen Typs",
    noType: "— Kein Typ —",
    createNewType: "+ Neuen Typ erstellen…",
    dueDate: "Fälligkeitsdatum",
    dueLabel: "Fällig",
    overdueLabel: "Überfällig",
    priority: "Priorität",
    normal: "Normal",
    medium: "Mittel",
    high: "Hoch",
    critical: "Kritisch",
    recurring: "Wiederkehrend",
    cancel: "Abbrechen",
    createTask: "Aufgabe erstellen",
    creating: "Wird erstellt…",
    debug: "Debug",
    copy: "Kopieren",
    clear: "Leeren",
    hide: "Ausblenden",
    copied: "Kopiert!",
    copyFailed: "Kopieren fehlgeschlagen",
    hideCompleted: "Erledigte ausblenden",
    showCompletedN: "Erledigte anzeigen ({n})",
    markAsOpen: "Als offen markieren",
    markAsDone: "Als erledigt markieren",
    passing: "Bestanden",
    failing: "Nicht bestanden",
    notScored: "Nicht bewertet",
  },
  ar_SA: {
    myTasks: "مهامي",
    auditResults: "نتائج التدقيق",
    newTask: "مهمة جديدة",
    refresh: "تحديث",
    translateBtn: "ترجمة",
    showOriginal: "إظهار الأصل",
    translating: "جارٍ الترجمة…",
    auditHistory: "سجل التدقيق",
    scrollLeft: "التمرير لليسار",
    scrollRight: "التمرير لليمين",
    allTypes: "جميع الأنواع",
    nTypes: "{n} أنواع",
    noTypeLabel: "بلا نوع",
    open: "مفتوحة",
    done: "مكتملة",
    both: "كلاهما",
    close: "إغلاق",
    noPreview: "لا تتوفر معاينة — استخدم التنزيل",
    groups: "المجموعات",
    people: "الأشخاص",
    loading: "جارٍ التحميل…",
    unassign: "إلغاء التعيين",
    reassign: "إعادة التعيين",
    assign: "تعيين",
    add: "إضافة",
    send: "إرسال",
    noCommentsYet: "لا توجد تعليقات بعد. كن أول من يعلّق.",
    noAttachments: "لا توجد مرفقات",
    remove: "إزالة",
    noAuditsFound: "لم يتم العثور على عمليات تدقيق",
    selectAudit: "اختر عملية تدقيق من الأعلى.",
    noFailureTasks: "لا توجد مهام إخفاق في هذا التدقيق.",
    noTasksAssigned: "لم تُسنَد إليك أي مهام في هذا التدقيق.",
    allTasksComplete: "تم إكمال جميع المهام لهذا التدقيق!",
    nTasksMarkedDone: "{n} مهام تم وضع علامة الإنجاز عليها",
    nTasksFlagged: "{n} مهام تم تحديدها",
    showOtherTasks: "إظهار {n} مهام أخرى في هذا التدقيق",
    hideOtherTasks: "إخفاء {n} مهام أخرى في هذا التدقيق",
    myTasksN: "مهامي ({n})",
    allCaughtUp: "لا توجد مهام مفتوحة — كل شيء منجز!",
    notes: "ملاحظات",
    attachments: "المرفقات",
    categoryBreakdown: "تفصيل حسب الفئة",
    noGroupAssigned: "لم يتم تعيين مجموعة",
    noIndividualAssignee: "لم يتم تعيين شخص",
    group: "مجموعة",
    person: "شخص",
    searchPeopleGroups: "ابحث عن أشخاص أو مجموعات…",
    auditFinding: "ملاحظة التدقيق",
    description: "الوصف",
    noDescription: "لا يوجد وصف",
    comments: "التعليقات",
    addComment: "أضف تعليقًا…",
    attachFile: "إرفاق ملف",
    noTaskSpaces: "لم يتم العثور على مساحات مهام",
    noTaskSpacesHint: "تأكد من وجود تثبيت واحد للمهام على الأقل.",
    failedToLoad: "فشل تحميل المهام",
    noTasksFound: "لم يتم العثور على مهام",
    allCaughtUpPersonal: "لا توجد مهام مفتوحة — أنجزت كل شيء!",
    noCompletedTasks: "لا توجد مهام مكتملة بعد",
    auditEmptyHint: "أرسل عملية تدقيق باستخدام أداة التدقيق لرؤية النتائج هنا.",
    noMatches: "لا توجد نتائج",
    createFailedPrefix: "تعذّر إنشاء المهمة:",
    newTaskHeading: "مهمة جديدة",
    title: "العنوان",
    titlePlaceholder: "ما الذي يجب إنجازه؟",
    descriptionPlaceholder: "أضف تفاصيل (اختياري)",
    list: "القائمة",
    type: "النوع",
    newTypePlaceholder: "اسم النوع الجديد",
    noType: "— بلا نوع —",
    createNewType: "+ إنشاء نوع جديد…",
    dueDate: "تاريخ الاستحقاق",
    dueLabel: "الاستحقاق",
    overdueLabel: "متأخرة",
    priority: "الأولوية",
    normal: "عادية",
    medium: "متوسطة",
    high: "عالية",
    critical: "حرجة",
    recurring: "متكررة",
    cancel: "إلغاء",
    createTask: "إنشاء مهمة",
    creating: "جارٍ الإنشاء…",
    debug: "تصحيح الأخطاء",
    copy: "نسخ",
    clear: "مسح",
    hide: "إخفاء",
    copied: "تم النسخ!",
    copyFailed: "فشل النسخ",
    hideCompleted: "إخفاء المكتملة",
    showCompletedN: "إظهار المكتملة ({n})",
    markAsOpen: "وضع علامة مفتوحة",
    markAsDone: "وضع علامة منجزة",
    passing: "ناجح",
    failing: "غير ناجح",
    notScored: "غير مُقيَّم",
  },
};
