// Pilot i18n bundles for audit-widget. en_US is canonical; de_DE / ar_SA are
// the pilot translations. Missing keys fall back to en_US via makeT().
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    auditForm: "Audit Form",
    auditQuestions: "Audit Questions",
    clickToEdit: "Click to edit",
    yourNamePlaceholder: "Your name",
    loadingYourName: "Loading your name…",
    storeAuditorDetails: "Store & Auditor Details",
    searchStorePlaceholder: "Search {store}…",
    loading: "Loading…",
    auditDate: "Audit Date",
    auditorName: "Auditor Name",
    auditorNotes: "Auditor Notes",
    auditorNotesPlaceholder: "Context for this audit session…",
    enterYourName: "Please enter your name.",
    noQuestions: "No questions",
    pass: "Pass",
    fail: "Fail",
    na: "N/A",
    poor: "Poor",
    excellent: "Excellent",
    reset: "Reset",
    start: "Start",
    taskWillBeGenerated: "Task will be generated",
    noFailures: "No failures",
    allPassedOrNa: "All answered questions passed or were marked N/A.",
    assignTo: "Assign to",
    groups: "Groups",
    people: "People",
    searchPlaceholder: "Search…",
    auditSummary: "Audit Summary",
    passing: "Passing",
    failing: "Failing",
    date: "Date",
    tasksFlagged: "Tasks flagged",
    notes: "Notes",
    categoryBreakdown: "Category Breakdown",
    tasksToCreate: "Tasks to Create",
    working: "Working…",
    noPeopleFound: "No people found",
    noGroupsFound: "No groups found",
    submitCreateTasks: "Submit & Create Tasks",
    submitting: "Submitting…",
    auditSubmittedMsg: 'Audit submitted! "{name}" created with {n} tasks.',
    edit: "edit",
    loadingStore: "Loading {store}…",
    selectStore: "Select a {store}…",
    optional: "(optional)",
    attachPhotoFile: "Attach photo or file",
    loadingQuestions: "Loading questions…",
    beginAudit: "Begin Audit",
    nOfMAnswered: "{a} of {b} answered",
    setup: "Setup",
    prev: "Prev",
    viewOverview: "View Overview",
    next: "Next",
    stop: "Stop",
    addPhoto: "Add photo",
    nPts: "{n} pts",
    critical: "Critical",
    autoTask: "Auto-task",
    dueLabel: "Due:",
    immediately: "Immediately",
    unassigned: "— Unassigned —",
    withinDays: "Within {d}d",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} pts · {a} of {c} answered",
    nThreshold: "{n}% threshold",
    back: "Back",
  },
  de_DE: {
    auditForm: "Audit-Formular",
    auditQuestions: "Audit-Fragen",
    clickToEdit: "Zum Bearbeiten klicken",
    yourNamePlaceholder: "Ihr Name",
    loadingYourName: "Ihr Name wird geladen…",
    storeAuditorDetails: "Store- und Prüferdetails",
    searchStorePlaceholder: "{store} suchen…",
    loading: "Wird geladen…",
    auditDate: "Audit-Datum",
    auditorName: "Name des Prüfers",
    auditorNotes: "Prüfernotizen",
    auditorNotesPlaceholder: "Kontext für diese Audit-Sitzung…",
    enterYourName: "Bitte geben Sie Ihren Namen ein.",
    noQuestions: "Keine Fragen",
    pass: "Bestanden",
    fail: "Durchgefallen",
    na: "N/V",
    poor: "Schlecht",
    excellent: "Ausgezeichnet",
    reset: "Zurücksetzen",
    start: "Start",
    taskWillBeGenerated: "Aufgabe wird erstellt",
    noFailures: "Keine Mängel",
    allPassedOrNa: "Alle beantworteten Fragen wurden bestanden oder als N/V markiert.",
    assignTo: "Zuweisen an",
    groups: "Gruppen",
    people: "Personen",
    searchPlaceholder: "Suchen…",
    auditSummary: "Audit-Zusammenfassung",
    passing: "Bestanden",
    failing: "Nicht bestanden",
    date: "Datum",
    tasksFlagged: "Markierte Aufgaben",
    notes: "Notizen",
    categoryBreakdown: "Kategorienaufschlüsselung",
    tasksToCreate: "Zu erstellende Aufgaben",
    working: "Wird bearbeitet…",
    noPeopleFound: "Keine Personen gefunden",
    noGroupsFound: "Keine Gruppen gefunden",
    submitCreateTasks: "Senden & Aufgaben erstellen",
    submitting: "Wird gesendet…",
    auditSubmittedMsg: 'Audit gesendet! „{name}“ mit {n} Aufgaben erstellt.',
    edit: "bearbeiten",
    loadingStore: "{store} werden geladen…",
    selectStore: "{store} auswählen…",
    optional: "(optional)",
    attachPhotoFile: "Foto oder Datei anhängen",
    loadingQuestions: "Fragen werden geladen…",
    beginAudit: "Audit beginnen",
    nOfMAnswered: "{a} von {b} beantwortet",
    setup: "Einrichtung",
    prev: "Zurück",
    viewOverview: "Übersicht anzeigen",
    next: "Weiter",
    stop: "Stopp",
    addPhoto: "Foto hinzufügen",
    nPts: "{n} Pkt.",
    critical: "Kritisch",
    autoTask: "Auto-Aufgabe",
    dueLabel: "Fällig:",
    immediately: "Sofort",
    unassigned: "— Nicht zugewiesen —",
    withinDays: "Innerhalb {d} T",
    auditor: "Prüfer",
    scoreSummary: "{e} / {t} Pkt. · {a} von {c} beantwortet",
    nThreshold: "{n}% Schwelle",
    back: "Zurück",
  },
  ar_SA: {
    auditForm: "نموذج التدقيق",
    auditQuestions: "أسئلة التدقيق",
    clickToEdit: "انقر للتعديل",
    yourNamePlaceholder: "اسمك",
    loadingYourName: "جارٍ تحميل اسمك…",
    storeAuditorDetails: "تفاصيل المتجر والمدقّق",
    searchStorePlaceholder: "ابحث في {store}…",
    loading: "جارٍ التحميل…",
    auditDate: "تاريخ التدقيق",
    auditorName: "اسم المدقّق",
    auditorNotes: "ملاحظات المدقّق",
    auditorNotesPlaceholder: "سياق جلسة التدقيق هذه…",
    enterYourName: "الرجاء إدخال اسمك.",
    noQuestions: "لا توجد أسئلة",
    pass: "ناجح",
    fail: "راسب",
    na: "غير منطبق",
    poor: "ضعيف",
    excellent: "ممتاز",
    reset: "إعادة تعيين",
    start: "بدء",
    taskWillBeGenerated: "سيتم إنشاء مهمة",
    noFailures: "لا توجد إخفاقات",
    allPassedOrNa: "نجحت جميع الأسئلة المُجابة أو تم تحديدها كغير منطبقة.",
    assignTo: "إسناد إلى",
    groups: "المجموعات",
    people: "الأشخاص",
    searchPlaceholder: "بحث…",
    auditSummary: "ملخص التدقيق",
    passing: "ناجح",
    failing: "غير ناجح",
    date: "التاريخ",
    tasksFlagged: "المهام المُحدَّدة",
    notes: "ملاحظات",
    categoryBreakdown: "تفصيل حسب الفئة",
    tasksToCreate: "المهام المطلوب إنشاؤها",
    working: "جارٍ العمل…",
    noPeopleFound: "لم يتم العثور على أشخاص",
    noGroupsFound: "لم يتم العثور على مجموعات",
    submitCreateTasks: "إرسال وإنشاء المهام",
    submitting: "جارٍ الإرسال…",
    auditSubmittedMsg: 'تم إرسال التدقيق! تم إنشاء «{name}» مع {n} مهام.',
    edit: "تعديل",
    loadingStore: "جارٍ تحميل {store}…",
    selectStore: "اختر {store}…",
    optional: "(اختياري)",
    attachPhotoFile: "إرفاق صورة أو ملف",
    loadingQuestions: "جارٍ تحميل الأسئلة…",
    beginAudit: "بدء التدقيق",
    nOfMAnswered: "{a} من {b} تمت الإجابة عليها",
    setup: "الإعداد",
    prev: "السابق",
    viewOverview: "عرض النظرة العامة",
    next: "التالي",
    stop: "إيقاف",
    addPhoto: "إضافة صورة",
    nPts: "{n} نقطة",
    critical: "حرج",
    autoTask: "مهمة تلقائية",
    dueLabel: "الاستحقاق:",
    immediately: "فورًا",
    unassigned: "— غير مُسنَد —",
    withinDays: "خلال {d} يوم",
    auditor: "المدقّق",
    scoreSummary: "{e} / {t} نقطة · {a} من {c} تمت الإجابة عليها",
    nThreshold: "عتبة {n}%",
    back: "رجوع",
  },
};
