// Pilot i18n bundles for audit-widget. en_US is canonical; de_DE / ar_SA are
// the pilot translations. Missing keys fall back to en_US via makeT().
import { Bundles } from "../shared/i18n";

export const STRINGS: Bundles = {
  en_US: {
    auditForm: "Audit Form",
    auditQuestions: "Audit Questions",
    clickToEdit: "Click to edit",
    yourNamePlaceholder: "Your name",
    loadingYourName: "Loading your name…",
    storeAuditorDetails: "Store & Auditor Details",
    searchStorePlaceholder: "Search {store}…",
    loading: "Loading…",
    auditDate: "Audit Date",
    auditorName: "Auditor Name",
    auditorNotes: "Auditor Notes",
    auditorNotesPlaceholder: "Context for this audit session…",
    enterYourName: "Please enter your name.",
    noQuestions: "No questions",
    pass: "Pass",
    fail: "Fail",
    na: "N/A",
    poor: "Poor",
    excellent: "Excellent",
    reset: "Reset",
    start: "Start",
    taskWillBeGenerated: "Task will be generated",
    noFailures: "No failures",
    allPassedOrNa: "All answered questions passed or were marked N/A.",
    assignTo: "Assign to",
    groups: "Groups",
    people: "People",
    searchPlaceholder: "Search…",
    auditSummary: "Audit Summary",
    passing: "Passing",
    failing: "Failing",
    date: "Date",
    tasksFlagged: "Tasks flagged",
    notes: "Notes",
    categoryBreakdown: "Category Breakdown",
    tasksToCreate: "Tasks to Create",
    working: "Working…",
    noPeopleFound: "No people found",
    noGroupsFound: "No groups found",
    submitCreateTasks: "Submit & Create Tasks",
    submitting: "Submitting…",
    auditSubmittedMsg: 'Audit submitted! "{name}" created with {n} tasks.',
    edit: "edit",
    loadingStore: "Loading {store}…",
    selectStore: "Select a {store}…",
    optional: "(optional)",
    attachPhotoFile: "Attach photo or file",
    loadingQuestions: "Loading questions…",
    beginAudit: "Begin Audit",
    nOfMAnswered: "{a} of {b} answered",
    setup: "Setup",
    prev: "Prev",
    viewOverview: "View Overview",
    next: "Next",
    stop: "Stop",
    addPhoto: "Add photo",
    nPts: "{n} pts",
    critical: "Critical",
    autoTask: "Auto-task",
    dueLabel: "Due:",
    immediately: "Immediately",
    unassigned: "— Unassigned —",
    withinDays: "Within {d}d",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} pts · {a} of {c} answered",
    nThreshold: "{n}% threshold",
    back: "Back",
  },
  de_DE: {
    auditForm: "Audit-Formular",
    auditQuestions: "Audit-Fragen",
    clickToEdit: "Zum Bearbeiten klicken",
    yourNamePlaceholder: "Ihr Name",
    loadingYourName: "Ihr Name wird geladen…",
    storeAuditorDetails: "Store- und Prüferdetails",
    searchStorePlaceholder: "{store} suchen…",
    loading: "Wird geladen…",
    auditDate: "Audit-Datum",
    auditorName: "Name des Prüfers",
    auditorNotes: "Prüfernotizen",
    auditorNotesPlaceholder: "Kontext für diese Audit-Sitzung…",
    enterYourName: "Bitte geben Sie Ihren Namen ein.",
    noQuestions: "Keine Fragen",
    pass: "Bestanden",
    fail: "Durchgefallen",
    na: "N/V",
    poor: "Schlecht",
    excellent: "Ausgezeichnet",
    reset: "Zurücksetzen",
    start: "Start",
    taskWillBeGenerated: "Aufgabe wird erstellt",
    noFailures: "Keine Mängel",
    allPassedOrNa: "Alle beantworteten Fragen wurden bestanden oder als N/V markiert.",
    assignTo: "Zuweisen an",
    groups: "Gruppen",
    people: "Personen",
    searchPlaceholder: "Suchen…",
    auditSummary: "Audit-Zusammenfassung",
    passing: "Bestanden",
    failing: "Nicht bestanden",
    date: "Datum",
    tasksFlagged: "Markierte Aufgaben",
    notes: "Notizen",
    categoryBreakdown: "Kategorienaufschlüsselung",
    tasksToCreate: "Zu erstellende Aufgaben",
    working: "Wird bearbeitet…",
    noPeopleFound: "Keine Personen gefunden",
    noGroupsFound: "Keine Gruppen gefunden",
    submitCreateTasks: "Senden & Aufgaben erstellen",
    submitting: "Wird gesendet…",
    auditSubmittedMsg: 'Audit gesendet! „{name}“ mit {n} Aufgaben erstellt.',
    edit: "bearbeiten",
    loadingStore: "{store} werden geladen…",
    selectStore: "{store} auswählen…",
    optional: "(optional)",
    attachPhotoFile: "Foto oder Datei anhängen",
    loadingQuestions: "Fragen werden geladen…",
    beginAudit: "Audit beginnen",
    nOfMAnswered: "{a} von {b} beantwortet",
    setup: "Einrichtung",
    prev: "Zurück",
    viewOverview: "Übersicht anzeigen",
    next: "Weiter",
    stop: "Stopp",
    addPhoto: "Foto hinzufügen",
    nPts: "{n} Pkt.",
    critical: "Kritisch",
    autoTask: "Auto-Aufgabe",
    dueLabel: "Fällig:",
    immediately: "Sofort",
    unassigned: "— Nicht zugewiesen —",
    withinDays: "Innerhalb {d} T",
    auditor: "Prüfer",
    scoreSummary: "{e} / {t} Pkt. · {a} von {c} beantwortet",
    nThreshold: "{n}% Schwelle",
    back: "Zurück",
  },
  ar_SA: {
    auditForm: "نموذج التدقيق",
    auditQuestions: "أسئلة التدقيق",
    clickToEdit: "انقر للتعديل",
    yourNamePlaceholder: "اسمك",
    loadingYourName: "جارٍ تحميل اسمك…",
    storeAuditorDetails: "تفاصيل المتجر والمدقّق",
    searchStorePlaceholder: "ابحث في {store}…",
    loading: "جارٍ التحميل…",
    auditDate: "تاريخ التدقيق",
    auditorName: "اسم المدقّق",
    auditorNotes: "ملاحظات المدقّق",
    auditorNotesPlaceholder: "سياق جلسة التدقيق هذه…",
    enterYourName: "الرجاء إدخال اسمك.",
    noQuestions: "لا توجد أسئلة",
    pass: "ناجح",
    fail: "راسب",
    na: "غير منطبق",
    poor: "ضعيف",
    excellent: "ممتاز",
    reset: "إعادة تعيين",
    start: "بدء",
    taskWillBeGenerated: "سيتم إنشاء مهمة",
    noFailures: "لا توجد إخفاقات",
    allPassedOrNa: "نجحت جميع الأسئلة المُجابة أو تم تحديدها كغير منطبقة.",
    assignTo: "إسناد إلى",
    groups: "المجموعات",
    people: "الأشخاص",
    searchPlaceholder: "بحث…",
    auditSummary: "ملخص التدقيق",
    passing: "ناجح",
    failing: "غير ناجح",
    date: "التاريخ",
    tasksFlagged: "المهام المُحدَّدة",
    notes: "ملاحظات",
    categoryBreakdown: "تفصيل حسب الفئة",
    tasksToCreate: "المهام المطلوب إنشاؤها",
    working: "جارٍ العمل…",
    noPeopleFound: "لم يتم العثور على أشخاص",
    noGroupsFound: "لم يتم العثور على مجموعات",
    submitCreateTasks: "إرسال وإنشاء المهام",
    submitting: "جارٍ الإرسال…",
    auditSubmittedMsg: 'تم إرسال التدقيق! تم إنشاء «{name}» مع {n} مهام.',
    edit: "تعديل",
    loadingStore: "جارٍ تحميل {store}…",
    selectStore: "اختر {store}…",
    optional: "(اختياري)",
    attachPhotoFile: "إرفاق صورة أو ملف",
    loadingQuestions: "جارٍ تحميل الأسئلة…",
    beginAudit: "بدء التدقيق",
    nOfMAnswered: "{a} من {b} تمت الإجابة عليها",
    setup: "الإعداد",
    prev: "السابق",
    viewOverview: "عرض النظرة العامة",
    next: "التالي",
    stop: "إيقاف",
    addPhoto: "إضافة صورة",
    nPts: "{n} نقطة",
    critical: "حرج",
    autoTask: "مهمة تلقائية",
    dueLabel: "الاستحقاق:",
    immediately: "فورًا",
    unassigned: "— غير مُسنَد —",
    withinDays: "خلال {d} يوم",
    auditor: "المدقّق",
    scoreSummary: "{e} / {t} نقطة · {a} من {c} تمت الإجابة عليها",
    nThreshold: "عتبة {n}%",
    back: "رجوع",
  },
  es_ES: {
    auditForm: "Formulario de auditoría",
    auditQuestions: "Preguntas sobre auditoría",
    clickToEdit: "Haz clic para editar",
    yourNamePlaceholder: "Tu nombre",
    loadingYourName: "Cargando tu nombre...",
    storeAuditorDetails: "Detalles de la Tienda y el Auditor",
    searchStorePlaceholder: "Registrar {store}...",
    loading: "Cargando...",
    auditDate: "Fecha de la auditoría",
    auditorName: "Nombre del auditor",
    auditorNotes: "Notas del auditor",
    auditorNotesPlaceholder: "Contexto de esta sesión de auditoría...",
    enterYourName: "Por favor, introduzca su nombre.",
    noQuestions: "Sin preguntas",
    pass: "Paso",
    fail: "Fallo",
    na: "N/A",
    poor: "Pobre",
    excellent: "Excelente",
    reset: "Reinicio",
    start: "Comienzo",
    taskWillBeGenerated: "Se generará la tarea",
    noFailures: "Sin fallos",
    allPassedOrNa: "Todas las preguntas respondidas aprobaron o fueron marcadas como N/A.",
    assignTo: "Asignar a",
    groups: "Grupos",
    people: "Personas",
    searchPlaceholder: "Buscar...",
    auditSummary: "Resumen de la auditoría",
    passing: "Fallecimiento",
    failing: "Fracaso",
    date: "Fecha",
    tasksFlagged: "Tareas marcadas",
    notes: "Notas",
    categoryBreakdown: "Desglose por categorías",
    tasksToCreate: "Tareas para crear",
    working: "Trabajando...",
    noPeopleFound: "No se encontró a nadie",
    noGroupsFound: "No se han encontrado grupos",
    submitCreateTasks: "Enviar y crear tareas",
    submitting: "Entregando...",
    auditSubmittedMsg: "¡Auditoría enviada! &#34;{name}&#34; creado con {n} tareas.",
    edit: "editar",
    loadingStore: "Cargando {store}...",
    selectStore: "Elige un {store}...",
    optional: "(opcional)",
    attachPhotoFile: "Adjuntar foto o archivo",
    loadingQuestions: "Cargando preguntas...",
    beginAudit: "Inicio de la auditoría",
    nOfMAnswered: "{a} de {b} respondido",
    setup: "Configuración",
    prev: "Anterior",
    viewOverview: "Ver visión general",
    next: "Siguiente",
    stop: "¡Para",
    addPhoto: "Añadir foto",
    nPts: "{n} pacientes",
    critical: "Crítica",
    autoTask: "Auto-tarea",
    dueLabel: "Fecha límite:",
    immediately: "Inmediatamente",
    unassigned: "— Sin asignar —",
    withinDays: "Dentro de {d}",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} puntos · {a} de {c} respondió",
    nThreshold: "umbral del {n}%",
    back: "Atrás",
  },
  fr_FR: {
    auditForm: "Formulaire d’audit",
    auditQuestions: "Questions d’audit",
    clickToEdit: "Cliquez pour modifier",
    yourNamePlaceholder: "Ton nom",
    loadingYourName: "Chargement de ton nom...",
    storeAuditorDetails: "Détails du magasin et de l’auditeur",
    searchStorePlaceholder: "Fouillez {store}...",
    loading: "Chargement...",
    auditDate: "Date de l’audit",
    auditorName: "Nom de l’auditeur",
    auditorNotes: "Notes de l’auditeur",
    auditorNotesPlaceholder: "Contexte pour cette session d’audit...",
    enterYourName: "Veuillez entrer votre nom.",
    noQuestions: "Pas de questions",
    pass: "Pass",
    fail: "Échec",
    na: "N/A",
    poor: "Pauvre",
    excellent: "Excellent",
    reset: "Réinitialisation",
    start: "Début",
    taskWillBeGenerated: "La tâche sera générée",
    noFailures: "Aucune défaillance",
    allPassedOrNa: "Toutes les questions répondues ont été réussies ou ont été marquées N/A.",
    assignTo: "Assigner à",
    groups: "Groupes",
    people: "Personnalités",
    searchPlaceholder: "Chercher...",
    auditSummary: "Résumé de l’audit",
    passing: "Passage",
    failing: "Échec",
    date: "Date",
    tasksFlagged: "Tâches signalées",
    notes: "Notes",
    categoryBreakdown: "Répartition par catégorie",
    tasksToCreate: "Tâches à créer",
    working: "Travailler...",
    noPeopleFound: "Aucune personne trouvée",
    noGroupsFound: "Aucun groupe trouvé",
    submitCreateTasks: "Soumettre et créer des tâches",
    submitting: "Soumettre...",
    auditSubmittedMsg: "Audit soumis ! « {name} » créé avec {n} tâches.",
    edit: "Édition",
    loadingStore: "Chargement {store}...",
    selectStore: "Sélectionnez un {store}...",
    optional: "(optionnel)",
    attachPhotoFile: "Joindre photo ou fichier",
    loadingQuestions: "Questions de chargement...",
    beginAudit: "Début de l’audit",
    nOfMAnswered: "{a} de {b} répondu",
    setup: "Mise en place",
    prev: "Précédent",
    viewOverview: "Voir l’aperçu",
    next: "Suivant",
    stop: "Arrête",
    addPhoto: "Ajouter la photo",
    nPts: "{n} PTS",
    critical: "Critique",
    autoTask: "Auto-tâche",
    dueLabel: "À rendre :",
    immediately: "Immédiatement",
    unassigned: "— Non assigné —",
    withinDays: "Dans {d}",
    auditor: "Auditeur",
    scoreSummary: "{e} / {t} pts · {a} de {c} répondu",
    nThreshold: "Seuil de {n} %",
    back: "Retour",
  },
  nl_NL: {
    auditForm: "Auditformulier",
    auditQuestions: "Auditvragen",
    clickToEdit: "Klik om te bewerken",
    yourNamePlaceholder: "Jouw naam",
    loadingYourName: "Laad je naam...",
    storeAuditorDetails: "Winkel- en auditorgegevens",
    searchStorePlaceholder: "Zoek {store}...",
    loading: "Laden...",
    auditDate: "Datum van de audit",
    auditorName: "Naam van de auditor",
    auditorNotes: "Aantekeningen van de Auditor",
    auditorNotesPlaceholder: "Context voor deze auditsessie...",
    enterYourName: "Voer alstublieft uw naam in.",
    noQuestions: "Geen vragen",
    pass: "Pas",
    fail: "Mislukt",
    na: "N.v.t.",
    poor: "Arme",
    excellent: "Uitstekend",
    reset: "Reset",
    start: "Start",
    taskWillBeGenerated: "De taak wordt gegenereerd",
    noFailures: "Geen mislukkingen",
    allPassedOrNa: "Alle beantwoorde vragen zijn geslaagd of werden als N.v.t. gemarkeerd.",
    assignTo: "Toewijzen aan",
    groups: "Groepen",
    people: "Mensen",
    searchPlaceholder: "Zoek...",
    auditSummary: "Auditsamenvatting",
    passing: "Overlijden",
    failing: "Falen",
    date: "Datum",
    tasksFlagged: "Taken gemarkeerd",
    notes: "Noten",
    categoryBreakdown: "Categorie-opsplitsing",
    tasksToCreate: "Taken om te creëren",
    working: "Aan het werk...",
    noPeopleFound: "Geen mensen gevonden",
    noGroupsFound: "Geen groepen gevonden",
    submitCreateTasks: "Taken indienen en aanmaken",
    submitting: "Indienen...",
    auditSubmittedMsg: "Audit ingediend! &#34;{name}&#34; gemaakt met {n} taken.",
    edit: "Bewerking",
    loadingStore: "Laad {store}...",
    selectStore: "Kies een {store}...",
    optional: "(optioneel)",
    attachPhotoFile: "Voeg foto of bestand bij",
    loadingQuestions: "Vragen laden...",
    beginAudit: "Start met audit",
    nOfMAnswered: "{a} van {b} antwoordde",
    setup: "Opstelling",
    prev: "Vorige",
    viewOverview: "Bekijk Overzicht",
    next: "Volgende",
    stop: "Stop",
    addPhoto: "Foto toevoegen",
    nPts: "{n} patiënten",
    critical: "Kritisch",
    autoTask: "Auto-task",
    dueLabel: "Deadline:",
    immediately: "Onmiddellijk",
    unassigned: "— Niet toegewezen —",
    withinDays: "Binnen {d}d",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} pts · {a} van {c} antwoordde",
    nThreshold: "{n}% drempel",
    back: "Achteruit",
  },
  zh_CN: {
    auditForm: "审计表格",
    auditQuestions: "审计问题",
    clickToEdit: "点击编辑",
    yourNamePlaceholder: "你的名字",
    loadingYourName: "加载你的名字......",
    storeAuditorDetails: "门店与审计员详情",
    searchStorePlaceholder: "搜查{store}......",
    loading: "加载中......",
    auditDate: "审计日期",
    auditorName: "审计员姓名",
    auditorNotes: "审计员笔记",
    auditorNotesPlaceholder: "这次审计会议的背景......",
    enterYourName: "请输入您的名字。",
    noQuestions: "没有任何疑问",
    pass: "山口",
    fail: "失败",
    na: "无",
    poor: "可怜",
    excellent: "太好了",
    reset: "重置",
    start: "开始",
    taskWillBeGenerated: "任务将被生成",
    noFailures: "没有故障",
    allPassedOrNa: "所有已答题或均已通过或标记为不适用。",
    assignTo: "分配到",
    groups: "团体",
    people: "人物",
    searchPlaceholder: "搜索......",
    auditSummary: "审计摘要",
    passing: "通过",
    failing: "失败",
    date: "日期",
    tasksFlagged: "标记任务",
    notes: "注释",
    categoryBreakdown: "类别分类",
    tasksToCreate: "需要创建的任务",
    working: "工作......",
    noPeopleFound: "未发现任何人",
    noGroupsFound: "未找到组",
    submitCreateTasks: "提交与创建任务",
    submitting: "臣服......",
    auditSubmittedMsg: "审计提交！“{name}”由{n}任务创建。",
    edit: "编辑",
    loadingStore: "正在加载{store}......",
    selectStore: "选择一个{store}......",
    optional: "（可选）",
    attachPhotoFile: "附上照片或文件",
    loadingQuestions: "加载问题......",
    beginAudit: "开始审计",
    nOfMAnswered: "{a} {b}回答",
    setup: "设置",
    prev: "前期",
    viewOverview: "查看概览",
    next: "下一个",
    stop: "停下",
    addPhoto: "添加照片",
    nPts: "{n}点",
    critical: "批判",
    autoTask: "自动任务",
    dueLabel: "到期：",
    immediately: "立刻",
    unassigned: "——未分配——",
    withinDays: "在{d}d",
    auditor: "审计长",
    scoreSummary: "{e} / {t}分·{a}人回答{c}",
    nThreshold: "{n}%门槛",
    back: "返回",
  },
  ja_JP: {
    auditForm: "監査フォーム",
    auditQuestions: "監査に関する質問",
    clickToEdit: "編集",
    yourNamePlaceholder: "君の名前",
    loadingYourName: "名前を読み込みます...",
    storeAuditorDetails: "店舗および監査人詳細",
    searchStorePlaceholder: "{store}を捜索...",
    loading: "読み込み中...",
    auditDate: "監査日",
    auditorName: "監査官名",
    auditorNotes: "監査人ノート",
    auditorNotesPlaceholder: "この監査セッションの背景は...",
    enterYourName: "お名前を入力してください。",
    noQuestions: "質問はなし",
    pass: "パス",
    fail: "失敗",
    na: "該当なし",
    poor: "かわいそうに",
    excellent: "素晴らしい",
    reset: "リセット",
    start: "開始",
    taskWillBeGenerated: "タスクが生成されます",
    noFailures: "失敗はありません",
    allPassedOrNa: "すべての問題に答えた問題は合格または該当なしとマークされていました。",
    assignTo: "割り当て",
    groups: "グループ",
    people: "人々",
    searchPlaceholder: "捜索...",
    auditSummary: "監査概要",
    passing: "パス",
    failing: "失敗",
    date: "日付",
    tasksFlagged: "フラグが立ったタスク",
    notes: "注記",
    categoryBreakdown: "カテゴリー内訳",
    tasksToCreate: "作成すべきタスク",
    working: "仕事中...",
    noPeopleFound: "誰も見つかりませんでした",
    noGroupsFound: "グループは見つかりませんでした",
    submitCreateTasks: "タスクの送信と作成",
    submitting: "服従...",
    auditSubmittedMsg: "監査提出!「{name}」は{n}タスクで作成されました。",
    edit: "編集",
    loadingStore: "読み込み{store}...",
    selectStore: "{store}を選んで...",
    optional: "(任意)",
    attachPhotoFile: "写真またはファイルを添付してください",
    loadingQuestions: "質問を読み込み中...",
    beginAudit: "監査開始",
    nOfMAnswered: "{a}{b}が答えた",
    setup: "セットアップ",
    prev: "前回",
    viewOverview: "概要を見る",
    next: "次",
    stop: "やめて",
    addPhoto: "写真を追加",
    nPts: "{n}点",
    critical: "重要な点",
    autoTask: "オートタスク",
    dueLabel: "期限:",
    immediately: "すぐに",
    unassigned: "— 未割り当て —",
    withinDays: "{d}d",
    auditor: "監査官",
    scoreSummary: "{e} / {t} pts ·{a}{c}が答えた",
    nThreshold: "{n}%の閾値",
    back: "戻る",
  },
  th_TH: {
    auditForm: "แบบฟอร์มการตรวจสอบ",
    auditQuestions: "คําถามเกี่ยวกับการตรวจสอบ",
    clickToEdit: "คลิกเพื่อแก้ไข",
    yourNamePlaceholder: "ชื่อของคุณ",
    loadingYourName: "กําลังโหลดชื่อของคุณ...",
    storeAuditorDetails: "รายละเอียดร้านค้าและผู้ตรวจสอบบัญชี",
    searchStorePlaceholder: "ค้นหา{store}...",
    loading: "กําลังโหลด...",
    auditDate: "วันที่ตรวจสอบ",
    auditorName: "ชื่อผู้สอบบัญชี",
    auditorNotes: "หมายเหตุผู้สอบบัญชี",
    auditorNotesPlaceholder: "บริบทสําหรับเซสชันการตรวจสอบนี้...",
    enterYourName: "กรุณากรอกชื่อของคุณ",
    noQuestions: "ไม่มีคําถาม",
    pass: "ผ่าน",
    fail: "ล้มเหลว",
    na: "ไม่มี",
    poor: "แย่",
    excellent: "ดีเยี่ยม",
    reset: "รีเซ็ต",
    start: "เริ่มต้น",
    taskWillBeGenerated: "งานจะถูกสร้างขึ้น",
    noFailures: "ไม่มีความล้มเหลว",
    allPassedOrNa: "คําถามที่ตอบทั้งหมดผ่านหรือถูกทําเครื่องหมายว่า N/A",
    assignTo: "มอบหมายให้",
    groups: "กลุ่ม",
    people: "บุคลากร",
    searchPlaceholder: "ค้นหา...",
    auditSummary: "สรุปการตรวจสอบ",
    passing: "ผ่าน",
    failing: "ล้มเหลว",
    date: "วันที่",
    tasksFlagged: "งานที่ถูกตั้งค่าสถานะ",
    notes: "หมายเหตุ",
    categoryBreakdown: "รายละเอียดหมวดหมู่",
    tasksToCreate: "งานที่ต้องสร้าง",
    working: "ทํางาน...",
    noPeopleFound: "ไม่พบบุคคล",
    noGroupsFound: "ไม่พบกลุ่ม",
    submitCreateTasks: "ส่งและสร้างงาน",
    submitting: "กําลังส่ง...",
    auditSubmittedMsg: "ส่งการตรวจสอบแล้ว! &#34;{name}&#34; ที่สร้างขึ้นด้วยงาน{n}",
    edit: "แก้ไข",
    loadingStore: "กําลังโหลด{store}...",
    selectStore: "เลือก{store}...",
    optional: "(ไม่บังคับ)",
    attachPhotoFile: "แนบรูปภาพหรือไฟล์",
    loadingQuestions: "กําลังโหลดคําถาม...",
    beginAudit: "เริ่มการตรวจสอบ",
    nOfMAnswered: "{a} จาก {b} ตอบ",
    setup: "การติดตั้ง",
    prev: "ก่อนหน้า",
    viewOverview: "ดูภาพรวม",
    next: "ต่อไป",
    stop: "หยุด",
    addPhoto: "เพิ่มรูปภาพ",
    nPts: "{n} คะแนน",
    critical: "วิกฤต",
    autoTask: "งานอัตโนมัติ",
    dueLabel: "ครบกําหนด:",
    immediately: "ทันที",
    unassigned: "- ไม่ได้มอบหมาย -",
    withinDays: "ภายใน {d} วัน",
    auditor: "ผู้สอบบัญชี",
    scoreSummary: "{e} / {t} คะแนน · {a} จาก {c} ตอบ",
    nThreshold: "เกณฑ์ {n}%",
    back: "ย้อนกลับ",
  },
  es_MX: {
    auditForm: "Formulario de auditoría",
    auditQuestions: "Preguntas sobre auditoría",
    clickToEdit: "Haz clic para editar",
    yourNamePlaceholder: "Tu nombre",
    loadingYourName: "Cargando tu nombre...",
    storeAuditorDetails: "Detalles de la Tienda y el Auditor",
    searchStorePlaceholder: "Registrar {store}...",
    loading: "Cargando...",
    auditDate: "Fecha de la auditoría",
    auditorName: "Nombre del auditor",
    auditorNotes: "Notas del auditor",
    auditorNotesPlaceholder: "Contexto de esta sesión de auditoría...",
    enterYourName: "Por favor, introduzca su nombre.",
    noQuestions: "Sin preguntas",
    pass: "Paso",
    fail: "Fallo",
    na: "N/A",
    poor: "Pobre",
    excellent: "Excelente",
    reset: "Reinicio",
    start: "Comienzo",
    taskWillBeGenerated: "Se generará la tarea",
    noFailures: "Sin fallos",
    allPassedOrNa: "Todas las preguntas respondidas aprobaron o fueron marcadas como N/A.",
    assignTo: "Asignar a",
    groups: "Grupos",
    people: "Personas",
    searchPlaceholder: "Buscar...",
    auditSummary: "Resumen de la auditoría",
    passing: "Fallecimiento",
    failing: "Fracaso",
    date: "Fecha",
    tasksFlagged: "Tareas marcadas",
    notes: "Notas",
    categoryBreakdown: "Desglose por categorías",
    tasksToCreate: "Tareas para crear",
    working: "Trabajando...",
    noPeopleFound: "No se encontró a nadie",
    noGroupsFound: "No se han encontrado grupos",
    submitCreateTasks: "Enviar y crear tareas",
    submitting: "Entregando...",
    auditSubmittedMsg: "¡Auditoría enviada! &#34;{name}&#34; creado con {n} tareas.",
    edit: "editar",
    loadingStore: "Cargando {store}...",
    selectStore: "Elige un {store}...",
    optional: "(opcional)",
    attachPhotoFile: "Adjuntar foto o archivo",
    loadingQuestions: "Cargando preguntas...",
    beginAudit: "Inicio de la auditoría",
    nOfMAnswered: "{a} de {b} respondido",
    setup: "Configuración",
    prev: "Anterior",
    viewOverview: "Ver visión general",
    next: "Siguiente",
    stop: "¡Para",
    addPhoto: "Añadir foto",
    nPts: "{n} pacientes",
    critical: "Crítica",
    autoTask: "Auto-tarea",
    dueLabel: "Fecha límite:",
    immediately: "Inmediatamente",
    unassigned: "— Sin asignar —",
    withinDays: "Dentro de {d}",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} puntos · {a} de {c} respondió",
    nThreshold: "umbral del {n}%",
    back: "Atrás",
  },
  vi_VN: {
    auditForm: "Biểu mẫu kiểm toán",
    auditQuestions: "Câu hỏi kiểm toán",
    clickToEdit: "Bấm để chỉnh sửa",
    yourNamePlaceholder: "Tên của bạn",
    loadingYourName: "Đang tải tên của bạn...",
    storeAuditorDetails: "Chi tiết cửa hàng & kiểm toán viên",
    searchStorePlaceholder: "Tìm kiếm {store}...",
    loading: "Đang tải...",
    auditDate: "Ngày kiểm toán",
    auditorName: "Tên kiểm toán viên",
    auditorNotes: "Ghi chú kiểm toán viên",
    auditorNotesPlaceholder: "Bối cảnh cho phiên kiểm toán này...",
    enterYourName: "Vui lòng nhập tên của bạn.",
    noQuestions: "Không có câu hỏi",
    pass: "Vượt qua",
    fail: "Không thành công",
    na: "Không có",
    poor: "Nghèo",
    excellent: "Thông minh",
    reset: "Xóa và làm lại",
    start: "Bắt đầu",
    taskWillBeGenerated: "Nhiệm vụ sẽ được tạo",
    noFailures: "Không thất bại",
    allPassedOrNa: "Tất cả các câu hỏi đã trả lời đều đạt hoặc được đánh dấu N/A.",
    assignTo: "Gán cho",
    groups: "Nhóm",
    people: "Con người",
    searchPlaceholder: "Tìm kiếm...",
    auditSummary: "Tóm tắt kiểm toán",
    passing: "Vượt qua",
    failing: "Không thành công",
    date: "Ngày",
    tasksFlagged: "Nhiệm vụ được gắn cờ",
    notes: "Ghi chú",
    categoryBreakdown: "Phân tích danh mục",
    tasksToCreate: "Nhiệm vụ cần tạo",
    working: "Đang làm việc...",
    noPeopleFound: "Không tìm thấy người",
    noGroupsFound: "Không tìm thấy nhóm nào",
    submitCreateTasks: "Gửi và tạo nhiệm vụ",
    submitting: "Đang gửi...",
    auditSubmittedMsg: "Kiểm toán đã gửi! &#34;{name}&#34; được tạo ra với các nhiệm vụ {n}.",
    edit: "Chỉnh sửa",
    loadingStore: "Đang tải {store}...",
    selectStore: "Chọn một {store}...",
    optional: "(tùy chọn)",
    attachPhotoFile: "Đính kèm ảnh hoặc tệp",
    loadingQuestions: "Đang tải câu hỏi...",
    beginAudit: "Bắt đầu kiểm tra",
    nOfMAnswered: "{a} của {b} đã trả lời",
    setup: "Thành lập",
    prev: "Trước",
    viewOverview: "Xem tổng quan",
    next: "Kế tiếp",
    stop: "Dừng lại",
    addPhoto: "Thêm ảnh",
    nPts: "{n} điểm",
    critical: "Quan trọng",
    autoTask: "Tự động tác vụ",
    dueLabel: "Đến hạn:",
    immediately: "Ngay lập tức",
    unassigned: "- Chưa được chỉ định -",
    withinDays: "Trong vòng {d}",
    auditor: "Kiểm toán viên",
    scoreSummary: "{e} / {t} điểm · {a} của {c} đã trả lời",
    nThreshold: "Ngưỡng {n}%",
    back: "Quay lại",
  },
  ko_KR: {
    auditForm: "감사 양식",
    auditQuestions: "감사 질문",
    clickToEdit: "클릭하여 편집하기",
    yourNamePlaceholder: "네 이름",
    loadingYourName: "이름 불러오는 중...",
    storeAuditorDetails: "매장 및 감사인 상세 정보",
    searchStorePlaceholder: "수색{store}...",
    loading: "로딩 중...",
    auditDate: "감사일",
    auditorName: "감사인 이름",
    auditorNotes: "감사관 노트",
    auditorNotesPlaceholder: "이번 감사 세션의 배경...",
    enterYourName: "이름을 입력해 주세요.",
    noQuestions: "질문 없어",
    pass: "고개",
    fail: "실패",
    na: "해당 없음",
    poor: "불쌍하네요",
    excellent: "훌륭해",
    reset: "리셋",
    start: "시작",
    taskWillBeGenerated: "과제가 생성될 것입니다",
    noFailures: "고장 없음",
    allPassedOrNa: "모든 답변이 합격되었거나 해당 문제로 표시되지 않았습니다.",
    assignTo: "할당",
    groups: "그룹",
    people: "인물",
    searchPlaceholder: "수색...",
    auditSummary: "감사 요약",
    passing: "통과",
    failing: "실패",
    date: "날짜",
    tasksFlagged: "과제 표시됨",
    notes: "주석",
    categoryBreakdown: "카테고리 분류",
    tasksToCreate: "만들 과제",
    working: "일하는 중...",
    noPeopleFound: "사람 찾지 못했다",
    noGroupsFound: "그룹 찾기 어떠",
    submitCreateTasks: "제출 및 작업 생성",
    submitting: "복종...",
    auditSubmittedMsg: "감사 제출! &#34;{name}&#34;은 {n} 작업으로 생성됩니다.",
    edit: "수정",
    loadingStore: "로딩 {store}...",
    selectStore: "{store} 선택하세요...",
    optional: "(선택 사항)",
    attachPhotoFile: "사진이나 파일을 첨부하세요",
    loadingQuestions: "질문 로딩...",
    beginAudit: "감사 시작",
    nOfMAnswered: "{a} {b} 대답했다",
    setup: "설정",
    prev: "이전",
    viewOverview: "개요 보기",
    next: "다음",
    stop: "멈춰",
    addPhoto: "사진 추가하세요",
    nPts: "{n}",
    critical: "비평",
    autoTask: "자동 작업",
    dueLabel: "기한:",
    immediately: "즉시",
    unassigned: "— 배정되지 않음 —",
    withinDays: "{d} 내에서",
    auditor: "감사관",
    scoreSummary: "{e} / {t} 점 · {c} {a} 대답했다",
    nThreshold: "{n}% 임계값",
    back: "뒤로",
  },
  tl_PH: {
    auditForm: "Form ng Pag-audit",
    auditQuestions: "Mga Tanong sa Pag-audit",
    clickToEdit: "Mag-click upang baguhin",
    yourNamePlaceholder: "Ang iyong pangalan",
    loadingYourName: "I-load ang Iyong Pangalan ...",
    storeAuditorDetails: "Mga Detalye ng Tindahan at Auditor",
    searchStorePlaceholder: "Hanapin {store} ...",
    loading: "Naglo-load...",
    auditDate: "Petsa ng Pag-audit",
    auditorName: "Pangalan ng Auditor",
    auditorNotes: "Mga Tala ng Auditor",
    auditorNotesPlaceholder: "Konteksto para sa sesyon ng pag-audit na ito ...",
    enterYourName: "Mangyaring ipasok ang iyong pangalan.",
    noQuestions: "Walang mga tanong",
    pass: "Pumasa",
    fail: "Nabigo",
    na: "N / A",
    poor: "Mahirap",
    excellent: "Napakahusay",
    reset: "I-reset",
    start: "Simulan",
    taskWillBeGenerated: "Ang gawain ay nabuo",
    noFailures: "Walang mga pagkabigo",
    allPassedOrNa: "Lahat ng sagot sa tanong ay pumasa o minarkahan ng N/A.",
    assignTo: "Magtalaga sa",
    groups: "Mga Grupo",
    people: "Mga Tao",
    searchPlaceholder: "Paghahanap...",
    auditSummary: "Buod ng Audit",
    passing: "Pagpasa",
    failing: "Pagkabigo",
    date: "Petsa",
    tasksFlagged: "Mga gawain na na-flag",
    notes: "Mga Tala",
    categoryBreakdown: "Pagkasira ng Kategorya",
    tasksToCreate: "Mga Gawain na Lumikha",
    working: "Nagtatrabaho ...",
    noPeopleFound: "Walang natagpuan na tao",
    noGroupsFound: "Walang natagpuang grupo",
    submitCreateTasks: "Isumite at Lumikha ng Mga Gawain",
    submitting: "Pagsusumite...",
    auditSubmittedMsg: "Isinumite ang audit! &#34;{name}&#34; na nilikha gamit ang {n} mga gawain.",
    edit: "baguhin",
    loadingStore: "Pag-load {store} ...",
    selectStore: "Pumili ng isang {store} ...",
    optional: "(opsyonal)",
    attachPhotoFile: "Ilakip ang larawan o file",
    loadingQuestions: "Naglo-load ng mga katanungan ...",
    beginAudit: "Simulan ang Pag-audit",
    nOfMAnswered: "{a} ng {b} ang sumagot",
    setup: "Pag-setup",
    prev: "Nakaraan",
    viewOverview: "Tingnan ang Pangkalahatang-ideya",
    next: "Susunod",
    stop: "Tumigil",
    addPhoto: "Email Address *",
    nPts: "{n} pts",
    critical: "Kritikal",
    autoTask: "Awtomatikong gawain",
    dueLabel: "Dahil sa:",
    immediately: "Agad",
    unassigned: "— Hindi nakatalaga —",
    withinDays: "Sa loob ng {d}d",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} pts · {a} ng {c} ang sumagot",
    nThreshold: "{n}% threshold",
    back: "Bumalik",
  },
  pt_BR: {
    auditForm: "Formulário de Auditoria",
    auditQuestions: "Perguntas de Auditoria",
    clickToEdit: "Clique para editar",
    yourNamePlaceholder: "Seu nome",
    loadingYourName: "Carregando seu nome...",
    storeAuditorDetails: "Detalhes de Loja e Auditor",
    searchStorePlaceholder: "Procurem {store}...",
    loading: "Carregando...",
    auditDate: "Data da Auditoria",
    auditorName: "Nome do Auditor",
    auditorNotes: "Notas do Auditor",
    auditorNotesPlaceholder: "Contexto para esta sessão de auditoria...",
    enterYourName: "Por favor, insira seu nome.",
    noQuestions: "Sem perguntas",
    pass: "Passe",
    fail: "Fracasso",
    na: "N/A",
    poor: "Pobre",
    excellent: "Excelente",
    reset: "Reiniciar",
    start: "Comece",
    taskWillBeGenerated: "A tarefa será gerada",
    noFailures: "Sem falhas",
    allPassedOrNa: "Todas as perguntas respondidas passaram ou foram marcadas N/A.",
    assignTo: "Atribuir a",
    groups: "Grupos",
    people: "Pessoas",
    searchPlaceholder: "Procurar...",
    auditSummary: "Resumo da Auditoria",
    passing: "Passagem",
    failing: "Fracasso",
    date: "Data",
    tasksFlagged: "Tarefas sinalizadas",
    notes: "Notas",
    categoryBreakdown: "Distribuição por Categorias",
    tasksToCreate: "Tarefas a Criar",
    working: "Trabalhando...",
    noPeopleFound: "Nenhuma pessoa encontrada",
    noGroupsFound: "Nenhum grupo encontrado",
    submitCreateTasks: "Enviar e Criar Tarefas",
    submitting: "Submetendo...",
    auditSubmittedMsg: "Auditoria enviada! &#34;{name}&#34; criado com {n} tarefas.",
    edit: "Editar",
    loadingStore: "Carregando {store}...",
    selectStore: "Escolha um {store}...",
    optional: "(opcional)",
    attachPhotoFile: "Anexe foto ou arquivo",
    loadingQuestions: "Carregando perguntas...",
    beginAudit: "Início da Auditoria",
    nOfMAnswered: "{a} de {b} respondido",
    setup: "Configuração",
    prev: "Anterior",
    viewOverview: "Ver Visão Geral",
    next: "Próximo",
    stop: "Pare",
    addPhoto: "Adicionar foto",
    nPts: "{n} Pts",
    critical: "Crítica",
    autoTask: "Auto-tarefa",
    dueLabel: "Prazo:",
    immediately: "Imediatamente",
    unassigned: "— Não atribuído —",
    withinDays: "Dentro de {d}",
    auditor: "Auditor",
    scoreSummary: "{e} / {t} pts · {a} de {c} respondido",
    nThreshold: "Limiar de {n}%",
    back: "Voltar",
  },
  ht_HT: {
    auditForm: "Fòm odit",
    auditQuestions: "Kesyon odit",
    clickToEdit: "Klike sou pou edite",
    yourNamePlaceholder: "Non ou",
    loadingYourName: "Loading non ou...",
    storeAuditorDetails: "Store & Odit Detay",
    searchStorePlaceholder: "Rechèch {store}...",
    loading: "Chaje ...",
    auditDate: "Dat odit",
    auditorName: "Non oditè",
    auditorNotes: "Nòt Odit",
    auditorNotesPlaceholder: "Context pou sesyon odit sa a...",
    enterYourName: "Tanpri antre non ou.",
    noQuestions: "Pa gen kesyon",
    pass: "Pase",
    fail: "Echwe",
    na: "NAN/A",
    poor: "Pòv",
    excellent: "Ekselan",
    reset: "Reyajiste",
    start: "Kòmanse",
    taskWillBeGenerated: "Travay yo pral pwodwi",
    noFailures: "Pa gen echèk",
    allPassedOrNa: "Tout kesyon reponn yo te pase oswa yo te make N / A.",
    assignTo: "Asiyen a",
    groups: "Gwoup yo",
    people: "Moun",
    searchPlaceholder: "Rechèch...",
    auditSummary: "Rezime odit",
    passing: "Pase",
    failing: "Echwe",
    date: "Dat",
    tasksFlagged: "Travay ki make",
    notes: "Nòt yo",
    categoryBreakdown: "Kategori pann",
    tasksToCreate: "Travay yo kreye",
    working: "Travay ...",
    noPeopleFound: "Pa gen moun ki te jwenn",
    noGroupsFound: "Pa gen gwoup yo te jwenn",
    submitCreateTasks: "Soumèt & Kreye Travay",
    submitting: "Soumèt ...",
    auditSubmittedMsg: "Odit soumèt! &#34;{name}&#34; kreye ak {n} travay.",
    edit: "modifye",
    loadingStore: "Loading {store}...",
    selectStore: "Chwazi yon {store}...",
    optional: "(si ou vle)",
    attachPhotoFile: "Tache foto oswa dosye",
    loadingQuestions: "Chaje kesyon ...",
    beginAudit: "Kòmanse Odit",
    nOfMAnswered: "{a} nan {b} reponn",
    setup: "Konfigirasyon",
    prev: "Prev",
    viewOverview: "View Apèsi sou lekòl la",
    next: "Next",
    stop: "Rete",
    addPhoto: "Ajoute foto",
    nPts: "{n} pts",
    critical: "Kritik",
    autoTask: "Oto-travay",
    dueLabel: "Akòz:",
    immediately: "Imedyatman",
    unassigned: "— Ki pa asiyen —",
    withinDays: "Nan {d} d",
    auditor: "Oditè",
    scoreSummary: "{e} / {t} pts · {a} nan {c} reponn",
    nThreshold: "{n}% papòt",
    back: "Do",
  },
};